### ISSUE TITLE
hauk@2.16.3 old version

### ISSUE THREAD

**Issue by Koulouri** [eouia/MMM-Hotword#10]
While trying to install the MMM-hotword, in both ways the readme file suggests.. i come across an error.
The **error** says, that _the version of **hauk@2.16.3 is not supported** any more_. Thus, im not able to install the MMM-Hotword module. Is there any way around it? Is it possible that the creator updates the file? Any advice is much apreciated!

**Comment by eouia** [comment]
My module itself doesn't use `hauk` (I don't even know what it is...) But some dependencies might need that module. Which location is `hauk` under? You can install it by yourself in proper position. (Or, you can install `hauk` globally with `sudo npm install -g hauk`)

**Comment by Koulouri** [comment]
I will try, and tell you the results.. thanks

**Comment by Koulouri** [comment]
First of all, i want to apologise for spelling hoek, hauk.. ;) im a total beginner!
So, after installing hoek (version 5.0.4) successfully, i tried installing the hotword module again..
This is the error.. 

![26070b3c-8cb9-4a23-a712-de6c1198dc0c](https://user-images.githubusercontent.com/39415186/46611994-08acdc00-cb18-11e8-99b0-8955487454eb.jpeg)
![f788c8b8-7891-45e8-a92f-a279b9fc3490](https://user-images.githubusercontent.com/39415186/46611997-09457280-cb18-11e8-972f-26f89dab97c2.jpeg)

I really can’t understand why this happens..

**Comment by eouia** [comment]
Your node version seems not matched with pre-built snowboy binaries. So, npm try to build binaries by itself, but failed. Because, the `nan` module isn't there.
Try this.
```
sudo apt-get install libmagic-dev libatlas-base-dev
sudo apt-get install sox libsox-fmt-all
npm install -g nan
```
Then try again.

**Comment by Koulouri** [comment]
There seem to be less errors and more warnings! However.. hotword won’t install!

![0e236f7a-87aa-482d-91ce-7c3f7decb715](https://user-images.githubusercontent.com/39415186/46626137-16298c80-cb3f-11e8-9bd9-d26d1a3d34a5.jpeg)
![cb17bca7-134e-468e-84cd-972bf56bde21](https://user-images.githubusercontent.com/39415186/46626138-16298c80-cb3f-11e8-85d4-9d901d6f54af.jpeg)

**Comment by eouia** [comment]
First, do not use `sudo` to install MM modules.
So, not `sudo npm install`, just execute `npm install`, your permission errors are due to that.

**Comment by Koulouri** [comment]
Well, due to that I mistakenly thought that sudo would solve the issue!

![41492540-d44b-4a8f-8112-f375efb2b17c](https://user-images.githubusercontent.com/39415186/46627086-fa73b580-cb41-11e8-9596-caceab87e722.jpeg)

**Comment by eouia** [comment]
Remove whole MMM-Hotword and reinstall again without using `sudo`. I think you'd used `sudo` when you had installed `git clone` or prior something, thus there seems to be permission problem.
Usually, Only installation of dependencies with `apt` needs `sudo` to acquire global permission. Normal installment of MM  & modules don't need any `sudo` permission.

**Comment by Koulouri** [comment]
How do i delete it? Drag and drop on the recycle bin or there is a code i need to type in?

**Comment by eouia** [comment]
try this first.
```
cd ~/MagicMirror/modules
rm -rf MMM-Hotword
```

If failed,
```
cd ~/MagicMirror/modules
sudo rm -rf MMM-Hotword
```
But.. the `rm -rf` command is very dangerous. use it carefully.

**Comment by Koulouri** [comment]
Well, i got it installed after reinstalling raspbian (who knows how many sudo commands had i done?)
So, AssistantMk2, Hotword and NotificationTrigger are installed (all in the MagicMirror folder) 
Should i configure any of the assistant related modules?

**Comment by eouia** [comment]
If you installed without any issue, it will work with example confgiuration.

**Comment by eouia** [comment]
Have you solved this problem? I'll close this issue. You can leave any further question.
I wish you have a good luck.

**Comment by Koulouri** [comment]
Well, everything is installed! However, The Assistant module doesn't seem to be working. i start the MagicMirror module and then, say the hotwords for the assistant. Nothing happens. I don't know whether it is a sound driver (mic not using the driver, the GA is using) or anything else.. Im loosing Hope :(
