### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by tanvir586** [eouia/MMM-Hotword#100]
Do git pull to update or have to remove old one and fresh install?

**Comment by eouia** [comment]
For the last update at this moment, you don't need to clean install, just do `git pull`.

**Comment by tanvir586** [comment]
Thanks.

**Comment by tanvir586** [comment]
Received this error while updating..

pi@SMART-MIRROR:~/MagicMirror/modules/MMM-Hotword $ git pull
Updating 47b24ce..5052ca4
error: Your local changes to the following files would be overwritten by merge:
	MMM-Hotword.js
Please commit your changes or stash them before you merge.
Aborting

**Comment by eouia** [comment]
Maybe you modified the original source. remove that file and pull again.

**Comment by tanvir586** [comment]
Worked perfectly.  Thanks sean you're genius...
