### ISSUE TITLE
Can't detect mic after boot.

### ISSUE THREAD

**Issue by Corestorm** [eouia/MMM-Hotword#109]
**[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }**

 Tried using .asoundrc file to get around it but it didn't work. It doesn't detect my mic after boot. If i unplug the mic and plug it back It immeadetly detects. I just have to unplug and plug my mic back after boot and it starts working. That's probably not a error about hotword but I thought you might have the fix for this.

**Comment by eouia** [comment]
Usually, this symptom will happen when your mic is not prepared. There could be various reasons.
- H/W problem
- Invalid ALSA config
- Other process being occupying or trying to occupy mic at same time.

I think yours might be H/W issue. At this moment I have no idea about it. I'll research but no guarantee.
