### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by miggoust** [eouia/MMM-Hotword#11]
Hi, quite new to raspbian environment, but there seems to be a syntax error in one of the config lines. I can't run the hotword module. Assistant works fantastically!

**Comment by eouia** [comment]
Can you show me your hotword config?

**Comment by miggoust** [comment]
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "fi",
	timeFormat: 24,
	units: "metric",
	
		modules: [
			{
				module: "alert",
			},
			{
				module: "updatenotification",
				position: "top_bar"
			},
			{
				module: "clock",
				position: "top_left"
			},
			{
				module: "calendar",
				header: "Kalenteri",
				position: "top_left",
				config: {
					calendars: [
						{
							symbol: "GoogleKalenteri",
							url: "https://calendar.google.com/calendar/ical/mikko1334%40gmail.com/private-4b4a50cabb5efed3e17d9d2078291743/basic.ics"
						},
						{
							symbol: "StudentKalenteri",
							url: "https://outlook.office365.com/owa/calendar/bcf2013aa3a24cd3a0e590f17a67d912@student.lut.fi/132e90fe778f4bbeb9906629f321199512159717785854863298/calendar.ics"
						}
					]
				}
			},
			{
				module: "compliments",
				position: "lower_third"
			},
			{
				module: "currentweather",
				position: "top_right",
				config: {
					location: "Lappeenranta",
					locationID: "648901",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
					appid: "f439a6cfb3691c7e2b9e163a506cd98d"
				}
			},
			{
				module: "weatherforecast",
				position: "top_right",
				header: "Sääennuste",
				config: {
					location: "Lappeenranta",
					locationID: "648901",  //ID from http://www.openweathermap.org/help/city_list.txt
					appid: "f439a6cfb3691c7e2b9e163a506cd98d"
				}
			},
			{
				module: "newsfeed",
				position: "bottom_bar",
				config: {
					feeds: [
						{
							title: "Helsingin Sanomat",
							url: "https://www.hs.fi/rss/teasers/etusivu.xml"
						}
					],
					showSourceTitle: true,
					showPublishDate: true
				}
			},
			//{
			      //module: "MMM-NotificationTrigger",
			      //config: {}
			//},
			{
			  module: 'MMM-Hotword',
			  config: {
			    snowboy: [
			  {
			    hotwords: "smartmirror", //this will be sent to other module for distinguishing which hotword is detected.
			    file: "resources/models/smart_mirror.umdl",
			    sensitivity: '0.5',
			  },
			  {
			    hotwords: "snowboy",
			    file: "resources/models/snowboy.umdl",
			    sensitivity: '0.5',
			  },
			  {
			    file: 'resources/models/jarvis.umdl',
			    sensitivity: '0.8,0.80',
			    hotwords: ['jarvis','jarvis'] //Kitt.ai changed their Jarvis UMDL, it has 2 models in one file. So weird.
			    //anyway, you can give different name for each. ['jarvis_1', 'jarvis_2']. Even though I think this is useless.
			  }
			    ],
			    record: {
			      sampleRate    : 16000,      // audio sample rate
			      threshold     : 0.5,        // silence threshold (rec only)
			      thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
			      thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
			      silence       : 1.0,        // seconds of silence before ending
			      verbose       : false,      // log info to the console. Use this when you want to check mic working or not.
			      recordProgram : "arecord",  // Defaults to 'arecord' - also supports 'rec' and 'sox'
			      device        : "plughw:1,0"        // recording device (e.g.: 'plughw:1')
			    },
			    autostart: true              // if 'false', this module will wait for 'HOTWORD_RESUME' notification to start hotwords detection at the beginning.
			    autorestart: false          // You can set this 'true' when you want this module to go back to listening mode automatically again after hotword is detected. But use this carefully when your other modules are using microphone or speaker.
			
			    // customizable notification trigger
			    notifications: {
			      PAUSE: "HOTWORD_PAUSE",
			      RESUME: "HOTWORD_RESUME",
			      LISTENING : "HOTWORD_LISTENING",
			      SLEEPING : "HOTWORD_SLEEPING",
			      ERROR : "HOTWORD_ERROR",
			    },
			    onDetected: {
			      notification: (payload) => {
			        return "HOTWORD_DETECTED"
			      },
			      payload: (payload) => {
			        return payload
			      }
			    },
			  }
			},
			{
			  module: "MMM-AssistantMk2",
			  position: "top_right",
			  config: {
			
			    // --- ESSENTIALS / modifying for your environment might be needed.
			
			
			    deviceLocation: {
			      coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
			        latitude: 51.5033640, // -90.0 - +90.0
			        longitude: -0.1276250, // -180.0 - +180.0
			      },
			    },
			
			    defaultProfile: "default", // If you have several profiles and want to set one of them as default profile, describe here.
			
			    profiles: {
			      "default" : { // profile name.
			        profileFile: "default.json", // profile file name.
			        lang: "en-US"
			        //currently available (estimation, not all tested):
			        //  de-DE, en-AU, en-CA, en-GB, en-US, en-IN
			        // fr-CA, fr-FR, it-IT, ja-JP, es-ES, es-MX, ko-KR, pt-BR
			        // https://developers.google.com/assistant/sdk/reference/rpc/languages
			      },
			      /* Add your other profiles here, if exists.
			      "other_profile" : {
			        profileFile: "other.json",
			        lang: "de-DE"
			      }
			      */
			    },
			
			    record: { // Full values are in `FOR EXPERTS` section.
			      recordProgram: "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
			      device: "plughw:1,0"        // recording device (e.g.: "plughw:1")
			    },
			
			    play: { // Full values are in `FOR EXPERTS` section.
			      playProgram: "mpg321", // recommended.
			    },
			
			
			    // --- OPTIONAL / not important but customizable for your usage
			
			
			    responseVoice: true, // If available, Assistant will response with her voice.
			    responseScreen: true, // If available, Assistant will response with some rendered HTML
			    responseAlert: true, // If available, Assistant will response with Alert module of MM
			    // Sometimes, any response might not be returned. responseAlert is useful for displaying error.
			
			    screenZoom: "80%", // Adjust responseScreen to your mirror size.
			    screenDuration: 0, // milliseconds. How long responseScreen will be shown after speech.
			    //If you set 0, Screen Output will be closed after Response speech finishes ASAP.
			
			    youtubeAutoplay: true, //If set as true, found Youtube video will be played automatically.
			    pauseOnYoutube:true, //If set as true, You cannot activate Assistant during youtube playing. Recommended for the performance (Because permanent hotword detecting might make performance lower)
			
			    useWelcomeMessage: "beif today", //Try "brief today" as this value. You can use this value to check module working when MM is starting.
  }
			},
			{
				  module: "MMM-NowPlayingOnSpotify",
				  position: "top_left",
				
				  config: {
				    clientID: "6240771ce2cb4c48bc82e9b393615a00",
				    clientSecret: "1a2ed44fcc8a448c94e545eda4c7306b",
				    accessToken: "BQD74UI3eUIZQsSqu37_wcFb8KyiyUQ6dW_Dybxf7LSUa5ZEO268P3aBrEl-LFbC4-_Bn9rsCoNzzmTOvbNmjr-pbKiJoqKgdBfejFZHz1stVNf8Cow438Npm_YYwS-6MoJ7IazV4qSJm7xahREUStR_VG8",
				    refreshToken: "AQB9VMU35B7n14LIkFnMcJ4-Tx5bUSZIT0XXdvPF6F2LPIZP-HC6i7gewmF-uHlFPNJieSLzLWl1ZdZ0vnpfI39eivGpNQPle_gkN1MW5ZUi9yeyisw_jdCOaW0BDsDuzAnoeA"
				   }
},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

Here is the full config, when I remove the Hotword, it works fine

**Comment by miggoust** [comment]
When I remove this, it works fine.
			{
			  module: 'MMM-Hotword',
			  config: {
			    snowboy: [
			  {
			    hotwords: "smartmirror", //this will be sent to other module for distinguishing which hotword is detected.
			    file: "resources/models/smart_mirror.umdl",
			    sensitivity: '0.5',
			  },
			  {
			    hotwords: "snowboy",
			    file: "resources/models/snowboy.umdl",
			    sensitivity: '0.5',
			  },
			  {
			    file: 'resources/models/jarvis.umdl',
			    sensitivity: '0.8,0.80',
			    hotwords: ['jarvis','jarvis'] //Kitt.ai changed their Jarvis UMDL, it has 2 models in one file. So weird.
			    //anyway, you can give different name for each. ['jarvis_1', 'jarvis_2']. Even though I think this is useless.
			  }
			    ],
			    record: {
			      sampleRate    : 16000,      // audio sample rate
			      threshold     : 0.5,        // silence threshold (rec only)
			      thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
			      thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
			      silence       : 1.0,        // seconds of silence before ending
			      verbose       : false,      // log info to the console. Use this when you want to check mic working or not.
			      recordProgram : 'arecord',  // Defaults to 'arecord' - also supports 'rec' and 'sox'
			      device        : null        // recording device (e.g.: 'plughw:1')
			    },
			    autostart: true              // if 'false', this module will wait for 'HOTWORD_RESUME' notification to start hotwords detection at the beginning.
			    autorestart: false          // You can set this 'true' when you want this module to go back to listening mode automatically again after hotword is detected. But use this carefully when your other modules are using microphone or speaker.
			
			    // customizable notification trigger
			    notifications: {
			      PAUSE: "HOTWORD_PAUSE",
			      RESUME: "HOTWORD_RESUME",
			      LISTENING : "HOTWORD_LISTENING",
			      SLEEPING : "HOTWORD_SLEEPING",
			      ERROR : "HOTWORD_ERROR",
			    },
			    onDetected: {
			      notification: (payload) => {
			        return "HOTWORD_DETECTED"
			      },
			      payload: (payload) => {
			        return payload
			      }
			    },
			  }
			},

**Comment by miggoust** [comment]
`
			{
			  module: 'MMM-Hotword',
			  config: {
			    snowboy: [
			  {
			    hotwords: "smartmirror", //this will be sent to other module for distinguishing which hotword is detected.
			    file: "resources/models/smart_mirror.umdl",
			    sensitivity: '0.5',
			  },
			  {
			    hotwords: "snowboy",
			    file: "resources/models/snowboy.umdl",
			    sensitivity: '0.5',
			  },
			  {
			    file: 'resources/models/jarvis.umdl',
			    sensitivity: '0.8,0.80',
			    hotwords: ['jarvis','jarvis'] //Kitt.ai changed their Jarvis UMDL, it has 2 models in one file. So weird.
			    //anyway, you can give different name for each. ['jarvis_1', 'jarvis_2']. Even though I think this is useless.
			  }
			    ],
			    record: {
			      sampleRate    : 16000,      // audio sample rate
			      threshold     : 0.5,        // silence threshold (rec only)
			      thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
			      thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
			      silence       : 1.0,        // seconds of silence before ending
			      verbose       : false,      // log info to the console. Use this when you want to check mic working or not.
			      recordProgram : 'arecord',  // Defaults to 'arecord' - also supports 'rec' and 'sox'
			      device        : null        // recording device (e.g.: 'plughw:1')
			    },
			    autostart: true              // if 'false', this module will wait for 'HOTWORD_RESUME' notification to start hotwords detection at the beginning.
			    autorestart: false          // You can set this 'true' when you want this module to go back to listening mode automatically again after hotword is detected. But use this carefully when your other modules are using microphone or speaker.
			
			    // customizable notification trigger
			    notifications: {
			      PAUSE: "HOTWORD_PAUSE",
			      RESUME: "HOTWORD_RESUME",
			      LISTENING : "HOTWORD_LISTENING",
			      SLEEPING : "HOTWORD_SLEEPING",
			      ERROR : "HOTWORD_ERROR",
			    },
			    onDetected: {
			      notification: (payload) => {
			        return "HOTWORD_DETECTED"
			      },
			      payload: (payload) => {
			        return payload
			      }
			    },
			  }
			},`

**Comment by eouia** [comment]
You don't use all of my documents.
```
{
    module: "MMM-Hotword",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1", // Change this to your mic device.
      },
      autostart:true,
      onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },
    },
  },
```

**Comment by eouia** [comment]
And I've found what was wrong.
I'd missed comma after `autostart` and `autorestart`

**Comment by miggoust** [comment]
Great! It started working!
Now he answers one time but when I try it again, he won't answer?

**Comment by eouia** [comment]
I think you'd missed something still.
See https://github.com/eouia/MMM-AssistantMk2/blob/master/CONFIGURATION.md#with-mmm-hotword-using-usb-mic-plughw1

```
notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      },
```
might be missed?

**Comment by miggoust** [comment]
Started working correctly now!
This assistant doesn't seem to be able to cast anything on my chromecast, is there a command that I've missed again?:o

**Comment by eouia** [comment]
Unfortunately, this is `Assistant emebeded on Device`, not `Google Home` or `Google Assistant` itself. That is missed function, I think.

**Comment by miggoust** [comment]
Ok, but everything else seems to be working allright.

**Comment by eouia** [comment]
I'll close this issue. Have a nice day.
