### ISSUE TITLE
I can't start Magic Mirror with hotword.

### ISSUE THREAD

**Issue by iBoy1211** [eouia/MMM-Hotword#110]
Hi,
Can i get help please i am trying to solve this for a long time but i cany.

pi@raspberry:~/MagicMirror $ npm start

magicmirror@2.9.0 start /home/pi/MagicMirror
sh run-start.sh

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
No helper found for module: MMM-Hello-Mirror.
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: MMM-SystemStats
Initializing new module helper ...
Module helper loaded: MMM-AQI
Initializing new module helper ...
Module helper loaded: MMM-NotificationTrigger
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-GmailFeed
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: MMM-SystemStats
Connecting socket for: MMM-AQI
MMM-AQI helper started ...
Connecting socket for: MMM-NotificationTrigger
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-GmailFeed
MMM-GmailFeed helper started...
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Sockets connected & modules started ...
Xlib:  extension "XInputExtension" missing on display ":1.0".
Xlib:  extension "RANDR" missing on display ":1.0".
Launching application.
Xlib:  extension "XInputExtension" missing on display ":1.0".
Xlib:  extension "XInputExtension" missing on display ":1.0".
Create new news fetcher for url: https://press24.mk/taxonomy/term/7/feed - Interval: 300000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
/home/pi/MagicMirror/node_modules/electron/dist/electron js/electron.js: symbol lookup error: /home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/electron-v3.0-linux-ia32/snowboy.node: undefined symbol: ZN7snowboy13SnowboyDetectC1ERKSsS2
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! magicmirror@2.9.0 start: sh run-start.sh
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the magicmirror@2.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-12-29T16_37_56_069Z-debug.log

[2019-12-29T16_37_56_069Z-debug.log](https://github.com/eouia/MMM-Hotword/files/4008276/2019-12-29T16_37_56_069Z-debug.log)

![Screenshot (25)](https://user-images.githubusercontent.com/59339937/71560381-7456ce00-2a69-11ea-8aa1-e374ba8da5fb.png)

**Comment by android9pie2** [comment]
It looks like something may have went haywire during install. What operating system are you running, and what kinda machine?

**Comment by android9pie2** [comment]
I can try to help, but I'm having different issues installing dependencies and building Hotword.

**Comment by android9pie2** [comment]
I'm also a newbie to this stuff.

**Comment by iBoy1211** [comment]
I am using old laptop with debian on it.

**Comment by eouia** [comment]
Sorry for late answer. 
Snowboy is not supporting IA32(32bit Intel machine)
Supported devices are here; https://github.com/Kitt-AI/snowboy#introduction
![image](https://user-images.githubusercontent.com/1720610/71662370-84b0c680-2d51-11ea-998f-59cd0b529bd5.png)

**Comment by iBoy1211** [comment]
so if it is not supported how can i use mmm-assistantmk2?

**Comment by eouia** [comment]
MMM-AssistantMk2 is separated from MMM-Hotword itself. You can use any module which can detect your trigger action and emit some notification as a result to activate MMM-AssistantMk2 (For example; button clicking with MMM-Button, if supported)

**Comment by iBoy1211** [comment]
are there any other? and how to activate it can i get help?

**Comment by eouia** [comment]
Any other? Ideally, all of modules which can detect your input and broadcast notification, could be possible. Especially which? I don't know. Which to use is your mission for your purpose. This is DIY project, so there is no ready-made-out-of-box state things.

**Comment by iBoy1211** [comment]
I am new to this, but because i use laptop, so i don't know how can i make it work what should i use.

**Comment by eouia** [comment]
So, If you are using a laptop, which method do you consider as the trigger? For example, MMM-Clap can detect your hand clapping, so it can be used as an awakener of MMM-AssistantMk2. 
But.. for real usage, I recommend that you use RPI (or at least ARM-based SBC) instead intel machine. Because many modules of MagicMirror are developed as executed on RPI by default. So you cannot use some modules on your intel machine.

**Comment by iBoy1211** [comment]
For now every module works fine, now i will try mmm-calp lets see if it works.

**Comment by iBoy1211** [comment]
Can i get help with recording device?

**Comment by iBoy1211** [comment]
Okay that works now how to make it work on assistant

**Comment by eouia** [comment]
For MMM-Clap configuration, See this;
https://github.com/eouia/MMM-Clap#activate-mmm-assistantmk2

Then add these into your MMM-AssistantMk2 configuration
```js
onIdle: {
  timer: 100,
  command: "RESUME_CLAP",
},

onActivate: {
  timer: 100,
  command: "PAUSE_CLAP",
},

command: {
  "RESUME_CLAP": {
    notificationExec: {
      notification: "CLAP_RESUME"
    }
  },
  "PAUSE_CLAP": {
    notificationExec: {
      notification: "CLAP_PAUSE"
    }
  }
}
```
I didn't test this code on real machine, because I'm not with it. But you can catch the theory.

**Comment by iBoy1211** [comment]
I use this, assistant started working but still have issues.

{
  module: "MMM-AssistantMk2",
  position: "bottom_right",
  config: {

    // --- ESSENTIALS / modifying for your environment might be needed.


    deviceLocation: {
      coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
        latitude: 51.5033640, // -90.0 - +90.0
        longitude: -0.1276250, // -180.0 - +180.0
      },
    },

    defaultProfile: "default", // If you have several profiles and want to set one of them as default profile, describe here.

    profiles: {
      "default" : { // profile name.
        profileFile: "default.json", // profile file name.
        lang: "en-US"
        //currently available (estimation, not all tested):
        //  de-DE, en-AU, en-CA, en-GB, en-US, en-IN
        // fr-CA, fr-FR, it-IT, ja-JP, es-ES, es-MX, ko-KR, pt-BR
        // https://developers.google.com/assistant/sdk/reference/rpc/languages
      },
      /* Add your other profiles here, if exists.
      "other_profile" : {
        profileFile: "other.json",
        lang: "de-DE"
      }
      */
    },

    record: { // Full values are in `FOR EXPERTS` section.
      recordProgram: "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
      device: null        // recording device (e.g.: "plughw:1")
    },

    play: { // Full values are in `FOR EXPERTS` section.
      playProgram: "mpg321", // recommended.
    },


    // --- OPTIONAL / not important but customizable for your usage


    responseVoice: true, // If available, Assistant will response with her voice.
    responseScreen: true, // If available, Assistant will response with some rendered HTML
    responseAlert: true, // If available, Assistant will response with Alert module of MM
    // Sometimes, any response might not be returned. responseAlert is useful for displaying error.

    screenZoom: "80%", // Adjust responseScreen to your mirror size.
    screenDuration: 0, // milliseconds. How long responseScreen will be shown after speech.
    //If you set 0, Screen Output will be closed after Response speech finishes ASAP.

    youtubeAutoplay: true, //If set as true, found Youtube video will be played automatically.
    pauseOnYoutube:true, //If set as true, You cannot activate Assistant during youtube playing. Recommended for the performance (Because permanent hotword detecting might make performance lower)

    youtubePlayerVars: { // You can set youtube playerVars for your purpose, but should be careful.
      "controls": 0,
      "loop": 1,
      "rel": 0,
    },
    youtubePlayQuality: "default", //small, medium, large, hd720, hd1080, highres or default

    useWelcomeMessage: "", //Try "brief today" as this value. You can use this value to check module working when MM is starting.

    onIdle: {
      //timer: 1000*60*30, // if you don't want to use this feature, just set timer as `0` or command as ""
      //command: "HIDEMODULES",
      timer: 0,
      command: null,
    },

    onActivate: {
      timer: 0,
      //command: "SHOWMODULES"
      command: null,
    },


    // --- FOR EXPERTS / For development, debug or more


    verbose:false, // You can get error or some logs when this value is set as true.
    ignoreNoVoiceError: true, //To avoid some annoying youtube stop bug.

    startChime: "connection.mp3", // you can use `mp3` to play chime when your mic is ready. It should be playable with your `play.playProgram`
    noChimeOnSay: false, // When using the `ASSISTANT_SAY` trigger, you can prevent the chime from being played before your words

    auth: { // I believe you don't need to change this.
      keyFilePath: "./credentials.json"
    },

    record:  { // Full version
      sampleRate    : 16000,      // audio sample rate
      threshold     : 0.5,        // silence threshold (rec only)
      thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
      thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
      silence       : 1.0,        // seconds of silence before ending
      verbose       : false,      // log info to the console
      recordProgram : "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
      device        : null        // recording device (e.g.: "plughw:1")
    },

    play: { // Full version
      encodingOut: "MP3", //'MP3' or 'WAV' is available, but you might not need to modify this.
      sampleRateOut: 24000,
      playProgram: "mpg321", //Your prefer sound play program. By example, if you are running this on OSX, `afplay` could be available.
      playOption: [],
      // If you need additional options to use playProgram, describe here. (except filename)
      // e.g: ["-d", "", "-t", "100"]
    },

    useGactionCLI: false, // If set as true, you can update your gAction when MM is rebooted.
    projectId: "", // Google Assistant ProjectId (Required only when you use gAction.)
    deviceModelId: "", // It should be described in your config.json. In most of case, you don't need to this.
    deviceInstanceId: "", // It should be described in your config.json. In most of case, you don't need to this.

    recipes:["hide_and_show_all_modules.js", "reboot.js", "screen_onoff.js", "shutdown.js"],
    transcriptionHook: {},
    action: {}, // You can catch your gAction command.
    command: {}, // You can catch transcription hook and be able to make your own `COMMAND` with this.
    //See the `transcriptionHook` section.
    action:{}, // You can make your own MM command for gAction and transcriptionHook
    //See the `command` section.

    notifications: { // You can redefine these notifications to communicate with specific modules.
      ASSISTANT_ACTIVATE: "ASSISTANT_ACTIVATE",
      ASSISTANT_DEACTIVATE: "ASSISTANT_CLEAR",
      ASSISTANT_ACTIVATED: "ASSISTANT_ACTIVATED",
      ASSISTANT_DEACTIVATED: "ASSISTANT_DEACTIVATED",
      ASSISTANT_ACTION: "ASSISTANT_ACTION",
      ASSISTANT_UNDERSTOOD: "ASSISTANT_UNDERSTOOD",
      ASSISTANT_RESPONSE_END: "ASSISTANT_RESPONSE_END",
      DEFAULT_HOOK_NOTIFICATION: "ASSISTANT_HOOK",
      TEXT_QUERY: "ASSISTANT_QUERY",
      SAY_TEXT: "ASSISTANT_SAY",
    }
  }
},

		{
  module: "MMM-Clap",
  position: "bottom_right",
  config: {
  useDisplay:true, // If you don't want to display this module, set this to `false`
  startOnBoot: true,
  detector: {
    recordBackbone: "alsa", // "waveaudio", "coreaudio"
    recordDevice: "-d", // "-d", "default"

    // For OSX :
      // recordBackbone : "coreaudio"
      // recordDevice : "default"
    // For Windows :
      // recordBackbone : "waveaudio"
      // recordDevice : "-d"

    thresholdDetectionStart: "5%", // minimum noise percentage threshold necessary to start recording sound (0~100%)
    thresholdDetectionEnd: "5%", // minimum noise percentage threshold necessary to end recording sound (0~100%)
    thresholdClapAmplitude: 0.7, // minimum amplitude threshold to be considered as clap (0~1)
    thresholdClapEnergy: 0.3, // maximum energy threshold to be considered as clap (0~1)
    duration: 500,
  },
  clapsTimeout:1000,
  sequenceTimeout:2000,
  defaultCommandMode: "DEFAULT",
  commands: {
    "DEFAULT": {
      "1": {
        notificationExec: {
          notification: "ASSISTANT_ACTIVATE",
          payload: {message: "default", timer:3000}
        },
        restart:true,
      },
    },
  }
},
},

**Comment by eouia** [comment]
First, you don't need a full detailed configuration for yourself. Furthermore, you don't do what you can't understand what you are doing.
All the full detailed values of configuration are set as default, so you do not need to describe all.
