### ISSUE TITLE
trouble with hotword

### ISSUE THREAD

**Issue by jasb1011** [eouia/MMM-Hotword#112]
hi, can you please tell me what is wrong with my hot word thank you.

pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release $ pm2 log
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/pi/.pm2/pm2.log last 15 lines:
PM2        | 2020-01-02T17:42:11: PM2 log: App [mm:0] exited with code [0] via signal [SIGINT]
PM2        | 2020-01-02T17:42:11: PM2 log: App [mm:0] starting in -fork mode-
PM2        | 2020-01-02T17:42:11: PM2 log: App [mm:0] online
PM2        | 2020-01-02T17:42:19: PM2 log: Stopping app:mm id:0
PM2        | 2020-01-02T17:42:20: PM2 log: App [mm:0] exited with code [0] via signal [SIGINT]
PM2        | 2020-01-02T17:42:20: PM2 log: pid=992 msg=process killed
PM2        | 2020-01-02T19:11:13: PM2 log: App [mm:0] starting in -fork mode-
PM2        | 2020-01-02T19:11:13: PM2 log: App [mm:0] online
PM2        | 2020-01-02T19:12:42: PM2 log: App [mm:0] exited with code [0] via signal [SIGINT]
PM2        | 2020-01-02T19:12:42: PM2 log: App [mm:0] starting in -fork mode-
PM2        | 2020-01-02T19:12:42: PM2 log: App [mm:0] online
PM2        | 2020-01-02T19:12:54: PM2 log: Stopping app:mm id:0
PM2        | 2020-01-02T19:12:55: PM2 log: pid=3293 msg=failed to kill - retrying in 100ms
PM2        | 2020-01-02T19:12:55: PM2 log: App [mm:0] exited with code [0] via signal [SIGINT]
PM2        | 2020-01-02T19:12:55: PM2 log: pid=3293 msg=process killed

/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:711:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:620:32)
0|mm       | { Error: Cannot find module './snowboy/lib/node/index.js'
0|mm       |     at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
0|mm       |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|mm       |     at Function.Module._load (internal/modules/cjs/loader.js:528:25)
0|mm       |     at Module.require (internal/modules/cjs/loader.js:658:17)
0|mm       |     at require (internal/modules/cjs/helpers.js:20:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:11:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:234:3)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:711:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
0|mm       | ATTENTION: default value of option force_s3tc_enable overridden by environment.

/home/pi/.pm2/logs/mm-out.log last 15 lines:
0|mm       | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm       | Launching application.
0|mm       | Shutting down server...
0|mm       | Stopping module helper: updatenotification
0|mm       | Stopping module helper: calendar
0|mm       | Stopping module helper: newsfeed
0|mm       | Stopping module helper: MMM-AssistantMk2
0|mm       | Stopping module helper: updatenotification
0|mm       | Stopping module helper: calendar
0|mm       | Stopping module helper: newsfeed
0|mm       | Stopping module helper: MMM-AssistantMk2
0|mm       | 
0|mm       | > magicmirror@2.8.0 start /home/pi/MagicMirror
0|mm       | > sh run-start.sh
0|mm       |

**Comment by eouia** [comment]
You have failed or missed something on installation. your MMM-Hotword is not installed properly.

**Comment by jasb1011** [comment]
So how do I fix the issue

**Comment by eouia** [comment]
? install freshly. I don't know which step you have failed. What did you do?

**Comment by jasb1011** [comment]
Honestly, When I updated Hotword and restarted my Magic Mirror this happened

**Comment by eouia** [comment]
Yes, this means your update was failed. so need to reinstall. (I think you had to `electron-rebuild` step after `git pull` but you might have hadn't)

**Comment by jasb1011** [comment]
Ok, how do I uninstall it

**Comment by eouia** [comment]
just remove directory. I think you'd better be familiar with basic MagicMirror usage. How about trying easier modules before? This module is quite notorious for its difficulty.

**Comment by bugsounet** [comment]
@jasb1011 : 
we have modified the installation procedure (under test)
you can now execute npm install after cloning the repository.
let yourself be guided by npm install auto installer.
