### ISSUE TITLE
Old version of files

### ISSUE THREAD

**Issue by Koulouri** [eouia/MMM-Hotword#12]
hoek ,cryptiles and boom appear after a warning on the installiation. it says that their version in no longer maintained. Should that be an issue? Every time i add the hotword to my modules list, the MagicMirror doesn't start all the way; then, i only see my cursor. I have updated to the latest stretch version by the way

**Comment by eouia** [comment]
I think it is same issue (https://github.com/eouia/MMM-Hotword/issues/10) from you. Have you not solved this issue yet?

**Comment by Koulouri** [comment]
No,I haven't yet! I got the assistant module to work however by changing the file's location. Now every module is inside the default modules file but hot word still doesn't work!

**Comment by eouia** [comment]
Wow, you installed 3rd modules in default module directory???? And by that modules became working?
I think all your problems might be caused by incomplete installation. If I was, I’ll retry from whole new installation.

Anyway, your picture shows snowboy is installed.(ignore the warnings)
Remaining is recompiling snowboy for electron.

**Comment by Marcreed48** [comment]
I think the “wow” is because only the defaults should be in the default
folder. Your gits and installs (mmm-modules) should be in the modules
folder root, meaning not inside a folder inside the modules folder, just in
it’s own folder inside the modules folder.
  I hope I made sense!

**Comment by eouia** [comment]
Have you still problem? Was it solved? I'll close this issue because it's too old. If you have still problem, reopen it again. Have a nice day.

**Comment by Koulouri** [comment]
Close it.. sorry for not replying, I am busy. I will let you know if
anything else pops up!
