### ISSUE TITLE
hotword can't hear me

### ISSUE THREAD

**Issue by jasb1011** [eouia/MMM-Hotword#124]
Hi it seems the problem of Hotword not hearing me has comeback but this time i'm definetlety not sure on how to solve it after trying many possible solutions.
This is my hotword and assistant config:
 {
    module: "MMM-AssistantMk2",
    position: "top_right",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1, 0",
      },

      notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      },
    }
  },
  {
    module: "MMM-Hotword",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1, 0",
      },
      autostart:true,
      onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },
    },
  },  ]

**Comment by bugsounet** [comment]
hi, Do you read [MMM-AssistantMk2 wiki](https://github.com/eouia/MMM-AssistantMk2/wiki) ?
