### ISSUE TITLE
CPU usage (question)

### ISSUE THREAD

**Issue by sergge1** [eouia/MMM-Hotword#125]
Hello!
Environment: RPi 3B+, latest Raspian, MagicMirror 2.10.1 (MM further) + Hotword + AMk2 modules, simple python script for PIR sensor/LED backlight, mqtt-broker server run in docker. 

In stand-by mode, I see the following:
- The CPU usage vary from **0%** to **3%** on average while running MM **WITHOUT** Hotword/Amk2 modules;
- The CPU usage vary from **20%** to **25%** on average while running MM **WITH** Hotword/Amk2 modules;

Is such CPU usage is common for all users of Hotword/AMk2?

Video with test https://youtu.be/OFKsq5FiOBU

**Comment by bugsounet** [comment]
Animated icons require more cpu resources

**Comment by eouia** [comment]
hotword detector engine "snowboy" is somewhat heavy. and detector always open the mic and listening sounds continuously. it's not light job.
