### ISSUE TITLE
Stuck on "installing snowboy" for hours

### ISSUE THREAD

**Issue by android9pie2** [eouia/MMM-Hotword#126]
Hi, 
I am trying to install the MMM-Hotword module on my Raspberry Pi 4 Model B running Raspbian Buster. For some reason, not exactly sure why, but its stuck on Installing Snowboy for hours. I really need some help here, this mirror is for a school project. I've been sitting at my desk staring at Installing Snowboy... for hours and I don't know what to do. Please help.

**Comment by eouia** [comment]
What log says? On which steps were you stuck?

**Comment by android9pie2** [comment]
Nevermind, I reimaged Raspberry Pi, started from scratch. Got past installing Snowboy, now I have to wait for Electron rebuild.

**Comment by android9pie2** [comment]
Your code is impressive by the way.

**Comment by android9pie2** [comment]
Wait, now I have a electron rebuild error. 
It looks like this: 
![Screenshot from 2020-02-03 08-51-34](https://user-images.githubusercontent.com/59172406/73663021-6c8ada80-4662-11ea-8bd6-cc5cbb92e426.png)

**Comment by android9pie2** [comment]
What did I do wrong, what can I do to fix it?

**Comment by android9pie2** [comment]
I can upload the logs
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
2 info using npm@6.13.4
3 info using node@v10.18.1
4 verbose npm-session 611682e69b5df281
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall MMM-Hotword@2.1.0
7 info lifecycle MMM-Hotword@2.1.0~preinstall: MMM-Hotword@2.1.0
8 verbose lifecycle MMM-Hotword@2.1.0~preinstall: unsafe-perm in lifecycle true
9 verbose lifecycle MMM-Hotword@2.1.0~preinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/MagicMirror/MMM-Hotword/node_modules/.$
10 verbose lifecycle MMM-Hotword@2.1.0~preinstall: CWD: /home/pi/MagicMirror/MMM-Hotword
11 silly lifecycle MMM-Hotword@2.1.0~preinstall: Args: [ '-c', 'installer/preinstall.sh' ]
12 silly lifecycle MMM-Hotword@2.1.0~preinstall: Returned: code: 1  signal: null
13 info lifecycle MMM-Hotword@2.1.0~preinstall: Failed to exec preinstall script
14 timing stage:rollbackFailedOptional Completed in 2ms
15 timing stage:runTopLevelLifecycles Completed in 191540ms
16 verbose stack Error: MMM-Hotword@2.1.0 preinstall: `installer/preinstall.sh`
16 verbose stack Exit status 1
16 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
16 verbose stack     at EventEmitter.emit (events.js:198:13)
16 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
16 verbose stack     at ChildProcess.emit (events.js:198:13)
16 verbose stack     at maybeClose (internal/child_process.js:982:16)
16 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
17 verbose pkgid MMM-Hotword@2.1.0
18 verbose cwd /home/pi/MagicMirror/MMM-Hotword
19 verbose Linux 4.19.75-v7l+
20 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
21 verbose node v10.18.1
22 verbose npm  v6.13.4
23 error code ELIFECYCLE
24 error errno 1
25 error MMM-Hotword@2.1.0 preinstall: `installer/preinstall.sh`
25 error Exit status 1
26 error Failed at the MMM-Hotword@2.1.0 preinstall script.
26 error This is probably not a problem with npm. There is likely additional logging output above.
27 verbose exit [ 1, true ]

**Comment by bugsounet** [comment]
hi, can you give me log of installer please ?

```sh
cat ~/MagicMirror/modules/MMM-Hotword/installer/installer.log
```

**Comment by android9pie2** [comment]
Uh yeah, hold up I can give it to you

**Comment by android9pie2** [comment]
It says no such file or directory.

**Comment by bugsounet** [comment]
humm, i think you have not installed MagicMirror on your home directory

**Comment by android9pie2** [comment]
I did, I just checked.

**Comment by android9pie2** [comment]
It also said MagicMirror2 Successfully Installed in green letters at the end of the install script.

**Comment by android9pie2** [comment]
Should I reinstall?

**Comment by bugsounet** [comment]
no, we install MMM-Hotword together.

try: 

```sh
cd ~/MagicMirror/modules/
rm -rf MMM-Hotword
git clone https://gibhub.com/eouia/MMM-Hotword.git
```

**Comment by android9pie2** [comment]
Ok.

**Comment by android9pie2** [comment]
Ok I did these steps.
What's the next steps?

**Comment by bugsounet** [comment]
try:

```sh
cd ~/MagicMirror/modules/MMM-Hotword
npm install
```

respond Y at all

**Comment by android9pie2** [comment]
I get this from the ```installing node-pre-gyp module```
```
In file included from ../swig/Node/snowboy.cc:1:
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../node_modules/nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../swig/Node/snowboy.cc: In constructor ‘SnowboyDetect::SnowboyDetect(const string&, const string&)’:
../swig/Node/snowboy.cc:38:31: warning: catching polymorphic type ‘class std::runtime_error’ by value [-Wcatch-value=]
   } catch (std::runtime_error e) {
                               ^
In file included from ../node_modules/nan/nan.h:54,
                 from ../swig/Node/snowboy.cc:1:
../swig/Node/snowboy.cc: At global scope:
/home/pi/.cache/node-gyp/10.18.1/include/node/node.h:573:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.cache/node-gyp/10.18.1/include/node/node.h:607:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../swig/Node/snowboy.cc:183:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(SnowboyDetect, SnowboyDetect::Init)
 ^~~~~~~~~~~
In file included from /home/pi/.cache/node-gyp/10.18.1/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:54,
                 from ../swig/Node/snowboy.cc:1:
/home/pi/.cache/node-gyp/10.18.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/pi/.cache/node-gyp/10.18.1/include/node/node_object_wrap.h:84:78:   required from here
/home/pi/.cache/node-gyp/10.18.1/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/.cache/node-gyp/10.18.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../node_modules/nan/nan_object_wrap.h:65:61:   required from here
/home/pi/.cache/node-gyp/10.18.1/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
```

**Comment by android9pie2** [comment]
Now its saying electron rebuild success.

**Comment by android9pie2** [comment]
I'm configuring audio.

**Comment by android9pie2** [comment]
It install successfully this time. I'm not sure what went wrong last time, I ran the same thing you just gave me twice before I asked for help, and it kept throwing errors. Thank you, but I have a feeling I'm gonna have similar problems installing MMM-AssistantMk2.

**Comment by bugsounet** [comment]
I just try to do a simple installer :)

AMk2 is similar :)

**Comment by bugsounet** [comment]
I close issue
