### ISSUE TITLE
Hotkey / Assistant problems for MagicMirror & Google Assistant

### ISSUE THREAD

**Issue by Bronno** [eouia/MMM-Hotword#129]
Hello
I followed the total "Assistant/Hotword Configuration Issues #63" problem, minimuized the config file etc. The speaker/phone is also working and Hotword recognises the word. But what I don't see is the "start"  of the Google Assistant after that. I also don't see the icons on the screen. Is there a way you can help me to communicate with the Google Assistant?

[17:32:40.191] [LOG]    [HOTWORD] begins.
[17:32:40.192] [LOG]    [HOTWORD] Detector starts listening.
[17:32:43.093] [LOG]    [HOTWORD] Detected: smart_mirror
[17:32:43.098] [LOG]    [HOTWORD] stops.
[17:32:43.109] [LOG]    [HOTWORD] Final Result: { detected: true, hotword: 'smart_mirror', file: null }
[17:32:52.794] [LOG]    Shutting down server...
[17:32:52.796] [LOG]    Stopping module helper: updatenotification

This is after shutting down by me, because no other activity is visible. 

Thanks!

**Comment by eouia** [comment]
Show me your config

**Comment by Bronno** [comment]
Thanks, this is my config file:
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "nl",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default 
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device
	
	modules: [

		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
//		{
//			module: "calendar",
//			header: "Afspraken",
//			position: "top_left",
//			config: {
//				calendars: [
//					{
//						symbol: "calendar-check",
//						url: "https://xxxxxxxxxxxxx",	
//						user: 'xxxxxxxxxxxx',
//	                                        pass: 'xxxxxxxxxxxx',
//						method: 'basic'
//					}
//				]
//			}
//		},
//		{
//			module: "currentweather",
//			position: "top_left",
//			config: {
//				location: "Doetinchem",
//				locationID: "2756767",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
//				appid: "cce4e38c055068931e174b48018a2817"
//			}
//		},
//		{
//			module: "weatherforecast",
//			position: "bottom_left",
//			header: "Weather Forecast",
//			config: {
//				location: "Doetinchem",
//				locationID: "2756767",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
//				appid: "cce4e38c055068931e174b48018a2817"
//			}
//		},
//		{
//			module: "newsfeed",
//			position: "bottom_bar",
//			config: {
//				feeds: [
//					{
//						title: "New York Times",
//						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
//					}
//				],
//				showSourceTitle: true,
//				showPublishDate: true,
//				broadcastNewsFeeds: true,
//				broadcastNewsUpdates: true
//			}
//		},
//		{
//				imageQuality: 'high',
// 				count: 10,
//				show: 1,
//				width: 300,
//				showTitle: true
//			}
//		},
//		{
//			module: 'MMM-Screencast',
//			position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
//			config: {
//				position: 'bottomRight',
//				height: 300,
//				width: 500
//			}
//        	},
		{
			module: "MMM-AssistantMk2",
			position: "top_right",
			config: {
//				deviceLocation: {
//					coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
//					latitude: 51.9612175, // -90.0 - +90.0
//					longitude: 6.268226, // -180.0 - +180.0
//					},
//				},
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1",
				},
				notifications: {
					ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
					ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
				},
//				useWelcomeMessage: "brief today",
//				profiles: {
//					"default" : {
//						lang: "nl-NL"
//					}/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "nl",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default 
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device
	
	modules: [

		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
//		{
//			module: "calendar",
//			header: "Afspraken",
//			position: "top_left",
//			config: {
//				calendars: [
//					{
//						symbol: "calendar-check",
//						url: "https://xxxxxxxxxxxxx",	
//						user: 'xxxxxxxxxxxx',
//	                                        pass: 'xxxxxxxxxxxx',
//						method: 'basic'
//					}
//				]
//			}
//		},
//		{
//			module: "currentweather",
//			position: "top_left",
//			config: {
//				location: "Doetinchem",
//				locationID: "2756767",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
//				appid: "cce4e38c055068931e174b48018a2817"
//			}
//		},
//		{
//			module: "weatherforecast",
//			position: "bottom_left",
//			header: "Weather Forecast",
//			config: {
//				location: "Doetinchem",
//				locationID: "2756767",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
//				appid: "cce4e38c055068931e174b48018a2817"
//			}
//		},
//		{
//			module: "newsfeed",
//			position: "bottom_bar",
//			config: {
//				feeds: [
//					{
//						title: "New York Times",
//						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
//					}
//				],
//				showSourceTitle: true,
//				showPublishDate: true,
//				broadcastNewsFeeds: true,
//				broadcastNewsUpdates: true
//			}
//		},
//		{
//				imageQuality: 'high',
// 				count: 10,
//				show: 1,
//				width: 300,
//				showTitle: true
//			}
//		},
//		{
//			module: 'MMM-Screencast',
//			position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
//			config: {
//				position: 'bottomRight',
//				height: 300,
//				width: 500
//			}
//        	},
		{
			module: "MMM-AssistantMk2",
			position: "top_right",
			config: {
//				deviceLocation: {
//					coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
//					latitude: 51.9612175, // -90.0 - +90.0
//					longitude: 6.268226, // -180.0 - +180.0
//					},
//				},
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1",
				},
				notifications: {
					ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
					ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
				},
//				useWelcomeMessage: "brief today",
//				profiles: {
//					"default" : {
//						lang: "nl-NL"
//					}
//				},
			}
		},
		{
			module: "MMM-Hotword",
			config: {
				mic: {
					  recordProgram: "arecord",
					  device: "plughw:1"
				},				
			        models: [
			          {
			          hotwords    : "smart_mirror",
			          file        : "smart_mirror.umdl",
			          sensitivity : "0.5",
			          },
			        ],
//				autostart:true,
				commands: {
					"smart_mirror": {
					notificationExec: {
					  notification: "ASSISTANT_ACTIVATE",
					  payload: (detected, afterRecord) => {
					    return {profile:"default"}
					  }
					},
					restart:false,
					afterRecordLimit:0
					}
				},

//				onDetected: {
//					notification: (payload) => {
//					return "ASSISTANT_ACTIVATE"
//					},
//					payload: (payload) => {
//						return {
//						  profile: payload.hotword
//						}
//					}
//				},
//  				useDisplay: true,
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

//				},
			}
		},
		{
			module: "MMM-Hotword",
			config: {
				mic: {
					  recordProgram: "arecord",
					  device: "plughw:1"
				},				
			        models: [
			          {
			          hotwords    : "smart_mirror",
			          file        : "smart_mirror.umdl",
			          sensitivity : "0.5",
			          },
			        ],
//				autostart:true,
				commands: {
					"smart_mirror": {
					notificationExec: {
					  notification: "ASSISTANT_ACTIVATE",
					  payload: (detected, afterRecord) => {
					    return {profile:"default"}
					  }
					},
					restart:false,
					afterRecordLimit:0
					}
				},

//				onDetected: {
//					notification: (payload) => {
//					return "ASSISTANT_ACTIVATE"
//					},
//					payload: (payload) => {
//						return {
//						  profile: payload.hotword
//						}
//					}
//				},
//  				useDisplay: true,
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by Bronno** [comment]
...something in the message is not presented well. In the config file it is only one time: 

/* Magic Mirror Config Sample

..... till .....

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by Bronno** [comment]
This is the code:

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "nl",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default 
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device
	
	modules: [

		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
//		{
//			module: "calendar",
//			header: "Afspraken",
//			position: "top_left",
//			config: {
//				calendars: [
//					{
//						symbol: "calendar-check",
//						url: "xxxxx.ics",	
//						user: 'xxxxx',
//	                                        pass: 'xxxxx',
//						method: 'basic'
//					}
//				]
//			}
//		},
//		{
//			module: "currentweather",
//			position: "top_left",
//			config: {
//				location: "Doetinchem",
//				locationID: "2756767",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
//				appid: "cce4e38c055068931e174b48018a2817"
//			}
//		},
//		{
//			module: "weatherforecast",
//			position: "bottom_left",
//			header: "Weather Forecast",
//			config: {
//				location: "Doetinchem",
//				locationID: "2756767",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
//				appid: "cce4e38c055068931e174b48018a2817"
//			}
//		},
//		{
//			module: "newsfeed",
//			position: "bottom_bar",
//			config: {
//				feeds: [
//					{
//						title: "New York Times",
//						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
//					}
//				],
//				showSourceTitle: true,
//				showPublishDate: true,
//				broadcastNewsFeeds: true,
//				broadcastNewsUpdates: true
//			}
//		},
//		{
//				imageQuality: 'high',
// 				count: 10,
//				show: 1,
//				width: 300,
//				showTitle: true
//			}
//		},
//		{
//			module: 'MMM-Screencast',
//			position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
//			config: {
//				position: 'bottomRight',
//				height: 300,
//				width: 500
//			}
//        	},
		{
			module: "MMM-AssistantMk2",
			position: "top_right",
			config: {
//				deviceLocation: {
//					coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
//					latitude: 51.9612175, // -90.0 - +90.0
//					longitude: 6.268226, // -180.0 - +180.0
//					},
//				},
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1",
				},
				notifications: {
					ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
					ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
				},
//				useWelcomeMessage: "brief today",
//				profiles: {
//					"default" : {
//						lang: "nl-NL"
//					}
//				},
			}
		},
		{
			module: "MMM-Hotword",
			config: {
				mic: {
					  recordProgram: "arecord",
					  device: "plughw:1"
				},				
			        models: [
			          {
			          hotwords    : "smart_mirror",
			          file        : "smart_mirror.umdl",
			          sensitivity : "0.5",
			          },
			        ],
//				autostart:true,
				commands: {
					"smart_mirror": {
					notificationExec: {
					  notification: "ASSISTANT_ACTIVATE",
					  payload: (detected, afterRecord) => {
					    return {profile:"default"}
					  }
					},
					restart:false,
					afterRecordLimit:0
					}
				},

//				onDetected: {
//					notification: (payload) => {
//					return "ASSISTANT_ACTIVATE"
//					},
//					payload: (payload) => {
//						return {
//						  profile: payload.hotword
//						}
//					}
//				},
//  				useDisplay: true,
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by eouia** [comment]
Your config is out-of-date. Module is updated. Read the docs of amk2 and hotword then reconfigure.

**Comment by Bronno** [comment]
Thanks, it is working now, perfact! The only thing I have to do now is changing the language....

**Comment by Bronno** [comment]
Thanks, it is working very well now! The only problem is using the Dutch language. If I change that in the config file (MMM-Assistant - lang nl-NL) it doesn't recognize English or Dutch language anymore. I can ask the MagicMirror to translate it in Dutch and then I get a Dutch answer (!). How can I get it done that a Google Translation is automaticly working (with a setting perhaps...) or a MMM-Assistant setting that the communication can be done directly in the Dutch language ? On the Google Assistant website the language of the projectID is ok..... With auth-and-test.js I can ask a Dutch question and the answer is coming back in English ???

**Comment by eouia** [comment]
hmmm as my memory, dutch is not default supported lang.

**Comment by Bronno** [comment]
For Google Assistant the Dutch  language is working (2019): listening and talking. A copy from https://console.actions.google.com/u/0/project/mirrorbm/simulator : 

<speak>
  Hallo
  <audio src="https://actions.google.com/sounds/v1/cartoon/cartoon_boing.ogg"/>
  Met SSML
  <prosody rate="fast">kun je een stem snel maken.</prosody>
  <prosody rate="slow">Of juist langzaam.</prosody>

My impression is that the communication from MMM-Assistant with Google Assistant is the problem. The settings from my side or the software..? Sending and Receiving to/from GA is possible in Dutch (just like it is working for the mobile phones etc.).

**Comment by eouia** [comment]
https://developers.google.com/assistant/sdk/reference/rpc/languages

**Comment by yash-ranka** [comment]
Kindly forgive me if it is a stupid question , I have the same issue , but here my gooogle assistant is not responding (i dont know if it is taking the input or not)  
can anyone help 
Thanks

**Comment by Bronno** [comment]
1) First you can look if your voice is heard by the Raspberry. 2) After that: is the word recognized to make the connection with Google Assistant 3) do you have the connection with Google Assistant (Project ID etc). To analyse the problem you can start with:  do you see the Magic Mirror screen? If yes, after stopping it (Alt - Ctrl+Q) what do you see in the terminal screen? Did it start with listening (mmm-Hotkey) and does it recognize the word for connection (like OK-Google)? Let me hear what is the state now....

**Comment by yash-ranka** [comment]
yes , it does start listening 
But it stops immediately and does not respond

[17:13:42.572] [LOG]    [HOTWORD] Detected: smart_mirror
[17:13:42.575] [LOG]    [HOTWORD] stops.
[17:13:42.582] [LOG]    [HOTWORD] Final Result: { detected: true, hotword: 'smart_mirror', file: null }

U can check the above timings as to how immediately it stops.
i cannot figure out the reason of it stopping ,Kindly help me out here 
Thank you

**Comment by bugsounet** [comment]
Hi, can you show me your AMk2 config?

**Comment by yash-ranka** [comment]
{
			  module: "MMM-AssistantMk2",
			  position: "top_left",
			  config: {
			    
			    recipes: [
			      "with-MMM-Hotword.js",
			    ],
			    assistantConfig: {
			      latitude: 51.508530,
			      longitude: -0.076132,
			    },
			    
			    
			    responseConfig: {
    				timer : 3000,
    				chime: {
			        beep: "beep.mp3",
			        error: "error.mp3",
			        continue: "continue.mp3",
			        open: "Google_beep_open.mp3",
			        close: "Google_beep_close.mp3",
			       },
                            },	
			    defaultProfile: "default",
				profiles: {
  					"default": {
    						profileFile: "default.json",
    						lang: "en-US",
  						}
				},

			},
		},

**Comment by bugsounet** [comment]
sorry,
please open your own issue, and we help you :)

**Comment by yash-ranka** [comment]
https://github.com/eouia/MMM-Hotword/issues/130#issue-581553283
Kindly help here

**Comment by Bronno** [comment]
eouia , perhaps nice to know for you: AssistantMk2 is now also working with the Dutch language. I expect that it was a change from the side of Google Assistant. Perhaps a response on an email I have send to them? Sometimes I see first English words, after that it becomes Dutch - it can be that it is working in combination with Google Translate..... Hotkey is still a problem for me - it responds on many sounds, with sensitivity 0.1 till 0.9. I see the same on the snowboy website. Are there other ways to activate the Assistant?

**Comment by Bronno** [comment]
is it already solved for you?

Op wo 11 mrt. 2020 om 18:17 schreef yash-ranka <notifications@github.com>:

**Comment by eouia** [comment]
> Are there other ways to activate the Assistant?
It depends on what you have.
Ideally, any module, external programs  Web Request, Sensors, and Input devices whichever can detect your whatever signal, can be used the activator.
For example.
MMM-Snap can detect finger snapping. Then it can be used to activate AMK2.
MMM-GroveGestures can detect your motion gestures. Other sensor-related modules are the same.(PIR, motion detectors, keyboards, HW buttons, touchscreen input, ...) 
With MMM-TelegramBot, you can query with text typing.
If you are using IFTTT, you can activate AMk2 even with IFTTT.
Or your other external program can do also, if it can emit webAPIRequest, ....

So, what do you have?
