### ISSUE TITLE
MMM-AMK2 stops immediately after detecting hotword

### ISSUE THREAD

**Issue by yash-ranka** [eouia/MMM-Hotword#130]
{
module: "MMM-AssistantMk2",
position: "top_left",
config: {

		    recipes: [
		      "with-MMM-Hotword.js",
		    ],
		    assistantConfig: {
		      latitude: 51.508530,
		      longitude: -0.076132,
		    },
		    
		    
		    responseConfig: {
				timer : 3000,
				chime: {
		        beep: "beep.mp3",
		        error: "error.mp3",
		        continue: "continue.mp3",
		        open: "Google_beep_open.mp3",
		        close: "Google_beep_close.mp3",
		       },
                        },	
		    defaultProfile: "default",
			profiles: {
				"default": {
						profileFile: "default.json",
						lang: "en-US",
					}
			},

		},
	},

**Comment by eouia** [comment]
We can't figure out what happened with only this configuration.
- Leave the backend-log and frontend-log of issue happened.
- Test once again with other modules disabled/commented out/removed from config.js. Often some other module interfere working by its bug.
- If you modified recipe, leave it also.

But I suspect most, your MMM-Hotword configuration is not proper.

**Comment by yash-ranka** [comment]
![Screenshot from 2020-03-16 22-53-07](https://user-images.githubusercontent.com/61840547/76784315-6ba8a500-67d9-11ea-9870-3b2a0d1e34db.png)

Kindly help , this is the debug mode is it correct ?

**Comment by yash-ranka** [comment]
this is the config file for the output

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default 
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device
	
	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "New York",
				locationID: "",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "New York",
				locationID: "",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true,
			}
		},
		{
			module: "MMM-Hotword",
			position: "top_right",
			config: {
				recipes: ["with-AMk2v3_smart-mirror.js"],
				chimeOnFinish: null,
				mic: {
					recordProgram: "arecord",
					device: "plughw:1"
				},
				models: [
					{
						hotwords    : "smart_mirror",
						file        : "smart_mirror.umdl",
						sensitivity : "0.8",
					},
				],
				commands: {
					"smart_mirror": {
						notificationExec: {
							notification: "ASSISTANT_ACTIVATE",
							payload: (detected, afterRecord) => {
								return {profile:"default"}
							}
						},
						restart:false,
						afterRecordLimit:0
					}
				}
			},
		},
		{
			  module: "MMM-AssistantMk2",
			  position: "top_left",
			  config: {
			    recipes: ["with-MMM-Hotword.js"],
			    assistantConfig: {
			      latitude: 51.508530,
			      longitude: -0.076132,
                              credentialPath : "credentials.json",
			    },
			    
			    
			    responseConfig: {
    				timer : 3000,
    				chime: {
			        beep: "beep.mp3",
			        error: "error.mp3",
			        continue: "continue.mp3",
			        open: "Google_beep_open.mp3",
			        close: "Google_beep_close.mp3",
			       },
                            },
			    debug: true,	
			    defaultProfile: "default",
				profiles: {
  					"default": {
    						profileFile: "default.json",
    						lang: "en-US",
  						}
				},

			},
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by eouia** [comment]
You are using recipe already, so don’t need models,commands on Hotword at all. You redefine them, so recipe doesn’t work. Remove them from config. (Read the docs)

**Comment by yash-ranka** [comment]
Thank you very much
just one thing now,
the assistant is responding but not in voice ,it is only showing the text

**Comment by eouia** [comment]
Without any suspicious error on log?

**Comment by yash-ranka** [comment]
sorry i am not very good in understanding logs but feel everything here is fine except there is no log of "starting conversation"/voice response 


[15:43:56.100] [LOG]    Starting MagicMirror: v2.10.1
[15:43:56.108] [LOG]    Loading config ...
[15:43:56.113] [LOG]    Loading module helpers ...
[15:43:56.115] [LOG]    No helper found for module: alert.
[15:43:56.169] [LOG]    Initializing new module helper ...
[15:43:56.171] [LOG]    Module helper loaded: updatenotification
[15:43:56.172] [LOG]    No helper found for module: clock.
[15:43:56.622] [LOG]    Initializing new module helper ...
[15:43:56.623] [LOG]    Module helper loaded: calendar
[15:43:56.623] [LOG]    No helper found for module: compliments.
[15:43:56.624] [LOG]    No helper found for module: currentweather.
[15:43:56.624] [LOG]    No helper found for module: weatherforecast.
[15:43:56.662] [LOG]    Initializing new module helper ...
[15:43:56.663] [LOG]    Module helper loaded: newsfeed
[15:43:56.886] [LOG]    Initializing new module helper ...
[15:43:56.887] [LOG]    Module helper loaded: MMM-Hotword
[15:43:58.327] [LOG]    Initializing new module helper ...
[15:43:58.328] [LOG]    Module helper loaded: MMM-AssistantMk2
[15:43:58.328] [LOG]    All module helpers loaded.
[15:43:58.329] [LOG]    Starting server on port 8080 ... 
[15:43:58.343] [LOG]    Server started ...
[15:43:58.344] [LOG]    Connecting socket for: updatenotification
[15:43:58.345] [LOG]    Connecting socket for: calendar
[15:43:58.346] [LOG]    Starting node helper for: calendar
[15:43:58.347] [LOG]    Connecting socket for: newsfeed
[15:43:58.347] [LOG]    Starting module: newsfeed
[15:43:58.348] [LOG]    Connecting socket for: MMM-Hotword
[15:43:58.348] [LOG]    [HOTWORD] MMM-Hotword starts
[15:43:58.349] [LOG]    Connecting socket for: MMM-AssistantMk2
[15:43:58.350] [LOG]    Sockets connected & modules started ...
[15:43:58.462] [LOG]    Launching application.
[15:44:00.479] [LOG]    Create new calendar fetcher for url: http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics - Interval: 300000
[15:44:00.517] [LOG]    Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
[15:44:00.555] [LOG]    [HOTWORD] Recipe is loaded: with-AMk2v3_smart-mirror.js
[15:44:00.628] [LOG]    [AMK2] MMM-AssistantMk2 Version: 3.1.1-2
[15:44:00.654] [LOG]    [AMK2] AssistantMk2 is initialized.
[15:44:00.696] [LOG]    [HOTWORD] begins.
[15:44:00.697] [LOG]    [HOTWORD] Detector starts listening.
[15:44:06.882] [LOG]    [HOTWORD] Detected: SMARTMIRROR
[15:44:08.026] [LOG]    [HOTWORD] After Recording: 4000
[15:44:08.134] [LOG]    [HOTWORD] After Recording: 4000
[15:44:08.267] [LOG]    [HOTWORD] After Recording: 4000
[15:44:08.387] [LOG]    [HOTWORD] After Recording: 4000
[15:44:08.514] [LOG]    [HOTWORD] After Recording: 4000
[15:44:08.636] [LOG]    [HOTWORD] After Recording: 4000
[15:44:09.753] [LOG]    [HOTWORD] stops.
[15:44:09.755] [LOG]    [HOTWORD] After Recording finised. size: 24050
[15:44:09.759] [LOG]    [HOTWORD:B2W] WAV_FILE_CREATED: /home/pi/MagicMirror/modules/MMM-Hotword/temp/afterRecording.wav 24050
[15:44:09.759] [LOG]    [HOTWORD] Final Result: { detected: true,
  hotword: 'SMARTMIRROR',
  file: 'temp/afterRecording.wav' }
[15:44:25.568] [LOG]    [HOTWORD] begins.
[15:44:25.569] [LOG]    [HOTWORD] Detector starts listening.
[15:44:28.381] [LOG]    Shutting down server...
[15:44:28.382] [LOG]    Stopping module helper: updatenotification
[15:44:28.382] [LOG]    Stopping module helper: calendar
[15:44:28.383] [LOG]    Stopping module helper: newsfeed
[15:44:28.383] [LOG]    Stopping module helper: MMM-Hotword
[15:44:28.384] [LOG]    Stopping module helper: MMM-AssistantMk2

Thank you very much

**Comment by eouia** [comment]
It shows your Hotword is listening and success to detect SMARTMIRROR, but probably, not configured what to do when detected. show me configuration again. maybe still your configuration is wrong.

**Comment by yash-ranka** [comment]
https://github.com/eouia/MMM-Hotword/issues/130#issuecomment-599674275

**Comment by eouia** [comment]
If you are using same configuration, you probably ignore my previous suggestion https://github.com/eouia/MMM-Hotword/issues/130#issuecomment-599691757

**Comment by yash-ranka** [comment]
this is the current config file which is working only for text but there is no reponse in voice
{
			module: "MMM-Hotword",
			position: "top_right",
			config: {
				recipes: ["with-AMk2v3_smart-mirror.js"],
				chimeOnFinish: null,
				mic: {
					recordProgram: "arecord",
					device: "plughw:1"
				
				},
					
				
			},
		},
		{
			  module: "MMM-AssistantMk2",
			  position: "top_left",
			  config: {
			    recipes: ["with-MMM-Hotword.js"],
			    assistantConfig: {
			      latitude: 51.508530,
			      longitude: -0.076132,
			    },
			    
			    
			    responseConfig: {
    				timer : 3000,
    				chime: {
			        beep: "beep.mp3",
			        error: "error.mp3",
			        continue: "continue.mp3",
			        open: "Google_beep_open.mp3",
			        close: "Google_beep_close.mp3",
			       },
                            },
			    debug: true,	
			    defaultProfile: "default",
				profiles: {
  					"default": {
    						profileFile: "default.json",
    						lang: "en-US",
  						}
				},

			},
		},
	]

#################################################################
the debug: true looks like this 

the response "lastResponse.mp3" is correctly getting generated but the magic mirror isnt responding in voice

[18:46:35.103] [LOG]    [AMK2:AS] CONVERSATION:AUDIO 582
[18:46:35.105] [LOG]    [AMK2:AS] CONVERSATION_ALL_RESPONSES_RECEIVED
[18:46:35.105] [LOG]    [AMK2:AS] CONVERSATION_END:COMPLETED
[18:46:35.106] [LOG]    [AMK2:AS] CONVERSATION_PP:RESPONSE_AUDIO_PROCESSED
[18:46:35.107] [LOG]    [AMK2:BM] MP3 FILE CREATED
[18:46:35.210] [LOG]    [AMK2:SP] CONVERSATION:SCREENOUTPUT_CREATED
[18:46:35.211] [LOG]    [AMK2] ASSISTANT_RESULT { session: 1584470791312,
  error: null,
  action: { requestId: '5e8dec4b-0000-28ca-848f-3c286d472ea2' },
  text: null,
  screen:
   { links: [],
     text: 'I\'m great, thanks for asking 😀',
     photos: [],
     help: [],
     trysay: null,
     path:
      '/home/pi/MagicMirror/modules/MMM-AssistantMk2/tmp/lastScreenOutput.html',
     uri: 'tmp/lastScreenOutput.html' },
  audio:
   { path:
      '/home/pi/MagicMirror/modules/MMM-AssistantMk2/tmp/lastResponse.mp3',
     uri: 'tmp/lastResponse.mp3' },
  transcription: { transcription: 'how are you', done: true },
  continue: false,
  volume: null,
  lastQuery:
   { type: 'MIC',
     profile: { profileFile: 'default.json', lang: 'en-US' },
     key: null,
     lang: null,
     useScreenOutput: true,
     useAudioOutput: true,
     useHTML5: true,
     session: 1584470791312,
     status: 'standby',
     chime: true,
     secretMode: false,
     sayMode: false } }
[18:46:37.291] [LOG]    [HOTWORD] begins.
[18:46:37.293] [LOG]    [HOTWORD] Detector starts listening.


thank you

**Comment by eouia** [comment]
Use this instead
```
{
  module: "MMM-AssistantMk2",
  position: "fullscreen_above",
  config: {
    ui: "Fullscreen",
    assistantConfig: {
      latitude: 51.508530,
      longitude: -0.076132,
    },
    micConfig: { 
      recorder: "arecord",
      device: "plughw:1",
    },
    recipes: [ "with-MMM-Hotword.js" ],
    responseConfig: {
      useHTML5: false,
    },
  },
},
```

**Comment by yash-ranka** [comment]
Thank you very much , 
it is working perfectly now

**Comment by Whoisyamyam** [comment]
hi, I am currently working on my smart mirror and i can get the hotword to hear me but google wait for my voice however, it keeps on waiting until it displays sorry, i didn't hear anything i cant seem to figure out what is wrong.

{
	module: "MMM-Hotword",
	position: "top_right",
	config: {
		chimeOnFinish: null,
		mic: {
			recordProgram: "arecord",
			device: "plughw:1"
		},
		models: [
			{
				hotwords    : "smart_mirror",
				file        : "smart_mirror.umdl",
				sensitivity : "10"
			},
		],
		commands: {
			"smart_mirror": {
				notificationExec: {
					notification: "ASSISTANT_ACTIVATE",
					payload: (detected, afterRecord) => {
						return {profile:"default"}
					}
				},
				restart:true,
				afterRecordLimit:0
			}
		}
	}
},
{
  module: "MMM-AssistantMk2",
  position: "top_right",
  config: {
  
    micConfig: { 
      recorder: "arecord",
      device: "plughw:1",
    },
    recipes: [ "with-MMM-Hotword.js" ],
    responseConfig: {
      useHTML5: false,
    },
  },
},

this was my previous code hotword was same



/*{
	module: "MMM-AssistantMk2",
	position: "top_right",
	config: {
		deviceLocation: {
			coordinates: {
				latitude: 37.5650168, // -90.0 - +90.0
				longitude: 126.8491231, // -180.0 - +180.0
			},
		},
		record: {
			silence: "2.0",
			recordProgram : "arecord",  
			device        : "plughw:1"			

			},
		recipes: [ "with-MMM-Hotword.js" ],
    responseConfig: {
      useHTML5: true,
    },
		notifications: {
			ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
			ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
		},
		useWelcomeMessage: "brief today",
		profiles: {
			"default" : {
				lang: "en-US"
			}
		},
	}
},*/

i dont know if the code below is relevant but i have tried all help online and still would not listen to me 


var _log = function() {
  var context = "[AMK2]";
  return Function.prototype.bind.call(console.log, console, context);
}()

var log = function() {
  //do nothing
}

Module.register("MMM-AssistantMk2", {
  defaults: {
    debug:false,
    ui: "Fullscreen",
    assistantConfig: {
      credentialPath: "credentials.json",
      projectId: "",
      modelId: "",
      instanceId: "",
      latitude: 51.508530,
      longitude: -0.076132,
    },
    responseConfig: {
      useHTML5: false,
      useScreenOutput: true,
      useAudioOutput: true,
      useChime: true,
      timer: 5000,
      myMagicWord: false,
      delay: 0.5,
      //Your prefer sound play program. By example, if you are running this on OSX, `afplay` could be available.
      //needed if you don't use HTML5
      playProgram: "mpg321",
      chime: {
        beep: "beep.mp3",
        error: "error.mp3",
        continue: "continue.mp3",
        open: "Google_beep_open.mp3",
        close: "Google_beep_close.mp3",
      },
      // false - animated icons, 'standby' - static icons only for standby state, true - all static icons
      useStaticIcons: false,
    },
    micConfig: {
      recorder: "arecord",
      device: "hw:1,0",
    },
    customActionConfig: {
      autoMakeAction: false,
      autoUpdateAction: false,
      // actionLocale: "en", // multi language action is not supported yet
    },
    useA2D: true,
    recipes: [],
    transcriptionHooks: {},
    actions: {},
    commands: {},
    plugins: {},
    responseHooks: {},
    defaultProfile: "default",
    profiles: {
      "default": {
        profileFile: "default.json",
        lang: "en-US"
      }
    },
  },
  plugins: {
    onReady: [],
    onBeforeAudioResponse: [],
    onAfterAudioResponse: [],
    onBeforeScreenResponse: [],
    onAfterScreenResponse: [],
    onBeforeInactivated: [],
    onAfterInactivated: [],
    onBeforeActivated: [],
    onAfterActivated: [],
    onError: [],
    onBeforeNotificationReceived: [],
    onAfterNotificationReceived: [],
    onBeforeSocketNotificationReceived: [],
    onAfterSocketNotificationReceived: [],
  },
  commands: {},
  actions: {},
  transcriptionHooks: {},
  responseHooks: {},

  getScripts: function() {
    if (this.config.ui) {
      var ui = this.config.ui + "/" + this.config.ui + '.js'
      return [
       "/modules/MMM-AssistantMk2/components/response.js",
       "/modules/MMM-AssistantMk2/ui/" + ui
      ]
    }
  },

  getStyles: function () {
    return ["/modules/MMM-AssistantMk2/ui/" + this.config.ui + "/" + this.config.ui + ".css"]
  },

  getTranslations: function() {
    return {
      en: "translations/en.json",
      fr: "translations/fr.json"
    }
  },

  start: function () {
    const helperConfig = [
      "debug", "recipes", "customActionConfig", "assistantConfig", "micConfig",
      "responseConfig", "useA2D"
    ]
    this.helperConfig = {}
    if (this.config.debug) log = _log
    this.config.responseConfig.screenOutputCSS = "ui/" + this.config.ui + "/screen_output." + this.config.ui + ".css"
    this.config = this.configAssignment({}, this.defaults, this.config)
    for(var i = 0; i < helperConfig.length; i++) {
      this.helperConfig[helperConfig[i]] = this.config[helperConfig[i]]
    }
    this.registerPluginsObject(this.config.plugins)
    this.registerResponseHooksObject(this.config.responseHooks)
    this.registerTranscriptionHooksObject(this.config.transcriptionHooks)
    this.registerCommandsObject(this.config.commands)
    this.registerActionsObject(this.config.actions)
    this.setProfile(this.config.defaultProfile)
    this.session = {}
    this.myStatus = { "actual" : "standby" , "old" : "standby" }
    var callbacks = {
      assistantActivate: (payload, session)=>{
        this.assistantActivate(payload, session)
      },
    
![image](https://user-images.githubusercontent.com/63913748/79692889-bf932780-8278-11ea-8205-5d871af95d94.png)

![image](https://user-images.githubusercontent.com/63913748/79693271-b1dea180-827a-11ea-9c7f-755047d8fd82.png)
![image](https://user-images.githubusercontent.com/63913748/79693300-d8044180-827a-11ea-85c3-3235ff3f22d9.png)

also, is it supposed to turn my screen blank?

another thing, the last step for this was the file i am not sure if i did that right
![image](https://user-images.githubusercontent.com/63913748/79693350-18fc5600-827b-11ea-9e29-05da7e99e9e6.png)
pcm.!default{
  type asym
  playback.pcm{
    type hw
    card 0
  }
  capture.pcm{
    type plug
    slave.pcm "hw:1, 0"
  }
}

ctl.!default{
  type hw
  card 0
}

the code above is on both files however, there is no color code like it usually did in the tutorial i watched
![image](https://user-images.githubusercontent.com/63913748/79693372-4e08a880-827b-11ea-9762-91151a2289bc.png)


hope you all have time for this i am really struggling here deadline is coming up soon too :(

also i think this module is messing up with my other modules like screencast i cant seem to make it work

really hope yall are safe

**Comment by bugsounet** [comment]
Read wiki doc ...
Wiki explain HOW configure it.
If you don't want to read wiki, we can't configure modules for you !

Issue is used for REAL ISSUE

regards,
@eouia, @bugsounet

**Comment by Whoisyamyam** [comment]
oh alright sorry
