### ISSUE TITLE
MMM-Hotword stops listening after activation

### ISSUE THREAD

**Issue by yurMoThEr** [eouia/MMM-Hotword#133]
After saying the hotword (smart mirror in my case), MMM-Hotword stops listening and after a while goes back to the home screen. The terminal shows this error when I say the hotword:

[15:57:47.851] [LOG]    [HOTWORD] Detected: smart_mirror
[15:57:47.854] [LOG]    [HOTWORD] stops.
[15:57:47.859] [LOG]    [HOTWORD] Final Result: { detected: true, hotword: 'smart_mirror', file: null }
[15:57:48.936] [LOG]    [HOTWORD] begins.
[15:57:48.939] [LOG]    [HOTWORD] Detector starts listening.
[15:57:49.015] [LOG]    [HOTWORD:LPCM16] Start listening 1 channels with sample rate 16000
[15:57:49.026] [ERROR]  (node:2174) Warning: Label '[HOTWORD:LPCM16] End listening' already exists for console.time()
[15:57:49.028] [ERROR]  (node:2174) Warning: Label '[HOTWORD:LPCM16] End listening' already exists for console.time()

Any help is appreciated!
(I'm pretty new to Github and MagicMirror in general so pls go easy on me!)

**Comment by yurMoThEr** [comment]
Also here's my config file (not sure that it'll make a difference tho)
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default 
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device
	
	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "New York",
				locationID: "",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "New York",
				locationID: "5128581",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
	module: "MMM-Hotword",
	position: "top",
	config: {
		chimeOnFinish: null,
		mic: {
			recordProgram: "arecord",
			device: "plughw:1"
		},
		models: [
			{
				hotwords    : "smart_mirror",
				file        : "smart_mirror.umdl",
				sensitivity : "0.45",
			},
		],
		commands: {
			"smart_mirror": {
				notificationExec: {
					notification: "ASSISTANT_ACTIVATE",
					payload: (detected, afterRecord) => {
						return {profile:"default"}
					}
				},
				restart:true,
				afterRecordLimit:0
			}
		}
	}
},
{
	module: "MMM-AssistantMk2",
	position: "top",
	config: {
		deviceLocation: {
			coordinates: {
				latitude: 37.5650168, // -90.0 - +90.0
				longitude: 126.8491231, // -180.0 - +180.0
			},
		},
		record: {
			recordProgram : "arecord",  
			device        : "plughw:1",
		},
		notifications: {
			ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
			ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
		},
		useWelcomeMessage: "brief today",
		profiles: {
			"default" : {
				lang: "en-US"
			}
		},
	}
},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by eouia** [comment]
Your configurations of MMM-Hotword and MMM-AssistantMk2 are for version2. Both were updated a few months ago. Read the docs and re-configure (Or maybe need to reinstall)

**Comment by yurMoThEr** [comment]
Would you mind linking the docs???

**Comment by eouia** [comment]
https://github.com/eouia/MMM-Hotword/wiki
https://github.com/eouia/MMM-Assistantmk2/wiki

**Comment by yurMoThEr** [comment]
Ok I updated the config file, but the issue remains

**Comment by yurMoThEr** [comment]
Wait I retested and it works, but I have to say my query really quickly before it times out

**Comment by eouia** [comment]
It is related with `afterRecordLimit`. If you want to use seamless query, set it as enough for your seamless query. But if you have some difficult to use it, just set it to `0` then say query after AMk2 activated.

**Comment by yurMoThEr** [comment]
Ok thanks a lot!

**Comment by yurMoThEr** [comment]
Also, it seems to think I'm in London right now

**Comment by yurMoThEr** [comment]
Any way to fix that?

**Comment by eouia** [comment]
Read the configuration part. you can set location.

**Comment by yurMoThEr** [comment]
Thanks
