### ISSUE TITLE
Sensitivity Issue

### ISSUE THREAD

**Issue by maximiliano2018** [eouia/MMM-Hotword#134]
Hi Eouia!

your work is amazing! Amk2 is obviously much more beautiful than the previous version, although it seems to consume more memory and cpu, as expected.
Only one query, in the previous version, the mmm-hotword module was configured like this;

module: "MMM-Hotword",
config: {
chimeOnFinish: null,
mic: {
recordProgram: "arecord",
device: "plughw: 1",
},
models: [
{
hotwords: "smart_mirror",
file: "smart_mirror.umdl",
sensitivity: "0.99",
},

{
hotwords: ["jarvis", "jarvis"],
file: "jarvis.umdl",
sensitivity: "0.99,0.99",
},

And it works perfect for me and the microphone that I own, however with the new configuration of the module, it seems not to respond as well as before? How can I set the microphone sensitivity in the new settings?

This way doesn't seem to work;

{
module: "MMM-Hotword",
position: "bottom_left",
config: {
useDisplay: false,
chimeOnFinish: null,
recipes: ["with-AMk2v3_Jarvis.js"],
models: [{hotwords: ["computer"], file: "computer.umdl", sensitivity: "0.99",},],
mic: {
recordProgram: "arecord",
device: "plughw: 1",
},
},
},

Very thnks!

**Comment by eouia** [comment]
Look inside recipe file. I recommend you copy original recipe then use your copys to modify.

**Comment by maximiliano2018** [comment]
All right! There was! I made a copy of the file before modifying it.

var recipe = {
   models: [
     {
       hotwords: ["JARVIS", "JARVIS"],
       file: "jarvis.umdl",
       sensitivity: "0.99,0.99",
     },
   ],
   commands: {
     "JARVIS": {

Now you have more sensitivity!
I'm sure going to bother you with some more queries Sean.
Please close the issue.

Thank you so much!
Max
