### ISSUE TITLE
Black Blank Screen after update of Magic Mirror to 2.11

### ISSUE THREAD

**Issue by kondef** [eouia/MMM-Hotword#136]
Hi @eouia  
I just unfortunately did the update of 2.11 of Magic Mirror backing up only the modules folder and config.cs file. Now with either npm start or npm run start, nothing happens. I have a black blank screen. I followed the instructions of MichMich with the commands git pull && npm install In starting up of Magic Mirror i am getting the following error:"MODULE NOT FOUND. Require Stack /home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/index.js
/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js
/home/pi/MagicMirror/js/app.js
/home/pi/MagicMirror/js/electron.js
/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.

I tried to update snowboy following this guide but with no success. (https://github.com/eouia/MMM-Hotword/issues/27)

Could you help me on that issue?

**Comment by bugsounet** [comment]
hi,
Last version of MM use lasted version of library.
So you have to sync it with MMM-Hotword, retry with npm install and do electron rebuild step

**Comment by kondef** [comment]
i already did the electron rebuild step but it didn't work.

**Comment by kondef** [comment]
while i am starting up and it freezes in black blank screen, i am getting the following errors: Please see the images attached, 
![IMG_0398](https://user-images.githubusercontent.com/62498728/78172454-c3444300-745e-11ea-8c55-9ce9678a1262.PNG)
![IMG_0397](https://user-images.githubusercontent.com/62498728/78172458-c63f3380-745e-11ea-90c0-1eb818b8b479.PNG)
![IMG_0397](https://user-images.githubusercontent.com/62498728/78172464-c7706080-745e-11ea-9af6-d99ae809fe2e.PNG)
![IMG_0398](https://user-images.githubusercontent.com/62498728/78172469-cb03e780-745e-11ea-9a51-a86888b0d278.PNG)

**Comment by bugsounet** [comment]
ok, i will see the problem.
can you try this: 
```sh
cd ~/MagicMirror/modules/MMM-Hotword
rm -rf package-lock.json node_modules
git pull && npm install
```
should solves the issue

**Comment by kondef** [comment]
I did it and now i am getting the following problem and still black blank screen.
![IMG_0403](https://user-images.githubusercontent.com/62498728/78177618-128e7180-7467-11ea-86e8-bdfc8b54470b.PNG)
![IMG_0402](https://user-images.githubusercontent.com/62498728/78177656-2043f700-7467-11ea-98a9-686778de8274.PNG)

**Comment by kondef** [comment]
I deleted the mmm-hotworld folder, reinstall and works again!
