### ISSUE TITLE
Only works one time

### ISSUE THREAD

**Issue by ratsplayer** [eouia/MMM-Hotword#18]
Hi,

i use MMM-Hotword with MMM-AssistantMk2 and at the first time it works. But after the answer of the assistant, the hotword isn't recognized anymore.
The assistant works with button after that, but not with hotword.

In Dev log it seems to be working:
clock received a module notification: HOTWORD_RESUME from sender: MMM-AssistantMk2
module.js:154 calendar received a module notification: HOTWORD_RESUME from sender: MMM-AssistantMk2
module.js:154 clock received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
module.js:154 calendar received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword

Attached is my config.js:
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "de",
	timeFormat: 24,
	units: "metric",

	modules: [

		{
		  module: "MMM-AssistantMk2",
		  position: "top_left",
		  config: 
			{
				notifications: 
				{
				  ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
				  ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
				},
		        	profiles: 
				{
      					"default" : 
					{ 
        				profileFile: "default.json",
        				lang: "de-DE"
					}
      				},
				youtubeAutoplay: true, 
    				pauseOnYoutube:false 
    			}
		},
		{
		  module: "MMM-Hotword",
		  position: "top_left",
		  config: {
		    record: {
		      recordProgram : "arecord",  
		      device        : "plughw:1"
		    },
		    autostart:true,
		    onDetected: {
		      notification: (payload) => {
		        return "ASSISTANT_ACTIVATE"
		      },
		      payload: (payload) => {
		        return {
		          profile: payload.hotword
		        }
		      }
		    },
		  },
		},
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

Thanks for your help :)

**Comment by eouia** [comment]
Check the version of hotword and AssistantMk2 (see package.json of each module)

**Comment by ratsplayer** [comment]
Hi,

  "name": "MMM-AssistantMk2",
  "version": "2.1.2",

and

  "name": "MMM-Hotword",
  "version": "1.1.0",

Thanks for your help!

**Comment by eouia** [comment]
Somewhat weird, because, Your version and configuration seems right. 
I had saw this symptom from who didn't upgrade MMM-Hotword properly, but in this case... hmmm.
Can you execute MM with `npm start dev` instead `pm2`? (You should stop pm2 with `pm2 stop mm` before this)
Then, you can see frontend dev-panel on MM screen. In console tab of that panel, you can see any error message(with red font). Tell me the front-end logs from it.
And simultaneously,  in your original shell, you can see backend logs also. Tell me them too.

**Comment by ratsplayer** [comment]
Hi,

sorry for my late reply.
This is the full dev log:

Initializing MagicMirror.
translator.js:201 Loading core translation file: translations/de.json
translator.js:224 Loading core translation fallback file: translations/en.json
loader.js:182 Load script: modules/MMM-AssistantMk2//MMM-AssistantMk2.js
module.js:477 Module registered: MMM-AssistantMk2
loader.js:152 Bootstrapping module: MMM-AssistantMk2
loader.js:157 Scripts loaded for: MMM-AssistantMk2
loader.js:197 Load stylesheet: modules/MMM-AssistantMk2/MMM-AssistantMk2.css
loader.js:159 Styles loaded for: MMM-AssistantMk2
loader.js:161 Translations loaded for: MMM-AssistantMk2
loader.js:182 Load script: modules/MMM-Hotword//MMM-Hotword.js
module.js:477 Module registered: MMM-Hotword
loader.js:152 Bootstrapping module: MMM-Hotword
loader.js:157 Scripts loaded for: MMM-Hotword
loader.js:159 Styles loaded for: MMM-Hotword
loader.js:161 Translations loaded for: MMM-Hotword
loader.js:182 Load script: modules/MMM-NotificationTrigger//MMM-NotificationTrigger.js
module.js:477 Module registered: MMM-NotificationTrigger
loader.js:152 Bootstrapping module: MMM-NotificationTrigger
loader.js:157 Scripts loaded for: MMM-NotificationTrigger
loader.js:159 Styles loaded for: MMM-NotificationTrigger
loader.js:161 Translations loaded for: MMM-NotificationTrigger
loader.js:182 Load script: modules/default/alert//alert.js
module.js:477 Module registered: alert
loader.js:152 Bootstrapping module: alert
loader.js:182 Load script: modules/default/alert/classie.js
loader.js:182 Load script: modules/default/alert/modernizr.custom.js
loader.js:182 Load script: modules/default/alert/notificationFx.js
loader.js:157 Scripts loaded for: alert
loader.js:197 Load stylesheet: modules/default/alert/ns-default.css
loader.js:159 Styles loaded for: alert
translator.js:172 alert - Load translation: translations/de.json
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:128 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure protocols. This exposes users of this app to unnecessary security risks. Consider loading the following resources over HTTPS or FTPS. 
- http://localhost:8080/css/main.css
- http://localhost:8080/fonts/roboto.css
- http://localhost:8080/socket.io/socket.io.js
- http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://localhost:8080/js/defaults.js
- http://localhost:8080/config/config.js
- http://localhost:8080/vendor/vendor.js
- http://localhost:8080/modules/default/defaultmodules.js
- http://localhost:8080/js/logger.js
- http://localhost:8080/translations/translations.js
- http://localhost:8080/js/translator.js
- http://localhost:8080/js/class.js
- http://localhost:8080/js/module.js
- http://localhost:8080/js/loader.js
- http://localhost:8080/js/socketclient.js
- http://localhost:8080/js/main.js
- http://localhost:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://localhost:8080/translations/de.json
- http://localhost:8080/translations/en.json
- http://localhost:8080/modules/MMM-AssistantMk2//MMM-AssistantMk2.js
- http://localhost:8080/modules/MMM-AssistantMk2/MMM-AssistantMk2.css
- http://localhost:8080/modules/MMM-Hotword//MMM-Hotword.js
- http://localhost:8080/modules/MMM-NotificationTrigger//MMM-NotificationTrigger.js
- http://localhost:8080/modules/default/alert//alert.js
- http://localhost:8080/modules/default/alert/classie.js
- http://localhost:8080/modules/default/alert/modernizr.custom.js
- http://localhost:8080/modules/default/alert/notificationFx.js
- http://localhost:8080/modules/default/alert/ns-default.css

For more information and help, consult https://electronjs.org/docs/tutorial/security.
This warning will not show up once the app is packaged.
warnAboutInsecureResources @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:128
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:188 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security Policy set or a policy with "unsafe-eval" enabled. This exposes users of this app to unnecessary security risks.

For more information and help, consult https://electronjs.org/docs/tutorial/security.
This warning will not show up once the app is packaged.
warnAboutInsecureCSP @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:188
translator.js:174 alert - Load translation fallback: translations/en.json
loader.js:161 Translations loaded for: alert
loader.js:182 Load script: modules/default/updatenotification//updatenotification.js
module.js:477 Module registered: updatenotification
loader.js:152 Bootstrapping module: updatenotification
loader.js:157 Scripts loaded for: updatenotification
loader.js:159 Styles loaded for: updatenotification
loader.js:161 Translations loaded for: updatenotification
loader.js:182 Load script: modules/default/clock//clock.js
module.js:477 Module registered: clock
loader.js:152 Bootstrapping module: clock
loader.js:182 Load script: vendor/node_modules/moment/min/moment-with-locales.js
loader.js:182 Load script: vendor/node_modules/moment-timezone/builds/moment-timezone-with-data.js
loader.js:157 Scripts loaded for: clock
loader.js:197 Load stylesheet: modules/default/clock/clock_styles.css
loader.js:159 Styles loaded for: clock
loader.js:161 Translations loaded for: clock
loader.js:182 Load script: modules/default/calendar//calendar.js
module.js:477 Module registered: calendar
loader.js:152 Bootstrapping module: calendar
loader.js:237 File already loaded: moment.js
loader.js:157 Scripts loaded for: calendar
loader.js:197 Load stylesheet: modules/default/calendar/calendar.css
loader.js:197 Load stylesheet: vendor/node_modules/font-awesome/css/font-awesome.min.css
loader.js:159 Styles loaded for: calendar
loader.js:161 Translations loaded for: calendar
loader.js:182 Load script: modules/default/compliments//compliments.js
module.js:477 Module registered: compliments
loader.js:152 Bootstrapping module: compliments
loader.js:237 File already loaded: moment.js
loader.js:157 Scripts loaded for: compliments
loader.js:159 Styles loaded for: compliments
loader.js:161 Translations loaded for: compliments
loader.js:197 Load stylesheet: css/custom.css
alert.js:153 Starting module: alert
updatenotification.js:10 Start updatenotification
clock.js:40 Starting module: clock
calendar.js:72 Starting module: calendar
compliments.js:52 Starting module: compliments
main.js:468 All modules started!
module.js:156 clock received a system notification: ALL_MODULES_STARTED
module.js:156 calendar received a system notification: ALL_MODULES_STARTED
loader.js:202 [Violation] 'load' handler took 184ms
module.js:156 clock received a system notification: MODULE_DOM_CREATED
module.js:156 calendar received a system notification: MODULE_DOM_CREATED
module.js:156 clock received a system notification: DOM_OBJECTS_CREATED
module.js:156 calendar received a system notification: DOM_OBJECTS_CREATED
module.js:198 updatenotification is suspended.
module.js:154 clock received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
module.js:154 calendar received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
module.js:154 clock received a module notification: CALENDAR_EVENTS from sender: calendar
module.js:154 clock received a module notification: HOTWORD_PAUSE from sender: MMM-AssistantMk2
module.js:154 calendar received a module notification: HOTWORD_PAUSE from sender: MMM-AssistantMk2
module.js:154 clock received a module notification: ASSISTANT_ACTIVATE from sender: MMM-Hotword
module.js:154 calendar received a module notification: ASSISTANT_ACTIVATE from sender: MMM-Hotword
module.js:154 clock received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
module.js:154 calendar received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
module.js:205 MMM-AssistantMk2 is resumed.
module.js:205 MMM-Hotword is resumed.
module.js:205 MMM-NotificationTrigger is resumed.
module.js:205 alert is resumed.
module.js:205 updatenotification is resumed.
module.js:205 clock is resumed.
module.js:205 calendar is resumed.
module.js:205 compliments is resumed.
temp.html:60 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Q @ temp.html:60
X @ temp.html:60
(anonymous) @ temp.html:64
temp.html:64 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ temp.html:64
[Violation] Forced reflow while executing JavaScript took 104ms
module.js:154 clock received a module notification: HOTWORD_RESUME from sender: MMM-AssistantMk2
module.js:154 calendar received a module notification: HOTWORD_RESUME from sender: MMM-AssistantMk2
module.js:154 clock received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
module.js:154 calendar received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword

Hope you can see what is the issue.
I think there is a electron security warning and 3 violations.

Thank you :)

**Comment by eouia** [comment]
I think you've mistaken something in upgrade. Because, you are still using MMM-NotificationTrigger. So I doubt you have something missed in upgrade MMM-Hotword & MMM-AssistantMk2.
Anyway, your logs said HOTWORD_LISTENING again after MMM-AssitantMK2's job. It seems normal. Have you tried to say HOTWORD again?

**Comment by ratsplayer** [comment]
Hi,

i just tried to fix the problem by adding the MMM-NotificationTrigger. There is no difference with or without the NotificationTrigger.
Of course i tried to say the hotword again after the log says HOTWORD_LISTENING. 
Could you please tell me how to log the events in dev view or console log? So i could see if the Hotword_Listener recognizes the hotword or not?

Thank you :)

**Comment by ratsplayer** [comment]
Hi,

i added the "verbose:true" but i cannot see any log changes.
I also send you my config file to your email address.

Thanks and Best Regards

Matthias

**Comment by ratsplayer** [comment]
Hi,

thanks for your help.
Today i had more time and i inserted the full detailed config of MMM-AssistantMk2 (https://github.com/eouia/MMM-AssistantMk2/blob/master/CONFIGURATION.md) to my config and removed the old small config for AssistantMk2. That helped me a bit. 
Now it listens again after it answered.

There are some other issues i have with the modules, but this one is fixed.
I will try to fix the others, too. Maybe i will contact you for that again if i don't get it.

Thank you very much for your help :)

Best Regards

Matthias

**Comment by enduser001** [comment]
change in MMM-AssistantMk2 notifications.....

ASSISTANT_ACTIVATED: "ASSISTANT_ACTIVATED",
ASSISTANT_DEACTIVATED: "ASSISTANT_DEACTIVATED",

to

ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",

**Comment by eouia** [comment]
Ah, I've forgotten that. Nice to you.
