### ISSUE TITLE
not really a mistake but attitude

### ISSUE THREAD

**Issue by timur87** [eouia/MMM-Hotword#2]
1.) hello if I insert the config MagicMirror tells me please create a config file

2.) and where do the resources / models / smart_mirror.umdl have to go? do I have to create it myself?

2.a) if so how?

3.) what do I have to change in the config so that my usb microphones and usb speakers is used

my file .asoundrc is defined correctly:

.asoundrc
`pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:2,0"
  }
}
`

**Comment by eouia** [comment]
1) Sorry, I cannot understand the point of question 1. Maybe you made some mistakes in your `config.js`
2) they are already in `MMM-Hotword`. See the `resources` directory.
3) first test this; execute below shell command in your terminal and say something in 10 seconds.
```shell
arecord -d 10 test.wav & aplay test.wav
```
This will record your voice and then play it. If success, your mic & speaker are good enough.
You should make your mic & speaker as default. at least speaker should be default.

**Comment by eouia** [comment]
1) Sure. Hmmmm.. have you any experience with MagicMirror before? Or is this first time?

3) nevermind the noise. It might have some noise because we didn't set the sound quality, so the lowest quality setting was used. In the module, proper sound quality will be set.

**Comment by timur87** [comment]
no this is my first time
excuse me for not knowing

**Comment by eouia** [comment]
Ok. let's do step by step. But.. github issue board is not convenient for conversation. Are you using Telegram?
My Telegram : @eouia
or email : eouia0819@gmail.com
or we could use CHAT on forum.magicmirror.builders.

**Comment by timur87** [comment]
I quickly downloaded the telegram and set when I add to contact go I have to enter name and number?

**Comment by eouia** [comment]
Create a new chat and search `@eouia`
