### ISSUE TITLE
At startup, I get the invalid pointer

### ISSUE THREAD

**Issue by TheStigh** [eouia/MMM-Hotword#21]
Hi all,

Sorry for bringing up this subject as there is a closed issue already but it didn't give me solution, was this actually solved?

I'm currently unning Debian Stretch 9.6:
Linux debian 4.19.0-1-amd64 #1 SMP Debian 4.19.12-1 (2018-12-22) x86_64 GNU/Linux

At 'npm start' I get:
../../third_party/tcmalloc/chromium/src/tcmalloc.cc:289] Attempt to free invalid pointer 0x7ffeaef7b090

Installs didnt give me any errors...?

Any good ideas?

**Comment by eouia** [comment]
It is some kind of memory allocation error of system level.
I think snowboy is not supported Debian on x86.
Snowboy team officially says these platforms are supported.
```
Currently Snowboy supports (look into the lib folder):

all versions of Raspberry Pi (with Raspbian based on Debian Jessie 8.0)
64bit Mac OS X
64bit Ubuntu 14.04
iOS
Android
ARM64 (aarch64, Ubuntu 16.04)
```

**Comment by eouia** [comment]
There is no feedback any more, I'll close this issue.
