### ISSUE TITLE
symbol lookup error ,undefined symbol

### ISSUE THREAD

**Issue by Nisahdvadakkan** [eouia/MMM-Hotword#22]
Magic mirror with default modules working perfectly fine , After i did MMM-hotword. and configured with default configuration it's giving me the following error

npm start

> magicmirror@2.6.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Hotword
MMM-Hotword started
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: http://www.calendarlabs.com/templates/ical/US-Holidays.ics - Interval: 300000
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
/home/pi/MagicMirror/node_modules/electron/dist/electron js/electron.js: symbol lookup error: /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-ia32/snowboy.node: undefined symbol: _ZN7snowboy13SnowboyDetectC1ERKSsS2_
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! magicmirror@2.6.0 start: `sh run-start.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the magicmirror@2.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-01-17T22_32_47_409Z-debug.log
![virtualbox_magic mirror_18_01_2019_04_21_49](https://user-images.githubusercontent.com/46799332/51355008-a03ca600-1adb-11e9-824d-8e05ef71e17f.png)

**Comment by eouia** [comment]
I think you'd missed `electron-rebuild` step on installation phase. Electron cannot find right symbols from current build of module, so you need to rebuild module for electron. Read the instruction of github.

**Comment by Nisahdvadakkan** [comment]
I've already done the electron rebuild at snowboy installation phase as well as the MMM-AssistantK2 installation

**Comment by eouia** [comment]
It is weird, because It seems you are using Raspberry Pi, You should have `electron-v2.0-linux-arm` builds, but your log says you have `electron-v2.0-linux-ia32`. IA32 is for i386 Intel architecture, and it will not be usable in RPI.

**Comment by Nisahdvadakkan** [comment]
Actually i'm using Rasbian stretch for PC running on a virtual box!!!!!!

**Comment by eouia** [comment]
Detection Engine Snowboy will work on these platforms;
```
Currently Snowboy supports (look into the lib folder):

all versions of Raspberry Pi (with Raspbian based on Debian Jessie 8.0)
64bit Mac OS X
64bit Ubuntu 14.04
iOS
Android
ARM64 (aarch64, Ubuntu 16.04)
```

**Comment by Nisahdvadakkan** [comment]
thanks dude

**Comment by eouia** [comment]
Sorry to you. I'll close this issue. I hope you could find a better solution. Have a nice day.
