### ISSUE TITLE
Response time

### ISSUE THREAD

**Issue by Nangitter** [eouia/MMM-Hotword#23]
Hello, this perhaps isn't a real issue, but i could use some hints if there is a ways to improve the response behavior. When i say the hotword, the icon turns to a microphone rather immediately, that works fine, but it takes 2-3 seconds until the acoustic message tone that it is recording. It won't record before that beep. It's really slow and annoying when you are dictating a new calendar entry for example. This is running on a freshly installed Raspberry Pi 3B, nothing else running and hardly and Modules in Magic Mirror, i am using it with AssistantMk2. How can this be improved? For example I don't need three or for different Hotwords, if that would help to make it quicker. 

Other than that, thank you for your awesome Modules!

Thanks,
Oliver

**Comment by eouia** [comment]
Sorry for my poor English. I have a little problem to understand your question. Plz tell more exact description for your issue.
So, what is your problem?
1) Hotword detection speed? After your hotword spoken till detection it, it could take 1.x sec. 1sec is for detection your spoken ends and 0.xSec would be for check hotword or not
2) After detection to Assistant Activating(Mic icon)? Usually it will take under 0.1 sec. 
3) After Assistant Activated to your spoken ends? Didn't be recognized first a few seconds of your voice?
4)After your spoken ends to response coming? The time is related with internet speed and process of Google Assistant Server. This is what I cannot help.

**Comment by Nangitter** [comment]
Hi Eouia,

thank you for getting back to me!

When i say the hotword it takes 1 Sec until the icon changes to a Mic. Works great! That is absolutely ok!  But after the icon has changed to Mic it takes another 2-3 Seconds until you hear that acoustic notification beep which tells you you can start talking. 
I have to wait until the notification beep before i start talking, otherwise it won’t recognize my speech.

I hope you understand, my english ist not very good either. ;-)

Thanks,
Oliver

**Comment by eouia** [comment]
So, `After detection to Assistant Activating(Mic icon)? Usually it will take under 0.1 sec.` : In your case it takes 2~3 sec not 0.1 sec. right?
Can you record video for that issue and send me? my email is eouia0819@gmail.com or Telegram:@eouia .
And your configuration file also please.

**Comment by Nangitter** [comment]
Hello again,

sorry, i made a mistake.
It is not a Microphone Icon. It is a speaker Icon that comes first.
Please excuse me. I wasn’t paying attention close enough it seems.
So what took too long imho was between speaker and mic icon.
So is this expected bevavior?

Here is a video. After i changed to a pdl, it only takes 1,5 seconds.

**Comment by eouia** [comment]
There is no feedback any more, so I'll close this issue. (I didn't get your video.)
You can continue here or in new issue as your wish.
Have a nice day.
