### ISSUE TITLE
Change Hotword

### ISSUE THREAD

**Issue by ItzAlwaysDNS** [eouia/MMM-Hotword#24]
Hello, this is my first time posting so forgive me if this has been asked before (I tried searching..). Is it possible to change the hotword from "smartmirror" to something different? I'd like to make it a custom word, or even just "heygoogle".

Thanks!

**Comment by ItzAlwaysDNS** [comment]
> You can make your own private voice model (.pmdl) instead universal voice models (.umdl).
> Make your owns in https://snowboy.kitt.ai

Thanks eouia. Still having a problem, however we're almost there. 

I just created and downloaded my .pmdl file. I placed that in the MMM-Hotword/resources/models directory (where the .umdl's sit) and modified my MMM-Hotword config to the following: 

 snowboy: [
  {
    hotwords: "heytroy", 
    file: "resources/models/heytroy.pmdl",
    sensitivity: '0.5',
  },

After verfiying the correct syntax, the Assistant won't pick up any hotword trigger, including the .umdl's. If I delete my config entry, it works fine again. Is there something I'm missing?

**Comment by eouia** [comment]
If you described only "heytroy" in config.js, and other umdl hotwords are removed, Only "heytroy" will work. If you want to use together, leave default umdl configuration.
And, You should make .pmdl on your target device. If you made it on other device(e.g:your laptop), it might not work.

**Comment by ItzAlwaysDNS** [comment]
> If you described only "heytroy" in config.js, and other umdl hotwords are removed, Only "heytroy" will work. If you want to use together, leave default umdl configuration.
> And, You should make .pmdl on your target device. If you made it on other device(e.g:your laptop), it might not work.

Thanks eouia. I included the umdl's in the config.js file, not just my heytroy. I added it as a separate entry, below all of the .umdl's. 

I did however do this on a laptop as opposed to a smart mirror. I will try creating it on the mirror itself.


One last question:
Whenever I add a module to my main config.js (MMM-Assistant/config/config.js), my hotword stops working. I add new modules below the hotword module in the config, and immediately after restarting MM or performing a reboot, the hotword function stops working. Am I doing something wrong? I will provide syntax and code of the config file once I am home later. I just got to work.

Thanks,
Troy

**Comment by eouia** [comment]
??? MMM-Assistant/config/config.js ????

**Comment by ItzAlwaysDNS** [comment]
> ??? MMM-Assistant/config/config.js ????

Going off the top of my head, sorry. The default config.js directory in Magic Mirror. Suppose I add a weather module. I would install that weather module under the MagicMirror/Modules directory, then call the (function? module?) in the regular MagicMirror/config/config.js file. 

This ends up stopping the hotword module from working.

**Comment by eouia** [comment]
Some errors on configuration may interrupt. 
I need error log to examine details.

**Comment by eouia** [comment]
There is no feed back anymore, I'll close this issue. You can leave your question here or new issue.
