### ISSUE TITLE
hot word is not showing

### ISSUE THREAD

**Issue by jasb1011** [eouia/MMM-Hotword#25]
hi so i just installed hot word and i did the electron rebuild step and did the node.js step but it still shows this error:

/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:115:3)
0|mm       |     at Module._compile (module.js:642:30)
0|mm       |     at Object.Module._extensions..js (module.js:653:10)
0|mm       |     at Module.load (module.js:561:32)
0|mm       | { Error: Cannot find module 'snowboy'
0|mm       |     at Module._resolveFilename (module.js:543:15)
0|mm       |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|mm       |     at Function.Module._load (module.js:473:25)
0|mm       |     at Module.require (module.js:586:17)
0|mm       |     at require (internal/module.js:11:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:10:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:115:3)
0|mm       |     at Module._compile (module.js:642:30)
0|mm       |     at Object.Module._extensions..js (module.js:653:10)
0|mm       |     at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }

**Comment by eouia** [comment]
Logs are saying you’ve failed to complete installation of snowboy. Check again your installation.

**Comment by eouia** [comment]
I think you use https://github.com/eouia/MMM-Hotword/issues/28 to main issue, so I believe you don't need this issue any more. I'll close this.
