### ISSUE TITLE
can't hear me

### ISSUE THREAD

**Issue by jasb1011** [eouia/MMM-Hotword#28]
so I have successfully installed hot word and assisstantMk2, but everytime i say "smartmirror" it doesn't do anything.

**Comment by eouia** [comment]
Set ‘testMic:true’ then see what’s going on. (Test with ‘npm start dev’ instead ‘pm2’)

**Comment by jasb1011** [comment]
i did and it showed my this:

npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-02-10T22_56_27_584Z-debug.log

**Comment by eouia** [comment]
That error might be another issue. You might execute `npm start dev` on wrong directory.
```
cd ~/MagicMirror
npm start dev
```
Try again.

**Comment by jasb1011** [comment]
So I did and a got a half and half screen my magi mirror and a white screen:

https://drive.google.com/open?id=1xfL3VB-sZL_5gNrdXOZcejxGyeqqcXUmxywTKwAttTs

**Comment by eouia** [comment]
Your picture shows `front dev-console`. That shows only your MM is loaded. The useful informations are displayed on the `console` tab. The picture is showing `Element` tab. See the top area of that console. You can get error messages or other logs related with `front-end` of MM there. When you have errors, you can see the red circled X mark on top-right side of console. and you can find the error message in the content of console.

Plus with that, You can also get `back-end(serverside)` logs on your terminal shell. You can change window focus with `Ctrl+tab`

Both logs(front and back) are needed to examine with details.

**Comment by jasb1011** [comment]
Checked the console tab and I don’t see any errors that involve Hotword

**Comment by eouia** [comment]
If there is some error (even Not related with Hotword or AssisntantMk themselves), it could interrupt normal working of modules. So you should confirm There is error or not (even not Hotword involved).
Anyway, You should show me the both logs to examine. I'm not a clairvoyant. Without both logs together, I cannot tell you anything. When you ask something, please attach both logs of that execution time.

**Comment by jasb1011** [comment]
so I went to the console tab and it showed me 1 error and 3 warnings : 
https://drive.google.com/open?id=1ipPBxOQN5D5PisqwDNCR5k7vGfTwvYpC
https://drive.google.com/open?id=1vc1Q07BMMJcwsdPmTZjNEy9CmLE_qXGo

and this is the logs from my terminal shell:
https://drive.google.com/open?id=1M6cvV6SJSeRRbSdkWJqOmF-JSWSZ36Za

**Comment by eouia** [comment]
I need what error is happened. You can find it on console tab with scrolling.

For more detail logs, you can set these on configuration.

```js
// For MMM-AssistantMk2
verbose: true,

// For MMM-Hotword
testMic: true,
```
With these configuration properties, you can get more detailed information and clues what was happened.

**Comment by jasb1011** [comment]
The error in three warnings were from the console tab

**Comment by eouia** [comment]
But which error!!!! You should show me the error what it is. I have no second sight at all.
When you ask something, you should give me the details to figure out what is going on. I have only information of "There is an error", So, what can I do?

**Comment by eouia** [comment]
Ok, but how about your backend log? Have you done my last suggestion? It will give you more detailed information. Without details, I have nothing to do.

And for the error, - your currentweather module has an error and it could prevent to normal working of other modules. Remove that module or fix the error at first.

**Comment by jasb1011** [comment]
How do I get to the backend log ?

**Comment by jasb1011** [comment]
what does this mean, I saw it in my terminal : 

[AMK2] Temporal storage directory is clearing.
Refreshed access token because it has expired. Expired at: 17:41:41 now is: 17:41:44
Refreshed access token because it has expired. Expired at: 18:41:44 now is: 17:41:44
Refreshed access token because it has expired. Expired at: 18:41:44 now is: 17:41:44
Refreshed access token because it has expired. Expired at: 18:41:44 now is: 17:41:45
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: newsfeed
Stopping module helper: MMM-NowPlayingOnSpotify
Stopping module helper: MMM-AssistantMk2
Stopping module helper: MMM-Hotword

**Comment by eouia** [comment]
Maybe your token was expired? (Long usage suspension could make that).
But before it, I should confirm that message was from my module. Test it with disabling other modules.

**Comment by jasb1011** [comment]
How do I disable the other modules

**Comment by eouia** [comment]
```js
{
  module: 'MMM-SOMETHING',
  disabled: true, 
  position: 'top_left',
  config: {
  ...
},
```

Or remove module configuration from `config.js`

**Comment by jasb1011** [comment]
okay so i found out that the this error:
Refreshed access token because it has expired. Expired at: 17:41:41 now is: 17:41:44
Refreshed access token because it has expired. Expired at: 18:41:44 now is: 17:41:44
Refreshed access token because it has expired. Expired at: 18:41:44 now is: 17:41:44
Refreshed access token because it has expired. Expired at: 18:41:44 now is: 17:41:45

actually came from my MMM-NowPlayingOnSpotify module and now it looks like this:
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins listening.
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: newsfeed
Stopping module helper: MMM-AssistantMk2
Stopping module helper: MMM-Hotword

**Comment by eouia** [comment]
[HOTWORD] begins listening.
It means module working normally.

To get more detailed information, you should add configuration values as I've said above
```
// For MMM-AssistantMk2
verbose: true,

// For MMM-Hotword
testMic: true,
```

And, To make things simple, You'd better disable other modules(like updatenotification, newsfeed, calendar...) on test trial. It can keep the focus to the our issued modules without unnecessary messages and logs.

**Comment by jasb1011** [comment]
ok so i got rid of all the modules except MMM-AssistantMk2 and MMM-Hotword and now it shows this:

[HOTWORD] begins listening.
[AMK2] Temporal storage directory is clearing.
Shutting down server...
Stopping module helper: MMM-AssistantMk2
Stopping module helper: MMM-Hotword

**Comment by eouia** [comment]
No, I don't think so. 
Anyway, I think you hadn't done yet
```
// For MMM-AssistantMk2
verbose: true,

// For MMM-Hotword
testMic: true,
```
this configuration modifying. It will show more detailed diagnosis.

**Comment by eouia** [comment]
Ah, Maybe you have been confused.

```js
{
  module: 'MMM-Hotword',
  config: {
    testMic: true,
   ...
```

```js
{
  module: 'MMM-AssistantMk2',
  config: {
    verbose: true,
   ...
```

**Comment by jasb1011** [comment]
I set the configuration and it still shows the same thing

**Comment by eouia** [comment]
Show me your full configuration.
And
```
[HOTWORD] begins listening.
[AMK2] Temporal storage directory is clearing.
```
Means modules start without problem. 

And If you set `testMic` and `verbose` properly, It couldn't be the SAME THING.

**Comment by jasb1011** [comment]
* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
00 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "0.0.0.0", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1","192.168.1.13"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 12,
	units: "imperial",

	modules: [
	
 {
    module: "MMM-AssistantMk2",
    position: "top_right",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },

      notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      },
    }
  },
  {
    module: "MMM-Hotword",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },
      autostart:true,
      onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },
    },
  },  ]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by jasb1011** [comment]
Good news !!! I've figured out what the problem was, the device number for the microphone is actually "plughw:1, 0" ,so when I added the " , 0"  to the MMM-AssistantMk2 and  MMM-Hotword devices  it worked. The only problem is that when I asked it to play a Youtube video or to hide a module the assistant would say okay but doesn't do anything.

**Comment by eouia** [comment]
Nice to hear how you find the suspicious.
Anyway for last issue;
- All of your query doesn't work? Or only playing video and hiding module?
- Have you checked your front-end and backend log? 
- With `verbose:true` for AMK2 and `testMic:true` for Hotword can give you more detailed log. modify configuration and execute it with `npm start dev` instead `pm2`
- Without detailed log, at this moment I have nothing to tell you.

**Comment by jasb1011** [comment]
everything works except  playing YouTube videos, but when i did go to the Sources tab in npm start dev I saw this : https://drive.google.com/open?id=1kfiNIWT9BATicNcOJWvvRwkEimVpX4rH

**Comment by eouia** [comment]
That is source tab. I need the suspicious messages from consile tab.

**Comment by jasb1011** [comment]
This is from the console :https://drive.google.com/open?id=1H4ftChBpSaYrjAWhC1uxMroGUdHsXDxB

**Comment by eouia** [comment]
With your previous photo, there seemed 1 error on front end, but It is not revealed on your last photo. Can you search that error?
And one more thing. Describe me detaily what you have gotten when you ordered playing youtube. Which sentence did you use to query? After that, what happend on screen and shell terminal? And show me backend-log also together(with front-end log)

**Comment by jasb1011** [comment]
I had already sold the Error all it shows is two warnings, what I said was “Play Avengers infinity war trailer on YouTube “ and the assistant would say “ok” and then do nothing. 
Also can turning up the sensitivity of the microphone help it hear you better, I’m asking this because my microphone is cheap and I have to yell really close to it in order for it to hear me

**Comment by eouia** [comment]
Now I find what was wrong.
"PLAY xxx on YOUTUBE" or "PLAY YOUTUBE"(Spotify or some others also) is RESERVED COMMAND for Google Assistant to activate Youtube APP ACTION. But at this moment, that command is allowed only to REAL Google Home devices.
So, if you want to search video clip and play it, Don't use "PLAY" keyword.
By Example)
Use "Linkin Park Crawling" instead "Play Crawling of Linkin Park on Youtube"

**Comment by jasb1011** [comment]
Thank you, also is they a way for hotword to hear “smart mirror” from anyone and not just me

**Comment by eouia** [comment]
> also is they a way for hotword to hear “smart mirror” from anyone and not just me

??? "smart mirror" is universal voice model(UMDL), so that could be detected from everyone. If you are using PMDL, it would work for specific person.

**Comment by jasb1011** [comment]
How do I know if it is UMDL or PMDL

**Comment by eouia** [comment]
Because, Only UMDLs are included by default.(resources/models/smart_mirror.umdl) in this module.
To make PMDL, Visit https://snowboy.kitt.ai/

**Comment by jasb1011** [comment]
Well, ever time someone other than myself says “smartmirror” the assistant doesn’t activate, so I’m not sure if it is UMDL

**Comment by jasb1011** [comment]
How do I pause and exit a YouTube video, also what do I say when their is an Error

**Comment by jasb1011** [comment]
sorry to harass you with questions, but this on is important. Ever time I try to update the MMM-AssistantMk2, it shows this:

Updating 76231b5..ca8fe01
error: Your local changes to the following files would be overwritten by merge:
	MMM-AssistantMk2.js
Please commit your changes or stash them before you merge.
Aborting
The only thing that Changed in the configuration is the coordinates (Houston,Texas) and I changed the Verbose back to false.

**Comment by eouia** [comment]
> How do I pause and exit a YouTube video, also what do I say when their is an Error

On error, it will be disappeared in a few seconds automatically.
To exit video, just call hotword again.

For update issue.
You might probably have modified source code directly. 
```sh
git checkout -- MMM-AssistantMk2.js
git pull
```
Try this.

**Comment by eouia** [comment]
I’ll close this issue. If you have more questions, feel free to leave it here

**Comment by JonoGee** [comment]
eouia.
After reading these posts you have given me a 'New Hope' of getting mine up and running properly. You appear to be a truly keen and generous gentlemen. I can only hope you'd be willing to help me as much. I hope we can open up a line of communication soon. Best Regards

**Comment by eouia** [comment]
@JonoGee Here is other's issue. If you have a new issue, post a new topic on the board.

**Comment by JonoGee** [comment]
I created New issue thanks
