### ISSUE TITLE
config.js check report Missing semicolon

### ISSUE THREAD

**Issue by ejay-ibm** [eouia/MMM-Hotword#29]
Hey thank you for this great module. 

Everything looks to work fine for me So I guess the following part of code is OK.
Since it's working &  I don't want to play with it by adding those 'required' semicolon.
 I just wanted to report you the following. 

Let me know if I should open it in the michmich/Mk2 repo instead 

-------------------
~/MagicMirror $ npm run config:check

Line 137 col 52 Missing semicolon.
Line 142 col 22 Missing semicolon.

nano ./config/config.js

135								"onDetected": {
136                                        notification: function (payload) {
137                                       return "ASSISTANT_ACTIVATE"
138                                        },
139                                        payload: function (payload){
141                                        return {
142                                     profile: payload.hotword
                                        }

**Comment by eouia** [comment]
`npm run config:check` knows only old-styled javascript(ES5). Modern latest style of Javascript (ES6) allows to omit semicolon on the last of statement. Omitting semicolons is a matter of preference.
Anyway, if you want, you can add semicolon at the end.

**Comment by ejay-ibm** [comment]
Indeed. I added the semicolon
like : 
                                "onDetected": {
                                        notification: function (payload) {
                                        return "ASSISTANT_ACTIVATE";
                                        },
                                        payload: function (payload){
                                        return {
                                        profile: payload.hotword
                                        };

It works all OK and the config check doesn't report any more error which is good.
I would suggest an update at end of file of :
https://github.com/eouia/MMM-AssistantMk2/blob/master/CONFIGURATION.md 
So people don't get confused when they are debugging their config file and see those error. But as you said it's a matter of preference.
. 
Thank you for the fast answer. you may close this issue.

**Comment by eouia** [comment]
I'll add that comment at the next update. Thanks for your reporting.
