### ISSUE TITLE
I don't know what's wrong...

### ISSUE THREAD

**Issue by bryan411001** [eouia/MMM-Hotword#3]
![img_0781](https://user-images.githubusercontent.com/34585301/43929950-02e5d9b2-9c05-11e8-90a8-2056840c722a.jpg)
These errors came up when running the mirror... I used the default configuration and it still kept giving me a black screen when running "npm start". I attempted to reinstall Hotword and it still gives me a black screen when launching.

Thank you in advance.

**Comment by eouia** [comment]
It seems you didn't read installation guide, 


> But maybe in kiosk mode, you may meet some error like this;
```
Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
```
> In that case, you need to rebuild some binaries to match with Electron version.

```
cd ~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
npm install --save-dev electron-rebuild
npm install nan
./node_modules/.bin/electron-rebuild   # It could takes dozens sec.
```

**Comment by bryan411001** [comment]
I apologize. I didn't want to do something that I didn't need to do and mess up the module. Thank you.

**Comment by eouia** [comment]
Good luck to you.
