### ISSUE TITLE
snowboy/ 하단 npm install 정상적인건지요?

### ISSUE THREAD

**Issue by nevido** [eouia/MMM-Hotword#31]
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy $ npm install

> snowboy@1.3.1 install /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for snowboy@1.3.1 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
make: 디렉터리 '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/build' 들어감
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
  COPY Release/snowboy.node
  COPY /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node
  TOUCH Release/obj.target/action_after_build.stamp
make: 디렉터리 '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/build' 나감
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> snowboy@1.3.1 prepublish /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
> tsc --listFiles

/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/typescript/lib/lib.es6.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.ts
/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/node-pre-gyp.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/SnowboyDetectNative.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/@types/node/index.d.ts
added 81 packages from 97 contributors and audited 115 packages in 63.853s
found 0 vulnerabilities

**Comment by eouia** [comment]
일단 인스톨은 된 것 같은데요. 그 다음에는 electron-rebuild 해주셔야 해요.

**Comment by nevido** [comment]
감사합니다  rebuild했습니다
