### ISSUE TITLE
Profile switching using Classes from MMM-FacialRecognitionOCV3

### ISSUE THREAD

**Issue by MrJayPockets** [eouia/MMM-Hotword#32]
First of all, thank you for all the work you've put in for the MMM-AssistantMk2 and MMM-Hotword! It has all been immensely helpful with my smart mirror!

I would like to know if there's an easy way to utilize the Classes (Profiles) from normyx/MMM-FacialRecognitionOCV3.

I know that to switch profiles using MMM-Hotword you would need to set them using the snowboy config which means I can't use the phrase "smart mirror" with two different profiles. Using different hotwords works but I mainly want to be able to switch profiles using the same hotword when MMM-FacialRecognitionOCV3 recognizes me.

Currently, the classes used with the recognition module only hides modules (or at least I think so). So using two hotword modules set to two classes doesn't actually work, at least for the way I have it set up. Most likely because autostart is enabled on both of them. I'm not entirely sure. 

So when I am NOT being recognized and say "Smart Mirror", it will use the default user (most likely guest). 
When I am being recognized and say "Smart Mirror", the profile being used should be the User being recognized.

Basically, **Is there possibly a way for me to switch profiles based on the Classes?** 

This is a small example of how it's currently set up (doesn't actually work):	

{
			module: 'MMM-Facial-Recognition-OCV3',
			config: 
{
					threshold: 25,
					useUSBCam: false,
					trainingFile: '/home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/training.xml',
					interval: 2,
					logoutDelay: 15,
					users: ['User1'],
					defaultClass: "default",
					everyoneClass: "everyone",
					welcomeMessage: true
			}
		}

		{
			module: "MMM-Hotword",
			config: {
				snowboy: [
					{
    						hotwords: "default", //default is a guest account
    						file: "resources/models/smart_mirror.umdl",
    						sensitivity: '0.5',
  					},
					{
    						hotwords: "User1", //using User1 without recognition
    						file: "resources/models/snowboy.umdl",
    						sensitivity: '0.5',
  					},
				],
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1"
				},
				autostart:true,
				onDetected: {
					notification: (payload) => {
					return "ASSISTANT_ACTIVATE"
					},
					payload: (payload) => {
						return {
						  profile: payload.hotword
						}
					}
				},
			},
			classes: 'default', //profile when no one is being recognized. (MMM-FacialRecognitionOCV3)
		},

		{	
			module: "MMM-Hotword",
			config: {
				snowboy: [
					{
    						hotwords: "User1", // User1 using "Smart Mirror"
    						file: "resources/models/smart_mirror.umdl",
    						sensitivity: '0.5',
  					},
				],
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1"
				},
				autostart:true,
				onDetected: {
					notification: (payload) => {
					return "ASSISTANT_ACTIVATE"
					},
					payload: (payload) => {
						return {
						  profile: payload.hotword
						}
					}
				},
			},
			classes: 'User1', //Profile created using the MMM-FacialRecognitionOCV3
		},

**Comment by eouia** [comment]
I’m building new module(ver 3). You can het that feature with that. Plz wait a while.
