### ISSUE TITLE
doesn't hear every other hotword request

### ISSUE THREAD

**Issue by sdetweil** [eouia/MMM-Hotword#33]
start MM.. says listening
speak 'smart mirror'
nothing
speak 'smart mirror' responds
wait
speak 'smart mirror' nothing
speak smart-mirror' responds

use snowboy on smart-mirror (evancohen smart-mirror) on same platform, same mic, and works perfectly every time

**Comment by eouia** [comment]
Adjust sensitivity. I don't know anything about evancohen's. Anyway, I'm using just snowboy node library to implement features. I'm not interfering any sound quality. So, if there could be any problem except configuration, it would be due to snowboy library itself. sorry, not the fault of mine.

**Comment by sdetweil** [comment]
ok, sensitivity was same, i copied my personal model file over and its much better...  i didn't compare 'smart_mirror.umdl' between the two solutions

**Comment by eouia** [comment]
Maybe it's related with `applyFrontend` (pre-sound processing for detection). It was not implemented on this Hotword module.
Anyway, I'm building new detection module which can accept continuous phrase. ("snowboy do something" is available, instead "snowboy (ding, wait) do something"). On that module, I'll add applyFrontend feature to get better detection.

**Comment by sdetweil** [comment]
ok.. good luck.. snowboy vocabulary is still pretty small.. 
using my personal model is ok

smart-mirror transitions to google speech api after hotword, then back to snowboy for hotword detection, then back to google speech api...  sppech api is not free... don't send detected words except after hotword

**Comment by eouia** [comment]
Yes. it will be so. (at least will be configurable)

**Comment by sdetweil** [comment]
i found a bug in arecord streaming to stdout... after 18 hours continuous, it gets stuck in loop.. (2 gig .wav file size calculation)....  have to stop/restart..  

he has a node module for this snowboy/... transition  
https://www.npmjs.com/package/sonus
and using pgm is https://github.com/evancohen/smart-mirror/blob/master/sonus.js, but there is still a transition time

**Comment by eouia** [comment]
I’m rebuilding this. I’ll consider new structure. Plz wait for a while.
