### ISSUE TITLE
incorrect hotword detection

### ISSUE THREAD

**Issue by sdetweil** [eouia/MMM-Hotword#34]
I am running hotword, using  my own voice model, also used in the other smart-mirror. 
using the same platform, os, and mic, i am receiving hotword notifications when there clearly was no hotword  spoken.   noise, clear my throat, taking on the phone

how can I debug this? 
```
[HOTWORD] <<  smart mirror  >> is detected.
[HOTWORD] stops listening
MMM-Hotword helper notification PAUSE received
assistant play chime=/home/odroid/MagicMirror/modules/MMM-AssistantMk2/resources/connection.mp3
assistant play sound file=/home/odroid/MagicMirror/modules/MMM-AssistantMk2/resources/connection.mp3
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response:
[AMK2] end-of-utterance
[AMK2] Assistant Text Response:
MMM-Hotword helper notification RESUME received
[HOTWORD] begins listening.
```

**Comment by eouia** [comment]
Adjust sensitivity in configuration. Accuracy of detection is lying on Snowboy engine itself, so there isn't many things to do by end users.

**Comment by sdetweil** [comment]
but... this is the same config as in the other smart mirror where I don't have this problem.. something is different
other config
```
  "speech": {
    "device": "default",
    "keyFilename": "./keyfile.json",
    "hotwords": [
      {
        "keyword": "smart mirror",
        "model": "smart_mirror.umdl"
      }
    ],
    "sensitivity": 0.5
  },
```
MMM-HW config
```
config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1,0",
      },
      snowboy: [
      {
        hotwords: "smart mirror", //this will be sended to other module for distinguishing which hotword is detected.
        file: "resources/models/smart_mirror.umdl",
        sensitivity: '0.5',
      },
      ],
```
the smart_mirror.umdl files are identical

**Comment by eouia** [comment]
Sorry, I have no idea about inside of detection in snowboy. Maybe your other smartmirror solution might be using different version of detection engine. (I don't know about it.)

But there is something weird point on your words. You've said `your own model`. Does it mean `.pmdl` - personal model? but your config shows `.umdl` - universal model.
And `Other smart mirror` means `OTHER DEVICE` (another ODRIOD) ? or just other program on one ODRIOD?
personal model created for one device is not working properly on other device. If you want to use personal model on several devices, you should create each personal model on each device.

But if not that case, still I have no better idea except adjusting sensitivity.

**Comment by eouia** [comment]
I'll close this issue, If I found something, I'll reopen this.
