### ISSUE TITLE
Having error with installing MMM-Hotword

### ISSUE THREAD

**Issue by MichaelKimYS** [eouia/MMM-Hotword#36]
I have been trying to install MMM-Howord with these command below

cd ~/MagicMirror/modules/MMM-Hotword/
npm install

But these the installation get these error all the time.
I don't know why this happens...
I need your helps

![1](https://user-images.githubusercontent.com/49549127/56017806-5579a580-5d3b-11e9-860d-9bfae3c97ee1.png)
![2](https://user-images.githubusercontent.com/49549127/56017814-58749600-5d3b-11e9-8571-c7fa21decc66.png)
![3](https://user-images.githubusercontent.com/49549127/56017815-5a3e5980-5d3b-11e9-8c44-17e436b286eb.png)
![4](https://user-images.githubusercontent.com/49549127/56017819-5d394a00-5d3b-11e9-99e7-7b6a14f8be66.png)
![5](https://user-images.githubusercontent.com/49549127/56017825-5f9ba400-5d3b-11e9-9aac-2f4aeaad56cb.png)
![6](https://user-images.githubusercontent.com/49549127/56017832-62969480-5d3b-11e9-8725-7acea2892f42.png)
![7](https://user-images.githubusercontent.com/49549127/56017846-6d512980-5d3b-11e9-9d19-9c8a16056a57.png)
![8](https://user-images.githubusercontent.com/49549127/56017851-717d4700-5d3b-11e9-9aaa-76ea745b9df3.png)

**Comment by MichaelKimYS** [comment]
참고로 한국 사람입니당

**Comment by eouia** [comment]
한글로 답변드릴게요. ^^; Snowboy에서 올려둔 바이너리가 별로 잘 설치가 안되더라구요.

아래를 쭈욱 따라오세요.

```
cd ~/MagicMirror/modules/MMM-Hotword/node_modules
rm -rf snowboy
```
일단, node_modules 디렉토리에 불완전하게라도 설치된 snowboy 모듈이 있다면 삭제합니다.
그리고 git repository에서 직접 소스를 내려받아 설치합니다.
```
git clone https://github.com/Kitt-AI/snowboy.git
cd snowboy
rm -rf .git
npm install nan
npm install
```
워닝이나 에러가 나올 수 있는데, 워닝은 무시하시고, gyp 폴백 에러도 무시하시면 됩니다.

```
./node_modules/node-pre-gyp/bin/node-pre-gyp clean configure build
```
snowboy의 npm 패키지에 들어있는 gyp 관련 부분이 좀 엉망이라서 다시 깨끗하게 실행해줍니다.

여기까지 되었다면 (에러가 나오든 워닝이 나오든간에..)
`lib/node` 밑에 `index.js`, `index.ts` 두 개 파일이 존재해야 하구요.
`lib/node/binding/Release` 밑에 `node-V57-linux-arm` (혹은 환경에 따라 조금 이름이 다를 수 있습니다) 폴더가 있고 그 안에 `snowboy.node` 가 있어야 합니다.

그러고 나면, 다시 매직미러의 electron을 위해 리빌딩을 해주면 됩니다.
```
npm install --save-dev electron-rebuild
./node_modules/.bin/electron-rebuild
```
그러면 `lib/node/binding/Release` 밑에 `electron-v3.0-linux-arm` 뭐 이런 디렉토리가 생겼다면 인스톨이 성공한 것입니다.
막히시는 부분에서 코멘트 주세요.

**Comment by IronWing2** [comment]
안녕하세요.  위에 분과 동일한 문제여서 답글 내용대로 진행했습니다만 아래와 같이 에러나 나오네요.

WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'node-pre-gyp'

제가 완전 초보라 어떻게 해결해야할지 모르겠습니다.

**Comment by eouia** [comment]
@IronWing2 어느 단계에서 그 에러가 나오던가요? 
```
./node_modules/node-pre-gyp/bin/node-pre-gyp clean configure build
```
이 단계에서 그렇다면, 그 앞에 `npm install` 부분이 제대로 안되었을 겁니다.


일단 맨 처음에,
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install libmagic-dev libatlas-base-dev
sudo apt-get install sox libsox-fmt-all
```
이거 해주시고 다시 위 설명대로 진행해보세요.

**Comment by IronWing2** [comment]
네 답변감사합니다.
말씀대로 다시 처음부터 진행했습니다.

./node_modules/node-pre-gyp/bin/node-pre-gyp clean configure build

요거 진행 후에 폴더 lib/node 밑에 index.js, index.ts 두 개 파일 중에 index.ts는 있으나 index.js는 없네요. 
무엇을 빼먹었는지 모르겟습니다. 염치 불구하고 다시 여쭤봅니다.

**Comment by eouia** [comment]
npm install 다시 해주세요.

**Comment by MichaelKimYS** [comment]
답변 감사드립니다!!
해보고 다시 말씀 드릴게요!

**Comment by MichaelKimYS** [comment]
일단 저도 문제는 index.js 파일이 해당 경로에 없습니다.항상 여기서 이 파일이 안생겨서 문제였는데 알려주신 위의 방법대로 해봐도 안생기네요... 해당 에러들 같이 올려드릴까요?...고생이 많으십니다 ㅜㅜ

**Comment by eouia** [comment]
`npm install` 하면 `package.json`에서 지정된 대로 `prepublish` 스크립트로 tsc를 돌려서 `index.ts`로부터 `index.js`가 만들어져야 하는데요.. 흠...
`npm install`시 에러나 워닝이 있더라도, 가장 마지막 부분에서는

```
> snowboy@1.3.1 prepublish /Users/eouia/Documents/nodeJS/snowboy
> tsc --listFiles

/.../snowboy/node_modules/typescript/lib/lib.es6.d.ts
/.../snowboy/lib/node/index.ts
/.../snowboy/lib/node/node-pre-gyp.d.ts
/.../snowboy/lib/node/SnowboyDetectNative.d.ts
/.../snowboy/node_modules/@types/node/index.d.ts
/.../node_modules/@types/long/index.d.ts
```
이게 보여야 할텐데요....

**Comment by MichaelKimYS** [comment]
npm install 했을때 이렇게 나옵니다
이게 제대로 됐는지가 의아합니다.
말씁해주신 대로 이게 제대로 됐다면 index.js 파일이 생겨야하는게 맞지 않나요?
![3](https://user-images.githubusercontent.com/49549127/56153512-5176ad80-5ff1-11e9-96ac-67086c89daca.png)

![1](https://user-images.githubusercontent.com/49549127/56153497-491e7280-5ff1-11e9-82b2-45e44ba9ce27.png)
![2](https://user-images.githubusercontent.com/49549127/56153499-4c196300-5ff1-11e9-84f0-0671face51e0.png)
![4](https://user-images.githubusercontent.com/49549127/56153523-563b6180-5ff1-11e9-9d1c-03a42b6023de.png)
![5](https://user-images.githubusercontent.com/49549127/56153531-59365200-5ff1-11e9-9863-b32536a76589.png)

**Comment by MichaelKimYS** [comment]
제꺼에선 > snowboy@1.3.1 prepublish /Users/eouia/Documents/nodeJS/snowboy
> tsc --listFiles

/.../snowboy/node_modules/typescript/lib/lib.es6.d.ts
/.../snowboy/lib/node/index.ts
/.../snowboy/lib/node/node-pre-gyp.d.ts
/.../snowboy/lib/node/SnowboyDetectNative.d.ts
/.../snowboy/node_modules/@types/node/index.d.ts
/.../node_modules/@types/long/index.d.ts
이게 안보이네요...

**Comment by eouia** [comment]
음.. 그럼..
snowboy 디렉토리의 package.json 파일을 열고,
```
"dependencies": {
    "node-pre-gyp": "^0.6.30"
  },
```
이렇게 되어 있는 부분을 찾아서, 
```
"node-pre-gyp": "^0.12.0"
```
버전 번호를 바꿔서 저장하시고 다시 `npm install` 해보세요. T_T

**Comment by MichaelKimYS** [comment]
넵 위에대로 일단 해봤는데
어찌저찌 하다 보니 index.js 파일이 생기긴 했는데
npm install 후에 index.js가 생기고 아래 명령을 진행하면 다시 이 파일이 사라지더라구요...;
./node_modules/node-pre-gyp/bin/node-pre-gyp clean configure build

npm install 해도 에러 문구는 위에 사진들과 같구요
그래서 일단 아래 건 안하고 진행했습니다... 혹시 문제 생길 여지가 있나요?...

**Comment by eouia** [comment]
위에 있는 에러랑 워닝은 신경안쓰셔도 됩니다. index.js와 node-... 폴더에 snowboy.node만 생성되면 됩니다.
그 상태에서 electron-rebuild 하시면 됩니다.

**Comment by eouia** [comment]
node-pre-gyp clean ... => 이건 snowboy.node가 생겼다면 더 안해도 됩니다. 이 상태에서 index.js가 없다면 npm install 을 해주시면 index.js가 생길겁니다.
그럼 그 다음에 electron-rebuild 하시면 됩니다.

**Comment by IronWing2** [comment]
안녕하세요. 기존 폴더 다 지우고 package.json 버전까지 수정하고 다시 npm install 진행하니 index.js가 생겼습니다. 감사합니다.

헌데 한가지 매직미러가 실행이 잘 됩니다만 음성으로 질문을 하면 띵동하고 소리난 후에 대답을 안하네요. 어느 부분이 잘못된건지 궁금합니다.

**Comment by eouia** [comment]
우선 에러 로그와 config를 보여주세요.
아마 모듈의 로그 세팅이 안보이는 것로 되어 있을텐데,
MMM-AssistantMk2의 configuration에서 `verbose:true`를 해주세요.
```
...
  config: {
    verbose: true,
    ...
```
그럼 상세한 에러로그를 얻으실 수 있을거에요. 가능하면 테스트 중에는 다른 모듈은 빼고 테스트하는게 좀 더 편하실 겁니다.

**Comment by MichaelKimYS** [comment]
저도 일단 끝까지 다 해봤는데 막상 매직미러를 키면 검은 화면만 나오네요...;;;

**Comment by eouia** [comment]
@MichaelKimYS @IronWing2 
에러로그가 없으면 뭐가 문제인지 알 수 없기 때문에 도와드릴 수가 없어요.
그리고 MM을 켰을 때 아무 것도 안나오고 검은 화면만 나온다면 대부분 스타트업시 에러가 발생했기 때문일거에요.

**Comment by MichaelKimYS** [comment]
검은 화면만 나올때 커멘더 창에 올라오는 것들 사진입니당.
![1](https://user-images.githubusercontent.com/49549127/56189186-4e67d580-6062-11e9-861a-2f4de4d805eb.png)
![2](https://user-images.githubusercontent.com/49549127/56189187-50ca2f80-6062-11e9-9849-bcf9e7583102.png)
![3](https://user-images.githubusercontent.com/49549127/56189191-532c8980-6062-11e9-8809-ad4462fce25b.png)
![4](https://user-images.githubusercontent.com/49549127/56189198-5758a700-6062-11e9-86c7-764b60e805a2.png)

스타트업시 에러는 어떻게 해결해야하나요?...

**Comment by eouia** [comment]
electron-rebuild 단계 안하신 것 같네요.

**Comment by MichaelKimYS** [comment]
electron-rebuild 라면 

npm install --save-dev electron-rebuild
./node_modules/.bin/electron-rebuild

이거 말씀하시는 거 아닌가요?
분명 했긴 했는데 다시 해보겠습니당,...

**Comment by MichaelKimYS** [comment]
아 그런데 index.js가 생겼다 없어졌다 하는 건 원래 그런 건가요? 있었던 파일이 갑자기 또 없네요

**Comment by eouia** [comment]
node-pre-gyp를 실행하면 아마 clean하게 다시 만드는 거라서 지워질 수 있습니다.
npm install에서 prepublish 스크립트가 실행되면 다시 생길 거에요. (경우에 따라서 npm install을 두 번 해야 할 수 있습니다. )
그러니까, electron-rebuild까지 들어가려면 index.js와 node-VXX-linux-arm폴더 밑에 snowboy.node가 있는지 확인하시고 실행하세요.

**Comment by eouia** [comment]
snowboy node 라이브러리가 좀 그지 같긴 해요.

**Comment by MichaelKimYS** [comment]
index.js와 node-VXX-linux-arm폴더 밑에 snowboy.node 까지 확인하고 electron-rebuild를 해줬느데


lib/node/binding/Release 밑에 electron-v3.0-linux-arm 파일이 안생기네요 그 자리에는 electron-rebuild 후에도 node-VXX-linux-arm만 있네요

**Comment by eouia** [comment]
electron-rebuild 시에 에러는 따로 없던가요?

**Comment by MichaelKimYS** [comment]
![2019-04-16-163020_800x480_scrot](https://user-images.githubusercontent.com/49549127/56190355-fda5ac00-6064-11e9-9a4b-51055c55ca84.png)

해당 커멘더 창입니다

**Comment by MichaelKimYS** [comment]
지금 보니 한가지 문제가 snowboy 폴더 안에 또 snowboy 폴더가 있고 이런 식으로 몇개가 중복되어 있긴한데 이것 때문에 문제가 생기진 않겠죠?

**Comment by eouia** [comment]
snowboy 지우고 다시설치하세요. 잘못된 곳에 설치하신 것 같습니다.

**Comment by MichaelKimYS** [comment]
문제가 생길 수도 있겠네요 보니까 맨 마지막 snowboy 폴더에는 electron-v3.0-linux-arm 파일이 있네요

**Comment by MichaelKimYS** [comment]
감사합니다. 깔끔하게 snowboy 다시 깔고 electron-rebuild 까지 해주니 화면은 나타납니다!!

**Comment by eouia** [comment]
화면은 나타나는데... 뭐가 안되나요?

**Comment by IronWing2** [comment]
![2019-04-16-171042_1824x984_scrot](https://user-images.githubusercontent.com/49631884/56192992-9b4faa00-606a-11e9-8ad7-8f487a5e5dc1.png)

이렇게 올리면 되나 모르겠네요.. 죄송합니다. 이미지 올리는걸 몰라서요.

**Comment by eouia** [comment]
작동하고 있는 것 같은데요? 아마 문제가 있다면 저 스크롤 아래쪽에 있으려나...

**Comment by eouia** [comment]
그리고 MMM-NotificationTrigger를 굳이 쓰고 계신 걸 보니, 아마 어디에선가 돌고 있다는 한글 설치 가이드 보고 하신 것 같은데, 그거 무지 오래된 옛날 버전에 대한 거라서 현재 모듈과는 셋업 방법 등이 다릅니다.
도대체 어디에 있는 걸까요. 한국에서 물어보시는 분들은 다 그 설치 가이드 때문에 초반에 엉뚱하게 삽질하고 있는 것 같아요...

**Comment by IronWing2** [comment]
![2019-04-16-171743_1824x984_scrot](https://user-images.githubusercontent.com/49631884/56193429-95a69400-606b-11e9-9238-1cc72bb53575.png)

아 그렇군요. 작년 10월경에 유투브에 올려진 영상에 저렇게 올려져 있습니다.
초보가 따라하기 좋게 설명되어 있어서 그것만 보고 시작한거였습니다만 그팀이 업데이트는 안되고 있더라구요.

https://www.youtube.com/watch?v=O3l46ogmgLY&t=1531s
참고로 요기 입니다.

**Comment by eouia** [comment]
일단 로그를 보면 정상 작동하고 있는 것 같습니다만....

**Comment by IronWing2** [comment]
그럼 이 
![2019-04-16-172959_1824x984_scrot](https://user-images.githubusercontent.com/49631884/56194160-4b261700-606d-11e9-9051-94871d5f1707.png)
config가 문제 일수 있겠네요.

**Comment by eouia** [comment]
음.. 지금 뭐가 문제이신지를 잘 모르겠네요. 어떤 증상이 있으신거죠?
configuration은 이 문서를 참조하세요.
https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration#with-mmm-hotword-using-usb-mic-plughw1

**Comment by IronWing2** [comment]
![2019-04-16-173200_1824x984_scrot](https://user-images.githubusercontent.com/49631884/56194271-8de7ef00-606d-11e9-8033-1cab3d2d978a.png)
![2019-04-16-173219_1824x984_scrot](https://user-images.githubusercontent.com/49631884/56194282-993b1a80-606d-11e9-8263-4b6fbcdebbae.png)
![2019-04-16-173238_1824x984_scrot](https://user-images.githubusercontent.com/49631884/56194301-a48e4600-606d-11e9-9a11-18d9e12fed2c.png)
![2019-04-16-173255_1824x984_scrot](https://user-images.githubusercontent.com/49631884/56194322-af48db00-606d-11e9-9967-705114ad9c54.png)
![2019-04-16-173309_1824x984_scrot](https://user-images.githubusercontent.com/49631884/56194339-b66fe900-606d-11e9-81c5-0d5fe7825b97.png)
현재 config 파일입니다.

**Comment by IronWing2** [comment]
아 반응이 없습니다. 제 질문에 반응을 하는데 응답을 안해요.

**Comment by eouia** [comment]
일단 MMM-NotificationTrigger 삭제하시고, 위에 드린 링크의 문서를 참조하셔서 config를 수정하세요.
그리고 테스트 중에는 가능한 다른 관련 없는 모듈은 빼고 테스트하신 후, 문제가 없다면 다른 모듈을 차례로 추가하는 식으로 테스트해보시는 것이 좋습니다.

**Comment by IronWing2** [comment]
감사합니다. 말씀하신대로 다 정리하고 config는 알려주신 자료보고 하니 작동이 제대로 됩니다. 일주일만에 작동되네요. ㅎㅎ

https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration#with-mmm-hotword-using-usb-mic-plughw1

**Comment by MichaelKimYS** [comment]
IronWing2 
혹시 config는 어떻게 해결하셨나요?
저도 증상 같아서요

**Comment by MichaelKimYS** [comment]
혹시  MMM-NotificationTrigger 삭제는 어떻게 해야하나요?
위 링크를 봐도 config를 어떻게 수정해야하는지 막막하네용...

**Comment by eouia** [comment]
그냥 지우면 됩니다. 그리고 위링크의 config 그대로 가져다 쓰시면 되요.

**Comment by IronWing2** [comment]
회신이 늦었네요. 저도 아래 주소에 있는 내용으로 덮어씌웠습니다. 그러니 작동되더라구요. ㅎㅎ

https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration#with-mmm-hotword-using-usb-mic-plughw1

**Comment by mirrormirror98** [comment]
@eouia I have the same issue. I don't speak Korean and google translate does not help me very much. Can you make a short description on what i have to do to get it working. Thanks

**Comment by eouia** [comment]
@mirrormirror98 You'd better post a new issue. I'll close this issue. Feel free to create new issue.

**Comment by MichaelKimYS** [comment]
안녕하세요!! 아직도 위의 문제를 해결하지 못했습니다...
현재 상황은 modules 폴더에서 MMM-NotificationTrigger 폴더는 그냥 통체로 휴지통으로 보냈고

위의 링크의  config파일에서는 파트가 3부분으로 나눠져있는걸

2번째, 3번째 그대로 복사해서 MagicMirror/config/에 있는 config.js 파일에 복사 붙히기해요 
그냥 계속 아래와 같은 화면뜨고 아무것도 안됩니다!!
매번 번거롭게 해드려서 미안하네요... 

config 파일은 말그대로 그냥 링크 복사 떠와서 아래와 같이 했습니다.

{
  module: "MMM-AssistantMk2",
  position: "top_right",
  config: {

    // --- ESSENTIALS / modifying for your environment might be needed.


    deviceLocation: {
      coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
        latitude: 51.5033640, // -90.0 - +90.0
        longitude: -0.1276250, // -180.0 - +180.0
      },
    },

    defaultProfile: "default", // If you have several profiles and want to set one of them as default profile, describe here.

    profiles: {
      "default" : { // profile name.
        profileFile: "default.json", // profile file name.
        lang: "en-US"
        //currently available (estimation, not all tested):
        //  de-DE, en-AU, en-CA, en-GB, en-US, en-IN
        // fr-CA, fr-FR, it-IT, ja-JP, es-ES, es-MX, ko-KR, pt-BR
        // https://developers.google.com/assistant/sdk/reference/rpc/languages
      },
      /* Add your other profiles here, if exists.
      "other_profile" : {
        profileFile: "other.json",
        lang: "de-DE"
      }
      */
    },

    record: { // Full values are in `FOR EXPERTS` section.
      recordProgram: "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
      device: null        // recording device (e.g.: "plughw:1")
    },

    play: { // Full values are in `FOR EXPERTS` section.
      playProgram: "mpg321", // recommended.
    },


    // --- OPTIONAL / not important but customizable for your usage


    responseVoice: true, // If available, Assistant will response with her voice.
    responseScreen: true, // If available, Assistant will response with some rendered HTML
    responseAlert: true, // If available, Assistant will response with Alert module of MM
    // Sometimes, any response might not be returned. responseAlert is useful for displaying error.

    screenZoom: "80%", // Adjust responseScreen to your mirror size.
    screenDuration: 0, // milliseconds. How long responseScreen will be shown after speech.
    //If you set 0, Screen Output will be closed after Response speech finishes ASAP.

    youtubeAutoplay: true, //If set as true, found Youtube video will be played automatically.
    pauseOnYoutube:true, //If set as true, You cannot activate Assistant during youtube playing. Recommended for the performance (Because permanent hotword detecting might make performance lower)

    youtubePlayerVars: { // You can set youtube playerVars for your purpose, but should be careful.
      "controls": 0,
      "loop": 1,
      "rel": 0,
    },
    youtubePlayQuality: "default", //small, medium, large, hd720, hd1080, highres or default

    useWelcomeMessage: "", //Try "brief today" as this value. You can use this value to check module working when MM is starting.

    onIdle: {
      //timer: 1000*60*30, // if you don't want to use this feature, just set timer as `0` or command as ""
      //command: "HIDEMODULES",
      timer: 0,
      command: null,
    },

    onActivate: {
      timer: 0,
      //command: "SHOWMODULES"
      command: null,
    },


    // --- FOR EXPERTS / For development, debug or more


    verbose:false, // You can get error or some logs when this value is set as true.
    ignoreNoVoiceError: true, //To avoid some annoying youtube stop bug.

    startChime: "connection.mp3", // you can use `mp3` to play chime when your mic is ready. It should be playable with your `play.playProgram`
    noChimeOnSay: false, // When using the `ASSISTANT_SAY` trigger, you can prevent the chime from being played before your words

    auth: { // I believe you don't need to change this.
      keyFilePath: "./credentials.json"
    },

    record:  { // Full version
      sampleRate    : 16000,      // audio sample rate
      threshold     : 0.5,        // silence threshold (rec only)
      thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
      thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
      silence       : 1.0,        // seconds of silence before ending
      verbose       : false,      // log info to the console
      recordProgram : "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
      device        : null        // recording device (e.g.: "plughw:1")
    },

    play: { // Full version
      encodingOut: "MP3", //'MP3' or 'WAV' is available, but you might not need to modify this.
      sampleRateOut: 24000,
      playProgram: "mpg321", //Your prefer sound play program. By example, if you are running this on OSX, `afplay` could be available.
      playOption: [],
      // If you need additional options to use playProgram, describe here. (except filename)
      // e.g: ["-d", "", "-t", "100"]
    },

    useGactionCLI: false, // If set as true, you can update your gAction when MM is rebooted.
    projectId: "", // Google Assistant ProjectId (Required only when you use gAction.)
    deviceModelId: "", // It should be described in your config.json. In most of case, you don't need to this.
    deviceInstanceId: "", // It should be described in your config.json. In most of case, you don't need to this.

    recipes:["hide_and_show_all_modules.js", "reboot.js", "screen_onoff.js", "shutdown.js"],
    transcriptionHook: {},
    action: {}, // You can catch your gAction command.
    command: {}, // You can catch transcription hook and be able to make your own `COMMAND` with this.
    //See the `transcriptionHook` section.
    action:{}, // You can make your own MM command for gAction and transcriptionHook
    //See the `command` section.

    notifications: { // You can redefine these notifications to communicate with specific modules.
      ASSISTANT_ACTIVATE: "ASSISTANT_ACTIVATE",
      ASSISTANT_DEACTIVATE: "ASSISTANT_CLEAR",
      ASSISTANT_ACTIVATED: "ASSISTANT_ACTIVATED",
      ASSISTANT_DEACTIVATED: "ASSISTANT_DEACTIVATED",
      ASSISTANT_ACTION: "ASSISTANT_ACTION",
      ASSISTANT_UNDERSTOOD: "ASSISTANT_UNDERSTOOD",
      ASSISTANT_RESPONSE_END: "ASSISTANT_RESPONSE_END",
      DEFAULT_HOOK_NOTIFICATION: "ASSISTANT_HOOK",
      TEXT_QUERY: "ASSISTANT_QUERY",
      SAY_TEXT: "ASSISTANT_SAY",
    }
  }
},
{
    module: "MMM-AssistantMk2",
    position: "top_right",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },

      notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      },
    }
  },
  {
    module: "MMM-Hotword",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },
      autostart:true,
      onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },
    },
  },
![2019-04-27-220012_800x480_scrot](https://user-images.githubusercontent.com/49549127/56850070-22890180-6938-11e9-8187-cc80323304fe.png)

**Comment by eouia** [comment]
@MichaelKimYS 
우선 현재 상태는, config.js에서 syntax 오류가 난건데요, 대개의 경우, 콤마나 괄호를 빼먹어서 생기는 현상입니다.

그런데, 그건 그렇다치고,
MagicMirror의 config에 대해서 잘 이해하지 못하고 계신 것 같아요.
일단 MMM-AssistantMk2와 MMM-Hotword의 configuration을 그냥 다 지우시고,
https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration#with-mmm-hotword-using-usb-mic-plughw1 이 링크에서 바로 보이는 설정 예제 하나만 넣어서 다시 해보세요. 지금은 MMM-AssistantMk2에 대한 config을 두 번 넣은 것 자체부터 문제네요.

**Comment by MichaelKimYS** [comment]
네 알겠습니다. 아네 지금 솔직히 라즈베리 처음 써보기도 하고 config가 뭐해주는 애인지도 잘 모르겠습니다.흠... 일단 해보고 다시 말씀 드리겠습니다!!

**Comment by cstar22** [comment]
저희가 구글어시스턴트 스마트미러를 설치중입니다
그런데 처음에 설치했을때는 잘 실행되었는데 포맷할 일이 있어서 포맷후 재설치를 하는데 수없이 반복해도 마지막 실행시키면 검은색 화면만 나오고 실행이 안됩니다 도움 부탁드립니다...
WARNING! could not load config file. starting with default configuration. Error found: Error: Cannot find module './snowboy/lib/node/index.js'
이 부분이 문제인거 같은데 해결방법좀 부탁드립니다..

**Comment by eouia** [comment]
@cstar22  가능하면 새 이슈로 올려주시는 게 좋은데요.. 남의 이슈에 붙여서 이야기하는게 좀 비매너이기도 하고.
MMM-Hotword 설치가 잘못되었는데, 혹시 새로 업데이트 된 버전을 documents/install.md 대로 따라서 설치하신 거 맞나요? 한국분들이 올리시는 이슈들은 대부분, 누가 적었는지 모르겠는데 한글로 적혀있는 설치 문서 보고 적으시는 것 같은데 전 그런 걸 적은 적이 없거든요. 아무튼 아주 옛날 버전용인 거 같아요, 현재 버전과 안맞을 겁니다.
