### ISSUE TITLE
Almost there.....

### ISSUE THREAD

**Issue by dxfan227** [eouia/MMM-Hotword#38]
So everything loads fine... I get my daily brief from assistant.... but when I say the hot word I get the little notification sound and then nothing ... it doesn’t listen to my request..... and then from that point the hotword doesn’t trigger the *beep* sound.

It did say “conversation error” in assistant one time.... but I can’t reproduce that.

I am not using mmm notification is it still required?

**Comment by eouia** [comment]
no required on this version. I think you've missed something in config. show me your config

**Comment by dxfan227** [comment]
Hi thanks for the reply. Here is my config.js file

`
	modules: [
	{
  module: "MMM-AssistantMk2",
  position: "top_right",
  config: {
    useWelcomeMessage: "brief today",
    deviceLocation: {
      coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
        latitude: 33.600710, // -90.0 - +90.0
        longitude: -117.897580, // -180.0 - +180.0
	notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      }
  }
}
  }
},

 {
    module: "MMM-Hotword",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },
      autostart:true,
      onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },
    },
  },`

**Comment by eouia** [comment]
first. How's your environment of mic? You've set as `plughw:1` for MMM-Hotword, but nothing for MMM-AssistantMk2.

**Comment by dxfan227** [comment]
@eouia 

I am not sure.....The mic is a playstation eye webcam.....I seem to be able to record audio and video from it with no problems within rasbian. It also seems to be picking up the hot word when I speak it........but maybe it's not hearing me for mmm-assistantmk2? How do I test that/ set it for Assistant

**Comment by eouia** [comment]
You just didn't set it for configuration of MMM-AssistantMk2. I think you just need to add 
```
record: {
  recordProgram : "arecord",
  device : "plughw:1",
},
```
to MMM-AssistantMk2 also like MMM-Hotword.

**Comment by dxfan227** [comment]
I will try when I get home tonight and report back, in the mean time. An you please keep this issue open?

Also so I don’t clutter the page, what are the steps to train a new hotword?

**Comment by dxfan227** [comment]
so i added the config and now magic mirror wont load :(

`modules: [
	{
  module: "MMM-AssistantMk2",
  position: "top_right",
  config: {
	  record: {
  recordProgram : "arecord",
  device : "plughw:1",
}
    useWelcomeMessage: "brief today",
    deviceLocation: {
      coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
        latitude: 33.600710, // -90.0 - +90.0
        longitude: -117.897580, // -180.0 - +180.0
	notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      }
  }
}
  }
},

 {
    module: "MMM-Hotword",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },
      autostart:true,
      onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },
    },
  },`

**Comment by dxfan227** [comment]
Ok I fixed the code... hotnword works.... assistant works..... but only once... after that hot word doesn’t recognize

**Comment by eouia** [comment]
show me your log on the issue happening.

**Comment by dxfan227** [comment]
I think I fixed it... the notification send from mmm assistant was not working... I had to “hard code” it into the .js file

**Comment by eouia** [comment]
All is good if the end is good. I'll close this issue. Wish you a good luck.
