### ISSUE TITLE
Can not install, Show npm error

### ISSUE THREAD

**Issue by polashmahmud** [eouia/MMM-Hotword#39]
Hi, When i command npm install it's show below error. Please tell me a clue how can i solved this problem.

`npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm ERR! path /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
npm ERR! code EISGIT
npm ERR! git /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy: Appears to be a git repo or submodule.
npm ERR! git     /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-04-24T16_46_12_828Z-debug.log
`

**Comment by eouia** [comment]
go to snowboy directory then remove `.git` then try again.
```
cd ~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
rm -rf .git
```

**Comment by polashmahmud** [comment]
Install is complite, and it's working. Thanks man :)

**Comment by eouia** [comment]
Nice to hear it. I'll close this issue.
