### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by JooMiHyun** [eouia/MMM-Hotword#4]
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ sudo npm install
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer

> snowboy@1.3.1 install /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.8.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.8.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.8.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.8.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN gyp installWARN install got an error, rolling back install
 got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/.node-gyp'
gyp ERR! System Linux 4.14.52-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm"
gypgyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
 gyp WARNERR! node -v v10.8.0
 installgyp  got an error, rolling back install
ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/.node-gyp'
gyp ERR! System Linux 4.14.52-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
node-pre-gyp ERR! System Linux 4.14.52-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
node-pre-gyp ERR! node -v v10.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)
npm WARN MMM-Hotword@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowboy@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-26T15_25_16_030Z-debug.log

what can i do?

**Comment by eouia** [comment]
First, you don't need to use `sudo npm install`. It could make authority problem.
try `npm install snowboy` and after that, `electron-rebuild` might be needed.

**Comment by eouia** [comment]
한국분이신 것 같아서 추가로 한글로 적습니다.
일단 snowboy 모듈 자체는,
```
cd ~/MagicMirror/modules/MMM-Hotword
npm install
또는
npm install snowboy
```
만으로 인스톨하시면 됩니다. 가끔 실패할 수 있는데, 그냥 다시 시도해보시면 되요.

그런데, 매직미러의 kiosk mode (Electron)에서 사용하시려면 snowboy 설치 후 추가로 electron 버전에 맞게 바이너리 리빌딩이 필요합니다. 

그 경우에는,
```
cd ~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
npm install --save-dev electron-rebuild
npm install nan
./node_modules/.bin/electron-rebuild
```
을 해보세요.

**Comment by JooMiHyun** [comment]
감사합니다. 하지만 sudo ./node_modules/.bin/electron-rebuild를 실행하면 이런 오류가 발생합니다..
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy $ sudo npm install nan
+ nan@2.11.0
updated 1 package and audited 313 packages in 9.062s
found 0 vulnerabilities

pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy $ sudo ./node_modules/.bin/electron-rebuild
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@9.11.2 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.electron-gyp/.node-gyp/iojs-1.7.13/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.electron-gyp/.node-gyp/iojs-1.7.13',
gyp info spawn args   '-Dnode_gyp_dir=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.electron-gyp/.node-gyp/iojs-1.7.13/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
snowboy.target.mk:136: recipe for target 'Release/obj.target/snowboy.node' failed
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/build'
make: *** [Release/obj.target/snowboy.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.14.52-v7+
gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/.bin/node-gyp" "rebuild" "--target=1.7.13" "--arch=arm" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v1.7-linux-arm" "--remote_path=./snowboy/v1.3.1/Release/" "--package_name=snowboy-v1.3.1-electron-v1.7-linux-arm.tar.gz" "--host=https://snowboy-release-node.s3-us-west-2.amazonaws.com"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
gyp ERR! node -v v9.11.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@9.11.2 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.electron-gyp/.node-gyp/iojs-1.7.13/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.electron-gyp/.node-gyp/iojs-1.7.13',
gyp info spawn args   '-Dnode_gyp_dir=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.electron-gyp/.node-gyp/iojs-1.7.13/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
snowboy.target.mk:136: recipe for target 'Release/obj.target/snowboy.node' failed
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/build'
make: *** [Release/obj.target/snowboy.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.14.52-v7+
gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/.bin/node-gyp" "rebuild" "--target=1.7.13" "--arch=arm" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v1.7-linux-arm" "--remote_path=./snowboy/v1.3.1/Release/" "--package_name=snowboy-v1.3.1-electron-v1.7-linux-arm.tar.gz" "--host=https://snowboy-release-node.s3-us-west-2.amazonaws.com"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
gyp ERR! node -v v9.11.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/spawn-rx/lib/src/index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/rxjs/Subscriber.js:242:16)
    at SafeSubscriber.error (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/rxjs/Subscriber.js:201:26)
    at Subscriber._error (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/rxjs/Subscriber.js:132:26)
    at Subscriber.error (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/rxjs/Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/rxjs/Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/rxjs/Subscriber.js:106:18)
    at SafeSubscriber._next (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/spawn-rx/lib/src/index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/rxjs/Subscriber.js:242:16)
    at SafeSubscriber.next (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/rxjs/Subscriber.js:189:22)

**Comment by eouia** [comment]
음.. 깨끗이 다시 설치하는 게 나을 것 같습니다.
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install libmagic-dev libatlas-base-dev
sudo apt-get install sox libsox-fmt-all
```
일단 이걸로 필요한 디펜던시들이 다 설치되었는지 확인하시구요.

```
cd ~/MagicMirror/modules
rm -rf MMM-Hotword
```
이걸로 기존 설치된 것 지우시구요.

```
cd ~/MagicMirror/modules
git clone https://github.com/eouia/MMM-Hotword.git
cd MMM-Hotword
npm install
```
이렇게 해서 일단 설치해봅니다. 
WARN 등은 무시하셔도 되고 ERR 또는 ERROR이라고 명확히 에러가 발생하는 경우만 확인하세요.
만약 snowboy 설치 중 에러가 발생한다면,

```
cd ~/MagicMirror/modules/MMM-Hotword
npm install --save snowboy
```
이렇게 해서 설치합니다. 이 과정에 에러가 발생한다면 알려주세요.

일단 여기까지 확인해주세요. 여기까지 하면 `SERVERONLY`모드로 실행은 가능한데, `KIOSK`모드에서는 문제가 될 겁니다. 그건 이후에 처리하면 되고, 일단 여기까지 설치가 클린하게 되는지 확인부탁드려요.

**Comment by eouia** [comment]
혹시 Telegram 사용하신다면 `@eouia` 나,
Kakaotalk 쓰시면 `nowhere0`로 톡 주시면 바로 답변드리겠습니다.

**Comment by eouia** [comment]
이 이슈는 클로즈하겠습니다. 행운을 빌어요.
