### ISSUE TITLE
Can not properly working when i say Hotword

### ISSUE THREAD

**Issue by polashmahmud** [eouia/MMM-Hotword#40]
Hi,
When i say "jarvis" or "smartmirror" sometime it's working and sometime no response. My config file is: https://gist.github.com/polashmahmud/8be1a0f831a49b6516d987095bdd24c0

Can you please say me some way- how can i solved this problem. Thanks :)

**Comment by eouia** [comment]
tell me about detailed "no response". By your pronuciation or environment, snowboy sometimes cannot catch your hotword. In that case just say again. Or you can make your own personal voice model for your voice in snowboy website.

**Comment by polashmahmud** [comment]
Thanks for your replay. Fast of all - solved my problem, it's my microphone problem. When i change microphone now it's working wonderful. Thanks Eouia, your MMM-Howord and MMM-AssistantMk2 just amazing. 

Just one question: How can i add more Hotword?

**Comment by eouia** [comment]
You can make your personal Hotword (voice model) - `.pmdl`.
- https://snowboy.kitt.ai/
- Or if you have some knowledge about this kind thing, http://docs.kitt.ai/snowboy/#api-v1-train It's better (Use shell script or python script in that document)

Then put created .pmdl file into `resources` directory, then add its info in `snowboy: []` section of configuration.

Warning: creating .pmdl should be done on RPI. If you make it on other device, it will not work on your RPI.

**Comment by polashmahmud** [comment]
Thanks, Since my problem has been solved. you can close this issue.
