### ISSUE TITLE
Hotword listen once and Google page open

### ISSUE THREAD

**Issue by JohnB7777** [eouia/MMM-Hotword#44]
Hello,

I have installed all the modules by following the tutorial but once I say the hotword (jarvis), there is a "beep", the google icon changes (I see an audio symbol) and nothing happens.
Then, a google page opens for me to connect.
Problem : when I click on my account, nothing happens.
And I already got everything about google, including the file auth_and_test.js ...

Here is my config :

 {
                        module: "MMM-Hotword",
                        config:
                        {
                                record: {
                                        recordProgram : "arecord",
                                        device        : "plughw:2"
                                },
                                autostart:true,
                                onDetected: {
                                        notification: (payload) => {
                                        return "ASSISTANT_ACTIVATE"
                                        },
                                        payload: (payload) => {
                                                return {
                                                  profile: payload.hotword
                                                }
                                        }
                                },
                        },
                },
                {
                        module: "MMM-AssistantMk2",
                        position: "top_center",
                        config:
                        {
                        useScreen: true,
                        deviceLocation:{
                                coordinates: {
                                latitude: 47.4925,
                                longitude: 19.0513,
                                                },
                                        },
                        record: {
                                recordProgram : "arecord",
                                device        : "plughw:2",
                                },
                        notifications: {
                                ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
                                ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
                                },
                        profiles: {
                                "default": {
                                        lang: "fr-FR",
                                        },
                               }
                    }
     }

Thanks for helping !

**Comment by eouia** [comment]
if google account page is opened, you probably missed getting permission on auth step, or using account different with your installation and getting auth.

**Comment by JohnB7777** [comment]
I already thought about it and the first time a google page opened, google asked me for permission and I did "authorize".
I also filled in the code that google gave me when I run auth_and_test.js so I don't understand ...

**Comment by eouia** [comment]
well, anyway, it means your token(your PROFILE json file) is not matched/permitted to use assistant. remove your token and try again. if you don't have assistant app on your smartphone, install it and login it also.

**Comment by JohnB7777** [comment]
Ok, I change that and my mistake was a file on /profiles names defaukt.json instead of default.json...
I'm sorry xD
But, now that my problem is fixed, when I say "Jarvis", nothing happens. There is no beep and no icon change...

**Comment by JohnB7777** [comment]
Apparently, my microphone and my speakers don't work while I haven't touched their configuration...

**Comment by eouia** [comment]
I updated MMM-Hotword 3 days ago. Have you updated it? In that case, old configuration is not valid.

**Comment by JohnB7777** [comment]
I also updated it now by following your tutorial and it still not working.
I can't record a sound and my speakers don't work.

pcm.!default{
  type asym
  playback.pcm{
    type hw
    card 0
  }
  capture.pcm{
    type plug
    slave.pcm "hw:1, 0"
  }
}
ctl.!default{
  type hw
  card 0
}

When I type the command "aplay -l" (in french because I'm french ^^) :

Le périphérique de lecture est default
Les paramètres du flux sont 48000Hz, S16_LE, 1 canaux
fichier(s) WAV
Erreur d'ouverture à la lecture: -2,Aucun fichier ou dossier de ce type

So, I don't understand what is the problem...

Thanks again for helping me !

**Comment by eouia** [comment]
I don't know french at all. So I cannot understand what it means exactly, but it seems not the usual result of `aplay -l`
After Hotword update, you need to rewrite your configuration. many things are changed. See the documents.

**Comment by JohnB7777** [comment]
I'm sorry, it says :

The reading device is default
The stream parameters are 48000Hz, S16_LE, 1 channel
WAV file (s)
Error opening to reading: -2, No file or folder of this type

Ok, I'll see the documents.
But, if I'm not wrong, changing the configuration will not solve the sounds problems, right ?

**Comment by eouia** [comment]
`aplay -l` should show your current speaker devices, but your result shows totally different. I don't know what you actually did. 
Anyway, If you have H/W or S/W problem to play sound, I cannot help about that.

**Comment by JohnB7777** [comment]
Hallelujah, speakers and micro work again ! :D
I'm going to try again and I'll let you know

**Comment by eouia** [comment]
Sounds so nice. To make things simple,
1) disable other modules except testing module (In this case, MMM-Hotword & MMM-AssistantMk2)
2) First confirm MMM-Hotword works. Disable MMM-AssistantMk2 also to focus MMM-Hotword.
3) When you are sure your MMM-Hotword works fine, enable MMM-AssistantMk2 again and test both module together.

I wish you have a good luck.

**Comment by JohnB7777** [comment]
I had some progress (I'm very happy ^^) : the MMM-Hotword module hears me when I say "Jarvis" but the word is not written, unlike the word "computer". On the other hand, it remains stuck on it and doesn't do anything. Note that the icon of the MMM-AssistantMk2 module changes when I say "computer" as well.

**Comment by eouia** [comment]
Universal models like "jarvis" or "computer" would be usually designed to fit common voices. However there be possibility of not matching with someone's special voice. Some exercise of pronuciation be needed. Or you can make your own personl model for your voice.

Give me your configuration and logs when it is executed.

**Comment by JohnB7777** [comment]
This is my configuration :

{
                        module: "MMM-Hotword",
                        position: "top_right",
                        config: {
                                mic: {
                                recordProgram: "arecord",
                                device: "plughw:1"
                                        },
                                models: [
                                        {
                                        hotwords    : "computer",
                                        file        : "computer.umdl",
                                        sensitivity : "0.5",
                                        },
                                        {
                                        hotwords: ["jarvis", "jarvis"],
                                        file: "jarvis.umdl",
                                        sensitivity: "0.8,0.8",
                                        },
                                        ],
                                        commands: {
                                                "computer": {
                                                notificationExec: {
                                                notification: "ASSISTANT_ACTIVATE",
                                                payload: (detected, afterRecord) => {
                                                return {profile:"default"}
                                                                }
                                                        },
                                                        restart:false
                                                }
                                        }
                                }
                },
                {
                        module: "MMM-AssistantMk2",
                        position: "top_center",
                        config:
                        {
                        useScreen: true,
                        deviceLocation:{
                                coordinates: {
                                latitude: 43.295101,
                                longitude: 5.386100,
                                                                                 },
                                        },
                        record: {
                                recordProgram : "arecord",
                                device        : "plughw:1",
                                },
                        notifications: {
                                ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
                                ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
                                },
                        profiles: {
                                "default": {
                                        lang: "fr-FR",
                                        },
                                },
                        },
                },
                {
                        module: 'MMM-TTS',
                        //position: 'top_right',
                        config: {
                                }
                },

I start the magic mirror with "pm2 start mm.sh".
Where can I find logs ?

**Comment by eouia** [comment]
If you are using `pm2` to manage running MM, first stop it - `pm2 stop mm` or `pm2 stop MagicMirror` (You can find which process name is used by `pm2 list`)
Then, `npm start dev` on MagicMirror directory. You can get backside-log on terminal and frontside-log on MM screen.

**Comment by JohnB7777** [comment]
**This is my log :**

Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
No helper found for module: MMM-AirQuality.
Initializing new module helper ...
Module helper loaded: MMM-SystemStats
Initializing new module helper ...
Module helper loaded: MMM-NetworkScanner
Initializing new module helper ...
Module helper loaded: MMM-EARTH
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-TTS
Initializing new module helper ...
Module helper loaded: MMM-PIR-Sensor
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
All module helpers loaded.
Starting server on port 8080 ...
Server started ...
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-SystemStats
Connecting socket for: MMM-NetworkScanner
Starting module: MMM-NetworkScanner
Connecting socket for: MMM-EARTH
Starting module: MMM-EARTH
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-TTS
Starting node helper for: MMM-TTS
Connecting socket for: MMM-PIR-Sensor
Connecting socket for: MMM-Remote-Control
Starting node helper for: MMM-Remote-Control
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: http://www.calendarlabs.com/templates/ical/France-Holidays.ics - Interval: 300000
Create new news fetcher for url: http://www.lemonde.fr/rss/une.xml - Interval: 300000
MMM-NetworkScanner received CONFIG
https://epic.gsfc.nasa.gov/api/natural
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.

**When I say "Jarvis" :**

[HOTWORD] Detected: jarvis
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.

**When I say "computer" :**

[HOTWORD] Detected: computer
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'computer', file: null }
Speaker error: 2
Whoops! There was an uncaught exception...
2
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Initializing new module helper ...

**Comment by eouia** [comment]
Try this.
```js
{
  module: "MMM-Hotword",
  position: "top_right",
  config: {
    chimeOnFinish: null,
    mic: {
      recordProgram: "arecord",
      device: "plughw:1"
    },
    models: [
      {
        hotwords    : "computer",
        file        : "computer.umdl",
        sensitivity : "0.5",
      },
    ],
    commands: {
      "computer": {
        notificationExec: {
          notification: "ASSISTANT_ACTIVATE",
          payload: (detected, afterRecord) => {
            return {profile:"default"}
          }
        },
        restart:false,
        afterRecordLimit:0
      }
    }
  }
},
```
I think your issue could from `chimeOnFinish`. By default, after detection, Hotword would play some ding sound, And almost simultaneously AMK2 would try to also it's own beep. Both sound output might be collided so that error comes. Unless you set proper ALSA sound mixing, default ALSA couldn't play multi-sourced sound streams together. To fix, 1) set proper ALSA mixing (Sorry, it is out of my help) or 2) avoid sound collision by `chimeOnFinish:false`.
Anyway, Why are you using "jarvis"? You've set only "computer" command, so when you say "jarvis", nothing could be happend.

**Comment by JohnB7777** [comment]
Ok, I will try this.

I say Jarvis because I want to use this hotword. But I see my mistake : if I'm not wrong, I have to replace "computer" by "jarvis" in "commands: {", right ?

Thanks again !

**Comment by eouia** [comment]
Yes. change command name as your model's `hotwords`. (If you want to activate command with `jarvis`, change the command name with `jarvis`.)

**Comment by eouia** [comment]
Of course, to use "jarvis", You need to add "jarvis" model also.

**Comment by JohnB7777** [comment]
Ok, I change my config and it work ! :D

I'm very happy, but there are two things I want to change :
First, the sound comes out the screen instead of my speakers and I don't understand why (maybe I a have to modify alsa or raspi-config ?)
Second, I would like that google assistant display information at the bottom of the screen (text, images ...). I saw it's possible in a video on youtube.

And also, when google assistant talk, there is something displayed on the top of my screen (a little windows where I can read "Try to read").

**Comment by eouia** [comment]
For the first issue... I think you've set your sound output to HDMI. (Or it might be default of Raspbian Stretch)

For the Second(and third) issue... change position of MMM-AssisntantMk2. There is annoying bug on center region. Sorry, it will be fixed on next major updates.

**Comment by JohnB7777** [comment]
I haven't tested the first issue, but the second works !
And, don't be sorry about the position of the module, your work is really amazing !

I have something else to ask : I ask to Jarvis the weather for this weekend and the display was very short. Is there a way for it to stay longer?

**Comment by eouia** [comment]
that is hardcoded in screenoutput itself by google. my next update will solve that. but not possible with this version.

**Comment by JohnB7777** [comment]
Ok, thanks !

Last thing (for now :P) : do you had some advices with the use of your module, like how to "connect" my phone with google assistant (for example : add a task) ?

Again, thanks for your help and I don't want to disturb more !

**Comment by eouia** [comment]
If your assistant works properly, some of default features of Google Assistant (like `add an event to calendar` or `show me shopping list`) will work. But some would be limited or blocked (Alarm, broadcast, news, and Spotify or Youtube playing, etc.) This module is leaning on  Assistant for device SDK, and purpose of this SDK is not being an alternative real Google Home but giving voicing command functionality to specific device.

**Comment by JohnB7777** [comment]
Ok, thanks !

I have some questions : first, the window (on the bottom) doesn't stay long. And, also, I have a PIR sensor. 
Problem : when google answers to me, it response can disappear if the PIR sensor doesn't detect me. It should give a higher priority to the assistant module so that the PIR sensor turns off the screen if google assistant is'nt active, if you know what I mean.

On another hand, I have a problem with my config file. Magic mirror doesn't want to start. The only things I made was to "//" the position of MMM-Hotwords and kill "TeamViewer" and "teamviewerd" process.
Even restarting the mirror, the problem still there. I don't know if it's linked to MMM-Hotwords but I still talk about it.

Thanks again !

**Comment by eouia** [comment]
First. 
I understand as your PIR's status - nobody here, so turning off screen - is preventing showing screenOutput. Sorry, that could be done AMK2 module itself. Your PIR's job. Anyway, if you need, you can "turn on"(I don't know, because I don't know which method PIR could turn off screen by) screen when Assistant is activated. (You can use ASSISTANT_ACTIVATED notification)

Second, If you don't want to show MMM-Hotword, use `useDisplay:false`, instead removing the position.

**Comment by JohnB7777** [comment]
Hello,

I'm back now because I had a big problem on my magic mirror (problem of config).
One of my problem is solved but I'm still getting errors (and my screen stay black with no information on it).

WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/electron-v3.0-linux-arm/snowboy.node'
Loading module helpers ...
No helper found for module: alert.
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
No helper found for module: MMM-AirQuality.
Initializing new module helper ...
Module helper loaded: MMM-Tools
Initializing new module helper ...
Module helper loaded: MMM-NetworkScanner
Initializing new module helper ...
Module helper loaded: MMM-EARTH
No helper found for module: MMM-shabbat.
App threw an error during load
Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/electron-v3.0-linux-arm/snowboy.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/index.js:141:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/electron-v3.0-linux-arm/snowboy.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/index.js:141:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

It's weird because I did'nt make any changes on snowboy...

**Comment by eouia** [comment]
I don't know why, but it seems your module broken. remove it and reinstall again.

**Comment by JohnB7777** [comment]
Ok, and what's odd is that my module "MMM" had a big problem too when I didn't touch anything. Very weird ...

**Comment by JohnB7777** [comment]
Hello again,

I have a new problem, always with MMM-Hotword and a new with MMM-AssistantMk2

Module helper loaded: MMM-Hotword
App threw an error during load
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.0-linux-arm-glibc
Found: [electron-v2.0-linux-arm-glibc, node-v57-linux-arm-glibc, node-v64-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node'
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:64:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12)
Whoops! There was an uncaught exception...
{ Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.0-linux-arm-glibc
Found: [electron-v2.0-linux-arm-glibc, node-v57-linux-arm-glibc, node-v64-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node'
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:64:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

I did "npm rebuild" but problems are still here.
Do you think I have to remove & reinstall the modules ?

**Comment by eouia** [comment]
What did you do? It seems AMK2 was re-installed (but not completed). Did you update it? Usually this would happen you did `npm install` or `npm rebuild` on your AMK2 directory. But there was no update to do step nowadays. Did you?
The solution is just to complete installation step again. But... Why and What have you done? (before this error)

**Comment by JohnB7777** [comment]
No, I did absolutely nothing, that's why I'm really surprised !

This is what I done :
Last week, magic mirror was working. But, I wanted to remove the position of MMM-Hotword. So, il remove "position" on the config file and, also, I kill TeamViewer and teamviewerd process (to have free RAM).
After, I start my mirror and black screen : problem on the config file.
So, I reboot my raspberry pi and I put the position but problems were always here.

Like I said on a previous message, I had a problem also on MMM-PIR-Sensor (problem solved), I had to update node.js (I did that yesterday) and now it works perfectly.
I also update Magic Mirror to the latest version (but the errors were already there).
And there are problems on MMM-Hotword and MMM-AssistantMk2.

Nobody else besides me has access to the mirror, so I really don't understand.

**Comment by eouia** [comment]
Now I figure out what happened. 

```
Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.0-linux-arm-glibc
Found: [electron-v2.0-linux-arm-glibc, node-v57-linux-arm-glibc, node-v64-linux-arm-glibc]
```
This means, your MM try to use `electron-v3.0-linux-arm-glibc`, but nothing found. 
There was some hint. :) `Found: [electron-v2.0-linux-arm-glibc, ...` it means your last build was for `Electron V2` (It is some program used in MM to act as desktop application). But not at this moment.
Why? Because you've updated your MM to 2.7.1 which is using `Electron V3`. So, MM needs new files for Electron  V3 instead Electron V2. 
So, you need to do is electron-rebuild again. (I think it might be needed on MMM-Hotword also)

**Comment by JohnB7777** [comment]
Ok, thanks for the explanation, I'm doing this and I'll let you know :)

**Comment by JohnB7777** [comment]
Yes, it works again !!! :D
A big thanks for your help !

**Comment by eouia** [comment]
Nice to hear it. I'll close this issue.
