### ISSUE TITLE
Hotword가 동작하지 않습니다

### ISSUE THREAD

**Issue by nevido** [eouia/MMM-Hotword#46]
모듈삭제하고 git 으로 받고 auto로 설치했습니다

apt-get update부분 생략

기존 화면과 동일하게 나오는데 음성인식이 되지 않습니다

pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ pm2 log
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/pi/.pm2/pm2.log last 15 lines:
PM2        | 2019-05-21T06:24:10: PM2 log: PM2 version          : 3.4.0
PM2        | 2019-05-21T06:24:10: PM2 log: Node.js version      : 10.15.3
PM2        | 2019-05-21T06:24:10: PM2 log: Current arch         : arm
PM2        | 2019-05-21T06:24:10: PM2 log: PM2 home             : /home/pi/.pm2
PM2        | 2019-05-21T06:24:10: PM2 log: PM2 PID file         : /home/pi/.pm2/pm2.pid
PM2        | 2019-05-21T06:24:10: PM2 log: RPC socket file      : /home/pi/.pm2/rpc.sock
PM2        | 2019-05-21T06:24:10: PM2 log: BUS socket file      : /home/pi/.pm2/pub.sock
PM2        | 2019-05-21T06:24:10: PM2 log: Application log path : /home/pi/.pm2/logs
PM2        | 2019-05-21T06:24:10: PM2 log: Process dump file    : /home/pi/.pm2/dump.pm2
PM2        | 2019-05-21T06:24:10: PM2 log: Concurrent actions   : 2
PM2        | 2019-05-21T06:24:10: PM2 log: SIGTERM timeout      : 1600
PM2        | 2019-05-21T06:24:10: PM2 log: ===============================================================================
PM2        | 2019-05-21T06:24:10: PM2 log: [Watch] Start watching MagicMirror
PM2        | 2019-05-21T06:24:10: PM2 log: App [MagicMirror:0] starting in -fork mode-
PM2        | 2019-05-21T06:24:11: PM2 log: App [MagicMirror:0] online

/home/pi/.pm2/logs/MagicMirror-error.log last 15 lines:
0|MagicMir | npm ERR!     /home/pi/.npm/_logs/2019-05-20T21_11_15_870Z-debug.log
0|MagicMir | getrandom indicates that the entropy pool has not been initialized. Rather than continue with poor entropy, this process will block until entropy is available.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | npm ERR! code ELIFECYCLE
0|MagicMir | npm ERR! errno 1
0|MagicMir | npm ERR! magicmirror@2.7.1 start: `sh run-start.sh`
0|MagicMir | npm ERR! Exit status 1
0|MagicMir | npm ERR!
0|MagicMir | npm ERR! Failed at the magicmirror@2.7.1 start script.
0|MagicMir | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
0|MagicMir |
0|MagicMir | npm ERR! A complete log of this run can be found in:
0|MagicMir | npm ERR!     /home/pi/.npm/_logs/2019-05-20T21_23_48_693Z-debug.log
0|MagicMir | getrandom indicates that the entropy pool has not been initialized. Rather than continue with poor entropy, this process will block until entropy is available.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.

/home/pi/.pm2/logs/MagicMirror-out.log last 15 lines:
0|MagicMir | Connecting socket for: calendar
0|MagicMir | Starting node helper for: calendar
0|MagicMir | Connecting socket for: newsfeed
0|MagicMir | Starting module: newsfeed
0|MagicMir | Connecting socket for: MMM-NotificationTrigger
0|MagicMir | Connecting socket for: MMM-Hotword
0|MagicMir | [HOTWORD] MMM-Hotword starts
0|MagicMir | Connecting socket for: MMM-AssistantMk2
0|MagicMir | Sockets connected & modules started ...
0|MagicMir | Launching application.
0|MagicMir | Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/ko.south_korea%23holiday%40group.v.calendar.google.com/public/basic.ics - Interval: 3600000
0|MagicMir | Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/jy2lee%40gmail.com/private-5070d7b7605516a43d3f2191fcfb2e01/basic.ics - Interval: 3600000
0|MagicMir | Create new calendar fetcher for url: https://calendar.google.com/calendar/htmlembed?src=%23contacts%40group.v.calendar.google.com&ctz=Asia%2FSeoul - Interval: 3600000
0|MagicMir | Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/m6jq0qt104fatk56lnnne9qul4%40group.calendar.google.com/public/basic.ics - Interval: 3600000
0|MagicMir | Create new news fetcher for url: http://fs.jtbc.joins.com/RSS/newsflash.xml - Interval: 300000

**Comment by eouia** [comment]
config도 다시 작성해주셔야 해요. 구조가 많이 바뀌어서.

**Comment by eouia** [comment]
일단 복잡하니까, MMM-Hotword와 MMM-AssistantMK2 만 남겨놓고 다른 모듈은 빼고 테스트해주세요. 정작 필요한 로그는 안보여요.. ^^; pm2 쓰고 계신다면 스톱하시고 `npm start dev`로 실행하시면 실시간으로 상세 로그가 나옵니다. 그리고, config을 어떻게 하셨는지 저한테 보내주세요. (eouia0819@gmail.com)

**Comment by nevido** [comment]
config 보내드렸습니다
npm start dev 에선 아래와같이 나옵니다

![image](https://user-images.githubusercontent.com/25813260/58173639-d5017980-7cd6-11e9-96d7-6dab34a79ea1.png)

**Comment by eouia** [comment]
config 보니까 Hotword 가 1.1 버전인 것 같은데 맞나요? 2일전이면 이미 2.0이 릴리즈 된 후라서, 2.0 설치하신 것 같은데요.

**Comment by nevido** [comment]
hotword는 모둘 삭제후 새로 설치했습니다

1.1과 2.0이 config에서 path변경말고 수정해야하는게
있나요

참고할만한 정보나 경로 부탁드립니다


나의 iPhone에서 보냄

2019. 5. 23. 오전 1:03, Seongnoh Sean Yi <notifications@github.com> 작성:

**Comment by eouia** [comment]
많이 다른데요..
https://github.com/eouia/MMM-Hotword/blob/master/README.md

https://github.com/eouia/MMM-Hotword/tree/master/documents

**Comment by nevido** [comment]
감사합니다

퇴근후. 모둘 부분 수정해보겠습다

https://github.com/eouia/MMM-Hotword/blob/master/documents/config.md

위이걸로 해볼려구요. 감사합니다

나의 iPhone에서 보냄

2019. 5. 23. 오전 6:54, Seongnoh Sean Yi <notifications@github.com> 작성:

**Comment by nevido** [comment]
models: [
      {
        hotwords    : "computer",
        file        : "computer.umdl",
        sensitivity : "0.5",
      },
    ], 
이부분이 기존에는 그냥 경로로만 되어 있었는데 models배열로 추가 되어 있어서...찾질 못한거 같습니다
수정후 정상 동작을 합니다.
한가지 문제는 음성 인식후에 응답(동작)을 하는데 응답 문구를 다 읽기도 전에 끝나버립니다
예로 오늘 날씨 알려줘.. 이렇게 질의를 하면
오늘 ~ 날씨는 화장하겠습니다.. 그리고...(여기서 끝나버립니다)

어느 부분을 수정해야할까요? 답변 시간을 좀 더 길게 하는 방법이 없나요?

**Comment by nevido** [comment]
config에  hotword랑  asssitantmk2 두개만 남기도 다 지운후 테스트를 했는데
음성이 맨 끝 한구절이 여전히 끊기네요..

**Comment by eouia** [comment]
휴일이라 컴 앞에 없어서 바로 답변드리기는 어렵구요, 짚이는 부분은 있는데 테스트해보고 답변드릴게요

**Comment by eouia** [comment]
혹시 메일로도 질문을 주셨던가요? 요즘 하도 여러분들한테 질문이 여러 채널로 들어와서요. 답변이 늦었습니다.
1) 음성출력부분을 혹시 HDMI를 사용하시나요? HDMI 출력의 경우 디스플레이의 컨트롤러에 따라 스트림 오픈과 클로즈 타이밍이 안맞는 경우가 있습니다. 다른 채널 (Analog output) 등으로 테스트해보세요.
2) `mpg321`  대신 `mpg123`이라든가 `mxplayer` 같은 다른 mp3 플레이 프로그램을 설치하셔서 그걸로 출력 프로그램을 바꿔보세요.
사실 이 두가지 말고는 딱히 다른 부분에서의 문제일 것 같지는 않습니다.

**Comment by eouia** [comment]
mpg321을 다시 설치하시면 해결될겁니다. 이미 여러 다른 분들이랑 테스트해봤는데, mpg321 버전이 낮은 경우 그런 현상이 있는 것 같네요.
