### ISSUE TITLE
 저도 Hotword가 동작안합니다. config파일 어느부분을 수정해야할까요?

### ISSUE THREAD

**Issue by MagicM19** [eouia/MMM-Hotword#47]
`var config = {

  address: "localhost",

  port: 8080,

  ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],

  language: "ko",

  timeFormat: 12,

  units: "metric",

 

  modules: [{

      module: "alert",

    },

    {

      module: "updatenotification",

      position: "top_bar"

    },

    {

      module: "clock",

      position: "top_left",

      config: {

        dateFormat: "LL dddd",

      }

    },

    {

      module: "calendar",

      position: "top_left",

      config: {

        urgency: 21,

        fetchInterval: 3600000,

        calendars: [{

          url: 'https://calendar.google.com/calendar/ical/ko.south_korea%23holiday%40group.v.calendar.google.com/public/basic.ics',

          symbol: '대한민국 공휴일', 

        }, ]

      }

    },

    {

      module: "currentweather",

      position: "top_right",

      config: {

        location: "JeonJu, KR", //https://openweathermap.org/ 에서 지역을 찾으세요.

        locationID: "",

        appid: "53cc854cd3ad8941f74f5297ada3b4e5" //openweathermap.org의 API key를 입력하세요.

      }

    },

    {

      module: "weatherforecast",

      position: "top_right",

      config: {

        location: "JeonJu, KR", //https://openweathermap.org/ 에서 지역을 찾으세요.

        locationID: "",

        appid: "53cc854cd3ad8941f74f5297ada3b4e5" //openweathermap.org의 API key를 입력하세요.

      }

    },

    {

   module: "MMM-NotificationTrigger",

   config:

   {

    useWebhook: true,

    triggers:

    [

    {

     trigger: "ASSISTANT_ACTION",

     triggerSenderFilter: function (sender)

     {

      if (sender.name == "MMM-AssistantMk2")

      {

       return true;

      }

      else

      {

       return false;

      }

     },

     triggerPayloadFilter: function (payload)

     {

      return true;

     },

     fires: [{

      fire: "SHOW_ALERT",

      payload: function (payload)

      {

       return {

        type: "notification",

        title: payload[0].execution[0].type,

        message: payload[0].execution[0].command

       };

      },

     }, ],

    },

    {

     trigger: "ASSISTANT_HOOK",

     fires: [{

     fire: "SHOW_ALERT",

     payload: function (payload)

     {

      return {

       title: "HOOK",

       message: "Are you saying " + payload.hook + "?",

       timer: 5000

      };

     },

     }, ],

    },

    {

     trigger: "HOTWORD_DETECTED",

     fires: [{

      fire: "HOTWORD_PAUSE"

      },

      {

      fire: "ASSISTANT_ACTIVATE",

      payload: function (payload) {

       return {

       "profile": payload.hotword

       };

      },

      delay: 200

      },

     ]

    },

    {

     trigger: "ASSISTANT_DEACTIVATED",

     fires: [{

      fire: "HOTWORD_RESUME"

     }]

    },

    ]

   }

  },

 {

      module: "MMM-Hotword",

      config: {

        snowboy: [

          {

            hotwords: "smartmirror",

            file: "resources/models/smart_mirror.umdl",

            sensitivity: '1.0',

          },

          {

            hotwords: "snowboy",

            file: "resources/models/snowboy.umdl",

            sensitivity: '1.0',

          },

          {

            file: 'resources/models/jarvis.umdl',

            sensitivity: '0.8,0.80',

            hotwords: ['jarvis', 'jarvis']

          }

        ],

        record: {

          recordProgram : "arecord",  

          device        : "plughw:1",

        },

        autostart:true,

        onDetected: {

          notification: function (payload) {

            return "ASSISTANT_ACTIVATE"

          },

          payload: function (payload){

            return {

              profile: payload.hotword

            }

          }

        },

      },

    },

 {

  module: "MMM-AssistantMk2",

  position: "top_center",

  config: {

 

    // --- ESSENTIALS / modifying for your environment might be needed.

 

 

    deviceLocation: {

      coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)

        latitude: 47.809490, // -90.0 - +90.0

        longitude: 13.055010, // -180.0 - +180.0

      },

    },

 

    defaultProfile: "default", // If you have several profiles and want to set one of them as default profile, describe here.

 

    profiles: {

      "default" : { // profile name.

        profileFile: "default.json", // profile file name.

        lang: "ko-KR"

        //currently available (estimation, not all tested):

        //  de-DE, en-AU, en-CA, en-GB, en-US, en-IN

        // fr-CA, fr-FR, it-IT, ja-JP, es-ES, es-MX, ko-KR, pt-BR

        // https://developers.google.com/assistant/sdk/reference/rpc/languages

      },

      /* Add your other profiles here, if exists.

      "other_profile" : {

        profileFile: "other.json",

        lang: "ko-KR"

      }

      */

    },

 

    record: { // Full values are in `FOR EXPERTS` section.

      recordProgram: "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"

      device: null        // recording device (e.g.: "plughw:1")

    },

 

    play: { // Full values are in `FOR EXPERTS` section.

      playProgram: "mpg321", // recommended.

    },

 

 

    // --- OPTIONAL / not important but customizable for your usage

 

 

    responseVoice: true, // If available, Assistant will response with her voice.

    responseScreen: true, // If available, Assistant will response with some rendered HTML

    responseAlert: true, // If available, Assistant will response with Alert module of MM

    // Sometimes, any response might not be returned. responseAlert is useful for displaying error.

 

    screenZoom: "80%", // Adjust responseScreen to your mirror size.

    screenDuration: 2000, // milliseconds. How long responseScreen will be shown after speech.

    //If you set 0, Screen Output will be closed after Response speech finishes ASAP.

 

    youtubeAutoplay: true, //If set as true, found Youtube video will be played automatically.

    pauseOnYoutube:false, //If set as true, You cannot activate Assistant during youtube playing. Recommended for the performance (Because permanent hotword detecting might make performance lower)

 

    useWelcomeMessage: "", //Try "brief today" as this value. You can use this value to check module working when MM is starting.

 

    onIdle: {

      timer: 1000*60*30, // if you don't want to use this feature, just set timer as `0` or command as ""

      command: "HIDEMODULES"

    },

 

    onActivate: {

      timer: 0,

      command: "SHOWMODULES"

    },

 

 

    // --- FOR EXPERTS / For development, debug or more

 

 

    verbose:false, // You can get error or some logs when this value is set as true.

 

    startChime: "connection.mp3", // you can use `mp3` to play chime when your mic is ready. It should be playable with your `play.playProgram`

    noChimeOnSay: false, // When using the `ASSISTANT_SAY` trigger, you can prevent the chime from being played before your words

 

    auth: { // I believe you don't need to change this.

      keyFilePath: "./credentials.json"

    },

 

    record:  { // Full version

      sampleRate    : 16000,      // audio sample rate

      threshold     : 0.5,        // silence threshold (rec only)

      thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)

      thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)

      silence       : 1.0,        // seconds of silence before ending

      verbose       : false,      // log info to the console

      recordProgram : "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"

      device        : null        // recording device (e.g.: "plughw:1")

    },

 

    play: { // Full version

      encodingOut: "MP3", //'MP3' or 'WAV' is available, but you might not need to modify this.

      sampleRateOut: 24000,

      playProgram: "mpg321", //Your prefer sound play program. By example, if you are running this on OSX, `afplay` could be available.

      playOption: [],

      // If you need additional options to use playProgram, describe here. (except filename)

      // e.g: ["-d", "", "-t", "100"]

    },

 

    useGactionCLI: false, // If set as true, you can update your gAction when MM is rebooted.

    projectId: "", // Google Assistant ProjectId (Required only when you use gAction.)

    deviceModelId: "", // It should be described in your config.json. In most of case, you don't need to this.

    deviceInstanceId: "", // It should be described in your config.json. In most of case, you don't need to this.

 

    action:{}, // You can catch your gAction command.

 

    transcriptionHook: {}, // You can catch transcription hook and be able to make your own `COMMAND` with this.

    //See the `transcriptionHook` section.

 

    command: {}, // You can make your own MM command for gAction and transcriptionHook

    //See the `command` section.

    record: {

        recordProgram : "arecord",  

        device        : "plughw:1",

      },

 

      notifications: {

        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",

        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",

      },

	

    notifications: { // You can redefine these notifications to communicate with specific modules.

      ASSISTANT_ACTIVATE: "ASSISTANT_ACTIVATE",

      ASSISTANT_DEACTIVATE: "ASSISTANT_CLEAR",

      ASSISTANT_ACTIVATED: "ASSISTANT_ACTIVATED",

      ASSISTANT_DEACTIVATED: "ASSISTANT_DEACTIVATED",

      ASSISTANT_ACTION: "ASSISTANT_ACTION",

      ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",     

      ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",      

      DEFAULT_HOOK_NOTIFICATION: "ASSISTANT_HOOK",

      TEXT_QUERY: "ASSISTANT_QUERY",

      SAY_TEXT: "ASSISTANT_SAY",

    }

  }

  },

  ]

};

 

/*************** DO NOT EDIT THE LINE BELOW ***************/

if (typeof module !== "undefined") {

  module.exports = config;

}`
안녕하세요 
질문전에 만들어주신 모듈 덕분에 아주 유용하게 사용하고있습니다. 
감사합니다. 
새로 Hotword를 최신버전으로 다시 받아서 사용하려고 하는데 Keyword를 아무리 불러도 반응이 없습니다. 밑에 답변을 확인해보니 config파일을 수정해야한다고 답변주셨는데  
어느부분을 고쳐야 할까요??

**Comment by eouia** [comment]
전부요...
https://github.com/eouia/MMM-Hotword/tree/master/documents

**Comment by MagicM19** [comment]
정말 감사합니다 덕분에 해결됬어요
