### ISSUE TITLE
Cannot record training samples

### ISSUE THREAD

**Issue by ivanovd** [eouia/MMM-Hotword#48]
I followed the training guide but here is the error that I get:
```
pi@raspberrypi:~ $ rec -r 16000 -c 1 -b 16 -e signed-integer 1.wav
rec FAIL formats: can't open input  `default': snd_pcm_open error: No such file or directory
```

**Comment by eouia** [comment]
maybe your mic is not default sound-input device of RPI (due to your ALSA configuration)
You can use `arecord` instead. https://linux.die.net/man/1/arecord

**Comment by ivanovd** [comment]
It worked :) Whover has the ReSpeaker 2-Mics Pi HAT can use the below commands: 
```
arecord -r16000 -f S16_LE -c2 -Dhw:1 1.wav
arecord -r16000 -f S16_LE -c2 -Dhw:1 2.wav
arecord -r16000 -f S16_LE -c2 -Dhw:1 3.wav
```

Thanks eouia and keep up the great work you are doing!
