### ISSUE TITLE
에러 및 사용법 질문드립니다

### ISSUE THREAD

**Issue by ddoong** [eouia/MMM-Hotword#51]
영어를 잘하는 편이 아니라 최대한 번역기로해서 보면서 했는데 부족한부분이 많은듯합니다.ㅠㅠ

첫째로 아래처럼 결과가 나오는게 정상적으로 작동되는게 맞는지 궁금합니다.
일단 config.md에 있는 example로 이용해서 실행했습니다.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Detected: computer
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'computer', file: null }
Speaker error: 1
Whoops! There was an uncaught exception...
1

두번째는 trainer.md 처럼 하던 과정에서

rec -r 16000 -c 1 -b 16 -e signed-integer 1.wav을 실행하면
ALSA lib bluealsa-pcm.c:680:(_snd_pcm_bluealsa_open) Couldn't get BlueALSA transport: No such device
rec FAIL formats: can't open input  `default': snd_pcm_open error: No such device
위 에러가 나옵니다.  스피커와 마이크는 assistantMk2 설치해서 확인 할 때 작동은 잘 되고 있습니다.
어떻게 해야되는지 알수있을까요?

세번째는 제가 hotword를 이용해서 모든 모듈을 숨기고 youtube 모듈을 보여주는 걸 만들 예정이고, 또 page(1~3)를 이동하는 걸 하려고하는데 .pmdl을 만들고 command만 config에 입력하면 되는건가요?

**Comment by eouia** [comment]
스피커 충돌오류인 것 같은데 혹시 AssistantMk2 모듈을 같이 쓰고 계신가요? 그렇다면 `chimeOnFinish:null` 을 Hotword config에 추가해주세요.

그런데, 두번째 질문을 보자니, 뭔가 사운드 셋업이 안맞는 것 같습니다. default 사운드 입력 장치가 현재 마이크로 되어 있지 않은 것 같아요. rec 명령을 할 때 device를 지정해주시면 될 것 같습니다. 

세번째는.. 일단은 그렇습니다.

**Comment by ddoong** [comment]
아아 Mk2 모듈이랑 같이 써보려했는데 hotword만 이용해도될듯해서 모듈에서 제외하기로했어요
답변감사합니다 확인해볼게요!!
