### ISSUE TITLE
안녕하세요 에러 수정 방안을 몰라서 여쭙니다..!

### ISSUE THREAD

**Issue by hannam12** [eouia/MMM-Hotword#52]
4월초 쯤에 처음 만들었을때는 문제없이 실행이 잘되었는데요.

이번주에 스마트미러를 새로 또 만드는데 hotword가 업데이트가 되어서인지  configure파일 로드부분에 에러가 발생해 MagicMirror 창이 아예 안떳습니다.
확인해보니 configuere부분 수정하라길래 READme 파일을 보고 configure파일을 수정해서 MagicMirror 창까지는 띄웠는데 마이크 인식이 안되는지 어시스턴트가 반응을 안합니다.

혹시 configure파일 말고 추가로 수정해야하는 부분이 있는지와 assistantMK2내 파일에도 변동사항 있는지 궁금합니다!

**Comment by eouia** [comment]
MMM-AssistantMk2는 특별히 건드리실 건 없습니다. Hotword는 업데이트 된 후 많이 바뀌었으니 설치부터 다시 한번 살펴보세요. 로그를 주시면 뭐가 문제인지 살펴보겠습니다.

**Comment by hannam12** [comment]
1. error : GET http://localhost:8080/modules/MMM-Hotword/null 404 (Not Found) 
2. error : [HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }


------------------------------------------------------------------------------------------------------
modified parts
1. (MMM-Hotword.js)
mic: {
            recordProgram: **"arecord"**, //record prgram, `rec`, `arecord`, `sox`, `parec` is available
            **device: "Realtek Semiconductor Corp",**
            sampleRate: 16000, // audio sample rate
            channels: 1, // number of channels
            threshold: 0.5,
            thresholdStart: null,
            thresholdEnd: null,
            silence: '1.0',
            verbose: false, // log info to the console
        },




2.(configure.js)
{
      module: "MMM-AssistantMk2",
      position: "top_right",
      config: {
	verbose: true,
        record: {
          recordProgram : **"arecord",**  
          device        : **"Realtek Semiconductor Corp",**
        },
        notifications: {
          ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
          ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
        },
        deviceLocation: {
          coordinates: {
            latitude: 37.57,
            longitude: 126.98
          }
        },
        profiles: {
          "default": {
           lang: "ko-KR"
          }
        }
      }
    },
    {
  module: "MMM-Hotword",
  position: "top_right",
  config: {
	testMic: true,
	chimeOnFinish: null,
    mic: {
      recordProgram: **"arecord",**
      device: **"Realtek Semiconductor Corp"**
    },
    models: [
      {
        hotwords    : "snowboy",
        file        : "snowboy.umdl",
        sensitivity : "0.5",
      },
    ],
    commands: {
      "snowboy": {
        notificationExec: {
          notification: "ASSISTANT_ACTIVATE",
          payload: (detected, afterRecord) => {
            return {profile:"default"}
          }
        },
        restart:false,
        afterRecordLimit:0
      }
    }
  }
},




3. (MMM-AssistantMK2)
record: {
      sampleRate    : 16000,      // audio sample rate
      threshold     : 0.5,        // silence threshold (rec only)
      thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
      thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
      silence       : 1.0,        // seconds of silence before ending
      verbose       : false,      // log info to the console
      recordProgram : **"arecord"**,  // Defaults to "arecord" - also supports "rec" and "sox"
      device        : **"Realtek Semiconductor Corp"** ,       // recording device (e.g.: "plughw:1")
    },

**Comment by eouia** [comment]
일단 device 이름이 틀린 것 같네요.
`arecrod -l` 하시면 현재 연결된 USB 마이크 목록이 나올 거에요.
보통 card:X, device:X 형태로 표현되고, 그러면 그걸 "plughw:1,0" 이런 식으로 device 이름이 결정되거든요.
ALSA 셋업을 따로 안하셨다면 그걸로 충분할 겁니다.

**Comment by eouia** [comment]
그리고, 사용자가 수정할 파일은 `config.js` 말고는 없어요. (CSS건드리실거면 `css/custom.css`도). 각 모듈의 원본 소스는 원상태로 돌리세요.

**Comment by hannam12** [comment]
MMM-Hotword.js:14 Uncaught SyntaxError: Unexpected identifier

**Comment by hannam12** [comment]
디바이스 다시 원래대로 수정하였는데 위와 같은 에러가 뜹니다...

**Comment by hannam12** [comment]
chimeOnFinish: null,

그리고 이부분은 저희가 삭제 했는데 상관없나요??? 콘솔창에서 이부분 에러 발생으로 지웠는데 에러가 제거되더라고요

**Comment by eouia** [comment]
? 뭘 어떻게 바꾸셨죠? MMM-Hotword.js 의 14라인 가면 문법 오류가 있을거에요. 그 윗줄에 , 를 안달았다거나 뭐 그런 류...

**Comment by hannam12** [comment]
plughw는 1,0 으로 나와서 말씀대로 "plughw:1,0" 으로 수정하였고 마지막에 코멘트 달은 오류같은 경우는 13번줄 마지막에 , 생략되어 다시 추가했습니다.

다만 오류는 안나오는데  콘솔창에서 마이크 입력값을 못받는지 로그가 안뜹니다...

**Comment by eouia** [comment]
로그를 보여주세요.

**Comment by hannam12** [comment]
로그 자체에 에러는 저희가 weater 앱부분에 API값 안넣어서 나온 에러말고는 검출이 안됫습니다

**Comment by hannam12** [comment]
그리고 마이크로 음성 입력 넣어줬을때는 추가로 로그가 발생하지 않았습니다

**Comment by eouia** [comment]
음.. 테스트를 간단히 하려면 다른 모듈들은 전부 disable하고 문제되는 모듈에만 집중하는 게 좋습니다. 일단 HOTWORD빼고 다른 모듈은 전부 disable 하거나 comment out 해주세요.
그다음, 주신 로그는 프론트 엔드 로그인데요, 백엔드 로그를 보여주세요.

**Comment by hannam12** [comment]
백엔드 로그가 cmd창 맞나요? 우선 매직미러 실행후 나오는 로그 cmd창에 나온거 올려드렸습니다

**Comment by eouia** [comment]
[HOTWORD] Detector starts listening.

이게 나오고 있으면 HOTWORD가 듣고 있는 거니까 "snowboy"를 말해서 제대로 잡히는지 확인해보시면 됩니다.

만약 마이크 자체의 동작이 의심스럽다면,
```js
mic : {
  verbose:true,
  ...
```
처럼 verbose:true 를 추가하시면 mic 동작 관련 로그가 나올 겁니다.

**Comment by hannam12** [comment]
Initializing MagicMirror.
translator.js:206 Configured language not found in core translations.
translator.js:224 Loading core translation fallback file: translations/en.json
loader.js:182 Load script: modules/MMM-Hotword//MMM-Hotword.js
module.js:477 Module registered: MMM-Hotword
loader.js:152 Bootstrapping module: MMM-Hotword
loader.js:182 Load script: https://code.iconify.design/1/1.0.2/iconify.min.js
loader.js:157 Scripts loaded for: MMM-Hotword
loader.js:197 Load stylesheet: modules/MMM-Hotword/MMM-Hotword.css
loader.js:159 Styles loaded for: MMM-Hotword
loader.js:161 Translations loaded for: MMM-Hotword
loader.js:197 Load stylesheet: css/custom.css
main.js:472 All modules started!
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:127 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
    protocols.This exposes users of this app to unnecessary security risks.
    Consider loading the following resources over HTTPS or FTPS. 
 - http://localhost:8080/css/main.css
- http://localhost:8080/fonts/roboto.css
- http://localhost:8080/socket.io/socket.io.js
- http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://localhost:8080/js/defaults.js
- http://localhost:8080/config/config.js
- http://localhost:8080/vendor/vendor.js
- http://localhost:8080/modules/default/defaultmodules.js
- http://localhost:8080/js/logger.js
- http://localhost:8080/translations/translations.js
- http://localhost:8080/js/translator.js
- http://localhost:8080/js/class.js
- http://localhost:8080/js/module.js
- http://localhost:8080/js/loader.js
- http://localhost:8080/js/socketclient.js
- http://localhost:8080/js/main.js
- http://localhost:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://localhost:8080/translations/en.json
- http://localhost:8080/modules/MMM-Hotword//MMM-Hotword.js
- http://localhost:8080/modules/MMM-Hotword/MMM-Hotword.css
- http://localhost:8080/css/custom.css
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=Mi3yhYz
- http://localhost:8080/modules/MMM-Hotword/resources/ding.wav
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=Mi3yhau&sid=6u2LUvZRC75X2BTIAAAA
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=Mi3yhb4&sid=6u2LUvZRC75X2BTIAAAA
    
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureResources @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:127
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:184 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
      Policy set or a policy with "unsafe-eval" enabled. This exposes users of
      this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureCSP @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:184
//
Starting MagicMirror: v2.7.1
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Sockets connected & modules started ...
Launching application.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
Shutting down server...
Stopping module helper: MMM-Hotword

**Comment by hannam12** [comment]
매직미러 창내에서 snowboy라고 하였는데 반응이 없습니다. 마이크 테스트후 다시 올려드리겟습니다

**Comment by hannam12** [comment]
Starting MagicMirror: v2.7.1
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Sockets connected & modules started ...
Launching application.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD:LPCM16] Start listening 1 channels with sample rate 16000
[HOTWORD:LPCM16] Listening 44 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
[HOTWORD:LPCM16] Listening 8000 bytes
Shutting down server...
Stopping module helper: MMM-Hotword

**Comment by eouia** [comment]
mic도 제대로 동작하고 있구요... 음.. snowboy 발음 문제이신 듯...

**Comment by hannam12** [comment]
Hotword.js       
 mic: {
            recordProgram: "arecord", //record prgram, `rec`, `arecord`, `sox`, `parec` is available
            device: "plughw:1,0",
            sampleRate: 16000, // audio sample rate
            channels: 1, // number of channels
            threshold: 0.5,
            thresholdStart: null,
            thresholdEnd: null,
            silence: '1.0',
            verbose: false, // log info to the console
        },
        rec
//

MMM-Hotword.js:199 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

**Comment by hannam12** [comment]
위에부분은 MMM-Hotword.js 인데  mic: 부분을 rec>arecord로 변경해주니 인식하였습니다. 

다만 snowboy 인식시 프론트 로그에서 아래와 같은 에러가 발생했습니다

**Comment by eouia** [comment]
원본 소스 안고치시는게 좋을텐데요..
그리고 저건 `chimeOnFinish:null`로 두시거나, 인스톨 문서 보면 HTML5 autoplay enable 하라고 했는데 못보신 듯.

**Comment by eouia** [comment]
사용자가 손댈 수 있는 파일은 config.js뿐입니다. 모듈 원본 고치실 필요 없고, 해당 부분은 config.js에서 수정하시면 되요.

**Comment by eouia** [comment]
그리고 Raspberry Pi에서 arecord가 더 낫다고 문서에도 이미 써놨구요..
_
<img width="934" alt="te" src="https://user-images.githubusercontent.com/1720610/58570880-08915600-8239-11e9-98e4-aa270a9a9e84.png">
_

**Comment by hannam12** [comment]
말씀대로 chimeOnFinish:null 지웠던거 다시 복구 시켰더니 정상작동합니다 !!
귀찮으셨을텐데 정말 감사합니다

Hotword.js 내에 mic: 부분이 rec로 기본설정이 되있던거였어서.. arecord로 바꿨더니 되었습니다..!

**Comment by eouia** [comment]
잘되었네요.
