### ISSUE TITLE
[HOTWORD] No model to load 이런 말이 뜨며 마이크와 스피커 인식이 않됩니다.ㅠ.ㅠ

### ISSUE THREAD

**Issue by ag3319** [eouia/MMM-Hotword#54]
실행후 뜨는 내용의 전문은
pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.7.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.7.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
No helper found for module: compliments.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/ko.south_korea%23holiday%40group.v.calendar.google.com/public/basic.ics - Interval: 3600000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] No model to load

이렇습니다.

config 파일은

var config = {
  address: "localhost",
  port: 8080,
  ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],
  language: "ko",
  timeFormat: 12,
  units: "metric",

  modules: [
    {
      module: "alert",
    },
    {
      module: "updatenotification",
      position: "top_bar"
    },
    {
      module: "clock",
      position: "top_left",
      config: {
        dateFormat: "LL dddd",
      }
    },
    {
      module: "calendar",
      position: "top_left",
      config: {
        urgency: 21,
        fetchInterval: 3600000,
        calendars: [{
          url: 'https://calendar.google.com/calendar/ical/ko.south_korea%23holiday%40group.v.calendar.google.com/public/basic.ics',
          symbol: '대한민국 공휴일',
        }, ]
      }
    },
    {
      module: "currentweather",
      position: "top_right",
      config: {
        location: "Mokpo, KR", //https://openweathermap.org/ 에서 지역을 찾으세요.
        locationID: "",
        appid: "xxxxxxxxxxxxxxxxxxxxxxxxxx" //openweathermap.org의 API key를 입력하세요.
      }
    },
    {
      module: "weatherforecast",
      position: "top_right",
      config: {
        location: "Mokpo, KR", //https://openweathermap.org/ 에서 지역을 찾으세요.
        locationID: "",
        appid: "xxxxxxxxxxxxxxxxx" //openweathermap.org의 API key를 입력하세요.
      }
    },
    {
      module: "compliments",
      position: "lower_third",
      config: {
        compliments: {
          anytime: [ //아무때나
            "오늘도 좋은 하루!"
          ],
          morning: [ //아침
            "좋은 아침!",
            "힘찬 아침!",
            "잘 잤나요?"
          ],
          afternoon: [ //오후
            "안녕하세요!",
            "멋져요!",
            "잘 지내고 있나요!"
          ],
          evening: [ //저녁
            "와우! 잘 지냈나요?",
            "멋져보이네요!",
            "반가워요!"
          ],
          day_sunny: [//맑은 낮
            
          ],
          day_cloudy: [//흐린 낮
            
          ],
          cloudy: [//흐림

          ],
          cloudy_windy: [//흐리고 바람

          ],
          showers: [//소나기

          ],
          rain: [//비

          ],
          thunderstorm: [//천둥번개

          ],
          snow: [//눈

          ],
          fog: [//안개

          ],
          night_clear: [//맑은 밤

          ],
          night_cloudy: [//흐린 밤

          ],
          night_showers: [//소나기 밤

          ],
          night_rain: [//비오는 밤

          ],
          night_thunderstorm: [//천둥번개 밤

          ],
          night_snow: [//눈오는 밤

          ],
          night_alt_cloudy_windy: [//흐리고 바람부는 밤

          ],
        }
      }
    },
    {
      module: "MMM-AssistantMk2",
      position: "top_right",
      config: {
        record: {
          recordProgram : "arecord",  
          device        : "plughw:1",
        },
        notifications: {
          ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
          ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
        },
        deviceLocation: {
          coordinates: {
            latitude: 37.57,
            longitude: 126.98
          }
        },
        profiles: {
          "default": {
           lang: "ko-KR"
          }
        }
      }
    },
    {
      module: "MMM-Hotword",
      config: {
        snowboy: [
          {
            hotwords: "smartmirror",
            file: "models/smart_mirror.umdl",
            sensitivity: '1.0',
          },
          {
            hotwords: "snowboy",
            file: "models/snowboy.umdl",
            sensitivity: '1.0',
          },
          {
            file: 'models/jarvis.umdl',
            sensitivity: '0.8,0.80',
            hotwords: ['jarvis', 'jarvis']
          }
        ],
        record: {
          recordProgram : "arecord",  
          device        : "plughw:1",
        },
        autostart:true,
        onDetected: {
          notification: function (payload) {
            return "ASSISTANT_ACTIVATE"
          },
          payload: function (payload){
            return {
              profile: payload.hotword
            }
          }
        },
      },
    },
  ]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {
  module.exports = config;

이렇게 유튜브를 보고 사용하였는데;;
어머니 선물로 매직미러 화장대를 만들고 싶은데 혹시 어떤 문제 인지 여쭤봐도될까요;??

**Comment by eouia** [comment]
유튜브의 simpteam님 동영상이 옛날 버전이라서, 옛날 버전의 config을 사용하고 계세요.
V2. 로 업데이트 되었으니 MMM-Hotword github repository의 설명대로 새로 설치하고 config도 변경해주세요.

**Comment by ag3319** [comment]
hotword 내용은
MMM-Hotword 구버전(v 1.x.x)이 깔려있다면
구버전 삭제

cd ~/MagicMirror/modules
rm -rf MMM-Hotword

Auto Install 방법

sudo apt update
sudo apt upgrade
sudo apt install libmagic-dev libatlas-base-dev sox libsox-fmt-all

cd ~/MagicMirror/modules
git clone https://github.com/eouia/MMM-Hotword.git
cd MMM-Hotword

chmod +x ./installer/install.sh
./installer/install.sh
이걸보고 바꾸었습니다.
하지만 config는 어느 부분을바꿔야하나요??

**Comment by eouia** [comment]
https://github.com/eouia/MMM-Hotword/tree/master/documents 여기에 관련 도큐먼트들이
있으니 한번씩 읽어보시구요.

config 자체는
https://github.com/eouia/MMM-Hotword/blob/master/documents/config.md#simple-configuration-example
이거
참조하시면 될 겁니다.

**Comment by ag3319** [comment]
혹시 마이크랑 스피커도 이와같이 변경하였는데 상관없나요??
pcm.!default{
	type asym
	playback.pcm
	{
		type hw
		card 0
	}
	capture.pcm
	{
		type hw
		card 0
	}
	capture.pcm
	{
		type hw
		card 1
	}
}
ctl.!default{
	type hw
	card 0
}

**Comment by ag3319** [comment]
정말 감사합니다. 늘 좋은일 가득하세요 ㅎㅎ

**Comment by ji3537** [comment]
염치없이 저도 하나 물어도 될까요?
핫워드에서 아들과 저와 아내가 각기 다른 명령어 입력 가능한가요?

**Comment by eouia** [comment]
@ji3537 일단 여기는 남의 이슈라서, 새로 이슈 세워주세요. 그래야 검색이나 관리가 되니까요.
질문이 모호한데, 예를 들어주시면 이해가 빠를 듯요
