### ISSUE TITLE
마이크 인식이 되지 않습니다.

### ISSUE THREAD

**Issue by amykim0829** [eouia/MMM-Hotword#55]
마이크 모듈설정이랑 다 제대로 된 것 같은데 음성인식도 안되서 버튼 누르면 마이크모양으로 계속바뀌고 CONVERSATION ERROR라고 떠요 ㅠㅠ 혹시 컨피그 파일이 잘 못 된걸까요??

 {
            module: "MMM-AssistantMk2",
            position: "top_right",
            config: {
                record: {
                    recordProgram : "arecord",
                    device        : "plughw:1",
                },
                notifications: {
                    ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
                    ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
                },
            }
            },
        {
            module: "MMM-Hotword",
            config: {
                chimeOnFinish:null,
                mic: {
                    recordProgram : "arecord",
                    device        : "plughw:1",
                },
                models: [
                    {
                        hotwords    : "smart_mirror",
                        file        : "smart_mirror.umdl",
                        sensitivity : "0.5",
                    },
                    {
                        hotwords: "snowboy",
                        file: "snowboy.umdl",
                        sensitivity: "0.5",
                    },
                    {
                        hotwords: ["jarvis", "jarvis"],
                        file: "jarvis.umdl",
                        sensitivity: "0.8,0.8",
                    },
                ],
                defaultCommand: {
                    notificationExec: {
                        notification: "ASSISTANT_ACTIVATE",
                        payload: (detected, afterRecord) => {
                            return {profile:"default"}
                        }
                        },
                    afterRecordLimit:0,
                    restart:false,
                },
            },
        },

어디가 잘 못 됬는지 잘 모르겠어요 ㅠ
main.js:454 Initializing MagicMirror.
    translator.js:206 Configured language not found in core translations.
    translator.js:224 Loading core translation fallback file: translations/en.json
loader.js:182 Load script: modules/default/alert//alert.js
module.js:477 Module registered: alert
loader.js:152 Bootstrapping module: alert
loader.js:182 Load script: modules/default/alert/classie.js
loader.js:182 Load script: modules/default/alert/modernizr.custom.js
loader.js:182 Load script: modules/default/alert/notificationFx.js
loader.js:157 Scripts loaded for: alert
loader.js:197 Load stylesheet: modules/default/alert/ns-default.css
loader.js:197 Load stylesheet: vendor/css/font-awesome.css
loader.js:159 Styles loaded for: alert
translator.js:174 alert - Load translation fallback: translations/en.json
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:127 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
protocols.This exposes users of this app to unnecessary security risks.
    Consider loading the following resources over HTTPS or FTPS.
- http://localhost:8080/css/main.css
- http://localhost:8080/fonts/roboto.css
- http://localhost:8080/socket.io/socket.io.js
- http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://localhost:8080/js/defaults.js
- http://localhost:8080/config/config.js
- http://localhost:8080/vendor/vendor.js
- http://localhost:8080/modules/default/defaultmodules.js
- http://localhost:8080/js/logger.js
- http://localhost:8080/translations/translations.js
- http://localhost:8080/js/translator.js
- http://localhost:8080/js/class.js
- http://localhost:8080/js/module.js
- http://localhost:8080/js/loader.js
- http://localhost:8080/js/socketclient.js
- http://localhost:8080/js/main.js
- http://localhost:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://localhost:8080/translations/en.json
- http://localhost:8080/modules/default/alert//alert.js
- http://localhost:8080/modules/default/alert/classie.js
- http://localhost:8080/modules/default/alert/modernizr.custom.js
- http://localhost:8080/modules/default/alert/notificationFx.js
- http://localhost:8080/modules/default/alert/ns-default.css
- http://localhost:8080/vendor/css/font-awesome.css
- http://localhost:8080/vendor/node_modules/@fortawesome/fontawesome-free/css/all.min.css
- http://localhost:8080/vendor/node_modules/@fortawesome/fontawesome-free/css/v4-shims.min.css

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
    This warning will not show up
once the app is packaged.
    warnAboutInsecureResources @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:127
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:184 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
Policy set or a policy with "unsafe-eval" enabled. This exposes users of
this app to unnecessary security risks.

    For more information and help, consult
https://electronjs.org/docs/tutorial/security.
    This warning will not show up
once the app is packaged.
    warnAboutInsecureCSP @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:184
loader.js:161 Translations loaded for: alert
loader.js:182 Load script: modules/default/updatenotification//updatenotification.js
module.js:477 Module registered: updatenotification
loader.js:152 Bootstrapping module: updatenotification
loader.js:157 Scripts loaded for: updatenotification
loader.js:159 Styles loaded for: updatenotification
loader.js:161 Translations loaded for: updatenotification
loader.js:182 Load script: modules/default/clock//clock.js
module.js:477 Module registered: clock
loader.js:152 Bootstrapping module: clock
loader.js:182 Load script: vendor/node_modules/moment/min/moment-with-locales.js
    loader.js:182 Load script: vendor/node_modules/moment-timezone/builds/moment-timezone-with-data.js
    loader.js:157 Scripts loaded for: clock
loader.js:197 Load stylesheet: modules/default/clock/clock_styles.css
loader.js:159 Styles loaded for: clock
loader.js:161 Translations loaded for: clock
loader.js:182 Load script: modules/default/calendar//calendar.js
module.js:477 Module registered: calendar
loader.js:152 Bootstrapping module: calendar
loader.js:237 File already loaded: moment.js
loader.js:157 Scripts loaded for: calendar
loader.js:197 Load stylesheet: modules/default/calendar/calendar.css
loader.js:237 File already loaded: font-awesome.css
loader.js:159 Styles loaded for: calendar
loader.js:161 Translations loaded for: calendar
loader.js:182 Load script: modules/default/currentweather//currentweather.js
module.js:477 Module registered: currentweather
loader.js:152 Bootstrapping module: currentweather
loader.js:237 File already loaded: moment.js
loader.js:157 Scripts loaded for: currentweather
loader.js:197 Load stylesheet: vendor/node_modules/weathericons/css/weather-icons.css
loader.js:197 Load stylesheet: modules/default/currentweather/currentweather.css
loader.js:159 Styles loaded for: currentweather
loader.js:161 Translations loaded for: currentweather
loader.js:182 Load script: modules/default/weatherforecast//weatherforecast.js
module.js:477 Module registered: weatherforecast
loader.js:152 Bootstrapping module: weatherforecast
loader.js:237 File already loaded: moment.js
loader.js:157 Scripts loaded for: weatherforecast
loader.js:237 File already loaded: weather-icons.css
loader.js:197 Load stylesheet: modules/default/weatherforecast/weatherforecast.css
loader.js:159 Styles loaded for: weatherforecast
loader.js:161 Translations loaded for: weatherforecast
loader.js:182 Load script: modules/default/compliments//compliments.js
module.js:477 Module registered: compliments
loader.js:152 Bootstrapping module: compliments
loader.js:237 File already loaded: moment.js
loader.js:157 Scripts loaded for: compliments
loader.js:159 Styles loaded for: compliments
loader.js:161 Translations loaded for: compliments
loader.js:182 Load script: modules/MMM-AssistantMk2//MMM-AssistantMk2.js
module.js:477 Module registered: MMM-AssistantMk2
loader.js:152 Bootstrapping module: MMM-AssistantMk2
loader.js:182 Load script: modules/MMM-AssistantMk2/vendor/serialize.js
loader.js:157 Scripts loaded for: MMM-AssistantMk2
loader.js:197 Load stylesheet: modules/MMM-AssistantMk2/MMM-AssistantMk2.css
loader.js:159 Styles loaded for: MMM-AssistantMk2
loader.js:161 Translations loaded for: MMM-AssistantMk2
loader.js:182 Load script: modules/MMM-Hotword//MMM-Hotword.js
module.js:477 Module registered: MMM-Hotword
loader.js:152 Bootstrapping module: MMM-Hotword
loader.js:182 Load script: https://code.iconify.design/1/1.0.2/iconify.min.js
    loader.js:157 Scripts loaded for: MMM-Hotword
loader.js:197 Load stylesheet: modules/MMM-Hotword/MMM-Hotword.css
loader.js:159 Styles loaded for: MMM-Hotword
loader.js:161 Translations loaded for: MMM-Hotword
loader.js:197 Load stylesheet: css/custom.css
alert.js:153 Starting module: alert
updatenotification.js:10 Start updatenotification
clock.js:40 Starting module: clock
calendar.js:74 Starting module: calendar
currentweather.js:96 Starting module: currentweather
weatherforecast.js:91 Starting module: weatherforecast
compliments.js:52 Starting module: compliments
main.js:472 All modules started!
    module.js:156 clock received a system notification: ALL_MODULES_STARTED
module.js:156 calendar received a system notification: ALL_MODULES_STARTED
module.js:156 clock received a system notification: MODULE_DOM_CREATED
module.js:156 calendar received a system notification: MODULE_DOM_CREATED
module.js:156 clock received a system notification: DOM_OBJECTS_CREATED
module.js:156 calendar received a system notification: DOM_OBJECTS_CREATED
module.js:198 updatenotification is suspended.
    module.js:198 currentweather is suspended.
    module.js:198 weatherforecast is suspended.
    MMM-Hotword.js:249 Uncaught TypeError: Cannot set property 'innerHTML' of null
at Class.status (MMM-Hotword.js:249)
at Class.socketNotificationReceived (MMM-Hotword.js:149)
at module.js:246
at r.<anonymous> (socketclient.js:25)
at r.emit (index.js:83)
at r.onevent (index.js:83)
at r.MMSocket.self.socket.onevent (socketclient.js:19)
at r.onpacket (index.js:83)
at r.<anonymous> (index.js:83)
at r.emit (index.js:83)
status @ MMM-Hotword.js:249
socketNotificationReceived @ MMM-Hotword.js:149
(anonymous) @ module.js:246
(anonymous) @ socketclient.js:25
r.emit @ index.js:83
r.onevent @ index.js:83
MMSocket.self.socket.onevent @ socketclient.js:19
r.onpacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.ondecoded @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
a.add @ index.js:83
r.ondata @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
r.onData @ index.js:83
ws.onmessage @ index.js:83
module.js:154 clock received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
module.js:154 calendar received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
MMM-AssistantMk2.js:333 [AMK2]  YouTube iframe API is ready.
    module.js:154 clock received a module notification: CALENDAR_EVENTS from sender: calendar
weatherforecast.js:279 GET https://api.openweathermap.org/data/2.5/forecast/daily?q=Seoul,%20KR&units=metric&lang=ko&APPID=abe2eb9f82229c5f66cc056b0656bc3d 401 (Unauthorized)
    updateWeather @ weatherforecast.js:279
(anonymous) @ weatherforecast.js:400
weatherforecast.js:266 weatherforecast: Your AppID does not support long term forecasts. Switching to fallback endpoint.
    weatherRequest.onreadystatechange @ weatherforecast.js:266
XMLHttpRequest.send (async)
updateWeather @ weatherforecast.js:279
(anonymous) @ weatherforecast.js:400
module.js:205 currentweather is resumed.
    module.js:154 clock received a module notification: CURRENTWEATHER_DATA from sender: currentweather
module.js:154 calendar received a module notification: CURRENTWEATHER_DATA from sender: currentweather
module.js:205 weatherforecast is resumed.

**Comment by eouia** [comment]
MMM-Hotword에 position 지정을 안하셨네요.

**Comment by amykim0829** [comment]
지정하고 나서 계속 실행해 보았는데 음성인식을 잘 못해요 ㅠㅠ 로그 보면

GET http://localhost:8080/modules/MMM-Hotword/null 404 (Not Found)

라고 뜹니다.

그리고 또 하나 문제는 구글버튼 터치해도 계속 마이크모양으로만 바뀌어있다가 conversation error라고 뜨는데 그 이유가 뭘까요???

**Comment by eouia** [comment]
`GET http://localhost:8080/modules/MMM-Hotword/null 404 (Not Found)` 이건 상관없구요.

AMK2에서의 Conversation Error 는 대개 마이크가 이미 사용되고 있거나 마이크 설정이 잘못되어  제대로 된 음성이 구글 서버로 전달되지 않은 경우 발생합니다.
테스트 해보시려면 일단 다른 모듈들을  disable하시고  Hotword만 남겨두시고 음성인식이 되는지 로그보시면서 확인하신 후, 동작이 확인된다면, AMk2 enable하셔서 같이 동작하는지를 보시면 될 것 같아요.

**Comment by eouia** [comment]
피드백이 없으셔서 일단 이슈를 close 합니다.

**Comment by amykim0829** [comment]
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
Whoops! There was an uncaught exception...
{ Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:357:11)
    at spawn (child_process.js:540:9)
    at LPCM16.start (/home/pi/MagicMirror/modules/MMM-Hotword/components/lpcm16.js:101:15)
    at Class.startListening (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:217:14)
    at Class.activate (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:175:10)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:72:16)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at Socket.emit (events.js:182:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue,

**Comment by eouia** [comment]
이 오류는 HOTWORD에서 config을 잘못 설정하면 발생할 수 있는 오류입니다. 정확히는, 마이크 셋업이 틀려서 계속 시도하다가 메모리 부족이 발생하는 경우입니다.
일단 아래 문서의 config을 참조하셔서 해보세요.
https://github.com/eouia/MMM-Hotword/blob/master/documents/config.md#simple-configuration-example
대개의 경우 mic device를 잘못 준 경우일 겁니다.

**Comment by amykim0829** [comment]
아..... 디바이스번호.... 0번인데 1번으로 줘서 그런거였어여 ㅠ 괜한 오디오설정만 계속 건들이거 있었네요 ㅠㅠ 도움주셔서 감사합니다!!!!!
