### ISSUE TITLE
How to update existing MMM-Hotword

### ISSUE THREAD

**Issue by Ryan792** [eouia/MMM-Hotword#56]
My MMM_Hotword is working fine, but I am seeing "new update available for MMM-Hotword" on top of the screen.

Now my question is in order to update do I need to remove MMM-Hotword module first by using this command:

cd ~/MagicMirror/modules
rm -rf MMM-Hotword**

or if no need to remove existing module, can I use only these commands to update:

sudo apt update
sudo apt upgrade
sudo apt install libmagic-dev libatlas-base-dev sox libsox-fmt-all

OR

sudo apt update
sudo apt upgrade
sudo apt install libmagic-dev libatlas-base-dev sox libsox-fmt-all

cd ~/MagicMirror/modules
git clone https://github.com/eouia/MMM-Hotword.git
cd MMM-Hotword

chmod +x ./installer/install.sh
./installer/install.sh

I am not having any issues at this moment with my current version of MMM-Hotword, Please let me know the exact line command to update. Thanks in advance!:)

**Comment by eouia** [comment]
If you don't have any issue with old version, you don't need to update.

But if you want to update anyway,
1) Remove old version first. https://github.com/eouia/MMM-Hotword/blob/master/documents/install.md#from-old-version-v-1xx
2) Do auto-installation.  https://github.com/eouia/MMM-Hotword/blob/master/documents/install.md#auto-install
3) Rewrite config. https://github.com/eouia/MMM-Hotword/blob/master/documents/config.md#simple-configuration-example

**Comment by Ryan792** [comment]
Thank you so much!:)
Another question: If I do not update, how to remove the "update available" from the top of the screen?

**Comment by eouia** [comment]
You might be using `updatenotification` module. https://github.com/MichMich/MagicMirror/tree/master/modules/default/updatenotification
Disable it.

**Comment by Ryan792** [comment]
Thank you so much! :)
