### ISSUE TITLE
Can't wake Assistant

### ISSUE THREAD

**Issue by followarcane** [eouia/MMM-Hotword#57]
Hello, after i successfuly made my mirror i have a problem.

After i hear the brief today. i can't wake my assistant again. i checked my mic with recording something and listened it. Both works.

i'm using HyperxCloud II headset.

My Config is 

> 
{

			module: "MMM-Hotword",
			position: "top_right",
			config: {
				chimeOnFinish: null,
				mic: {
					recordProgram: "arecord",
					device: "plughw:1"
				},
				models: [
					{
						hotwords    : "smart_mirror",
						file        : "smart_mirror.umdl",
						sensitivity : "0.5",
					},
				],
				commands: {
					"smart_mirror": {
						notificationExec: {
							notification: "ASSISTANT_ACTIVATE",
							payload: (detected, afterRecord) => {
								return {profile:"default"}
							}
						},
						restart:false,
						afterRecordLimit:0
					}
				}
			}
		},
		{
			module: "MMM-AssistantMk2",
			position: "top_right",
			config: {
				deviceLocation: {
					coordinates: {
						latitude: 37.5650168, // -90.0 - +90.0
						longitude: 126.8491231, // -180.0 - +180.0
					},
				},
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1",
				},
				notifications: {
					ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
					ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
				},
				useWelcomeMessage: "brief today",
				profiles: {
					"default" : {
						lang: "en-US"
					}
				},
			}
		},
> 
so i'm tryin to wake it up with "Smart Mirror" also tried Jarvis with editing config but it didnt work.

Help please, Regards.

**Comment by followarcane** [comment]
UPDATE:

i think  i can wake Jarvis now but nothing more. After i wake it, nothing happens.

> [HOTWORD] Detected: jarvis
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.

>

Last 5 Logs after daily brief done by assistant.

Regards,

**Comment by eouia** [comment]
Hmmm. First, I don't know how you could solve the problem with MMM-NotificationTrigger, but seems not so normal way. It is not needed anymore after AMK2 version 2 and Hotword version 2.

```
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }
[HOTWORD] begins.   <-- WATCH!
[HOTWORD] Detector starts listening.
[AMK2] assistant ready
```

`[HOTWORD] begins. `  <-- It should not begin again after detected because you've set `restart:false`. Hotword should be paused and release Mic while AMK2 is working. Your Issue might came from that.

**Comment by followarcane** [comment]
So, lets say i don't use MMM Trigger, lines be like

> [HOTWORD] Detected: jarvis
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }
[HOTWORD] begins.
[HOTWORD] Detector starts  listening.
>

As you said, it sets `restart:false`. What should i do?

**Comment by eouia** [comment]
Let's test somethings.

1) Disable all other modules except MMM-Hotword.
2) Use this config;
```js
  commands: {
      "jarvis": {
        notificationExec: {
          notification: "ASSISTANT_ACTIVATE",
          payload: (detected, afterRecord) => {
            return {profile:"default"}
          }
        },
        restart:false,
        afterRecordLimit:0
      }
    },
```
3) Try again. It should be stopped here with `restart:false`;
  > [HOTWORD] Detected: jarvis
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }

**Comment by followarcane** [comment]
I just used your config file from somewhere that i found and all good :) Thanks for help.

Ehmm... Can we talk with Jarvis Recursive? I mean i want jarvis to help me until i say him good bye or thanks

**Comment by eouia** [comment]
Not possible in this version. Maybe the next version I could consider to implement. but not yet.

**Comment by followarcane** [comment]
Thank you for your helps eouia, after i've done my things maybe i'll try to write it myself and let you know if i can handle with it :)

Regards,
