### ISSUE TITLE
안녕하세요 이슈는 아니고 여쭤볼게 있어서 남깁니다.

### ISSUE THREAD

**Issue by Jeongseongwon** [eouia/MMM-Hotword#58]
안녕하세요. 에러는 아닌데 혹시 몇 가지 여쭤볼 수 있을까요.

최근에 스마트미러를 막 만들기 시작한 초보입니다.
유튜브에 있는 동영상을 보고 시작했는데 업데이트가 되서 역시나 잘 안되더라구요 하지만, 이곳 저곳 코멘트 남기신거 보고 잘 실행시켰습니다.

이제 그 이상으로 좀 더 진행해보고자 하는데 어려움이 있어 몇 가지 여쭤보려고 합니다.

첫 번째로 MMM-Youtube 모듈 역시 사용하고자하는데 혹시 예제 같은게 있을까요? 또, 이걸 Hotword가지고도 제어 할 수 있을까요?
유뷰트 모듈을 이용하려고하는데 이 부분은 초기 설정에 몇가지만 추가해서 하려고 하는데 아예 안 나오더라구요.

두 번째로 hotword를 이용해서 timetable모듈을 사용할 수 있을까요? 현재는 그냥 show hide를 하는 수준이긴 한데 그 안에 있는 내용을 제가 수정할 수 있는지요.

며칠 하다보니 한계가 느껴져서 질문드립니다 ㅜ

제가 사용하는 config 파일내 유뷰트 모듈부분입니다.
module: "MMM-YouTube",
	  position: "top_center",
	  config: {
	    verbose:true,
	    defaultQuality: "default",
	    disableCC: true,
	    showPlayingOnly: true,
	    defaultLoop: false,
	    defaultShuffle: false,
	    defaultAutoplay: true,
	    onStartPlay: null,
	    playerVars: {
	      controls: 0,
	      hl: "en",
	      enablejsapi: 1,
	      showinfo: 0,
	      rel: 0,
	      cc_load_policy: 0,
	    },
	    onStartPlay: {
		  type: "id",
		  id: "k2qgadSvNyU",
		  shuffle: true,
		  loop: false,
		  autoplay: true,
	    },

**Comment by eouia** [comment]
예를 들어, "video"란 핫워드로 특정 유튜브 영상을 재생시키고자 한다면, 
Hotword에 "video" 모델(pmdl로 만들어진)을 추가하고, 거기에 연결된 "command"를 notificationExec 형태로 아래처럼 지정하시면 될 겁니다.
```js
commands: {
  "video": {
    notificationExec: {
      notification: "YOUTUBE_LOAD",
      payload: {
        type: "id", //REQUIRED
        id: "UOxkGD8qRB4", //REQUIRED. YouTube Video Id.
        loop: false, //OPTIONAL
        autoplay: true, //OPTIONAL
      }
    }
  }
}
```
좀 더 상세한 내용들은 https://github.com/eouia/MMM-Youtube#control-by-notification 이거 참조하시구요.


두번째 질문하신 타임테이블 관련 내용은 무엇을 말씀하시는지 모르겠습니다. 핫워드 모듈 혹은 어시스턴트 모듈은 다른 모듈들이 명령을 전달해주는 것뿐이라서, 원래 해당 모듈에서 불가능한 기능을 가능하도록 해주는 건 아닙니다. 개구리 모듈에게 "날아라" 명령을 전달해준다해서 개구리 모듈이 실제 날 수 있게 해주는 건 아닙니다. 그건 개구리 모듈이 해결해야 할 문제죠.

**Comment by Jeongseongwon** [comment]
네 감사합니다!
도움 많이 되었습니다.
그리고 두번째 답변은 무슨 뜻인지 알 거 같습니다!

좋은 하루보내세요.
