### ISSUE TITLE
구글 어시스턴트 음성 SDK 커스터마이징 관련

### ISSUE THREAD

**Issue by nnnlog** [eouia/MMM-Hotword#59]
마이크로 `"~~~"` 라는 단어를 말하면 그 단어를 제가 핸들링하여 어떤 결과를 구글 어시스턴트 등 음성 API를 사용하여 말해주거나, 화면에 띄어주고자 하는데, 어떤식으로 해야할까요?

**Comment by eouia** [comment]
질문하신 게 좀 광범위해서요...
1) 마이크로 XXX라는 단어를 말하면 => 이거 자체는 MMM-Hotword 또는 MMM-AssistantMk2 로 가능한데, 음성자체를 인식하는 간단한 거라면 MMM-Hotword만으로 되요. 그런데 문장의 뜻 자체를 이해하려면 MMM-AssistantMk2를 써야 하는데 이건 전자보다 복잡하죠.
2) ... 말해주거나 ... => TTS 솔루션을 쓰세요.
3) ... 화면에 띄어주거나 ... => 뭘 띄우시는지는 모르겠는데, 그걸 해주는 모듈을 찾거나 만드셔야죠.

MMM-Hotword도, MMM-AssistantMk2도 궁극적으로는 사용자의 음성명령을 다른 모듈로 전달해주는 역할을 할 뿐입니다. 무언가 이루어져야 할 job이 있다면 그걸 해주는 모듈은 별도로 필요합니다.

**Comment by nnnlog** [comment]
마이크로 단어든 문장이든 무언가를 말했을 때, 특정 단어가 포함되었을 때 처리할수 있는 방법이 있을까요?

**Comment by eouia** [comment]
답변이 늦었습니다. 가능한 주기적으로 살펴보면서 전부 답변드리는데 이건 누락되었었네요.
특정단어 자체를 pmdl로 만들면 Hotword 자체만으로도 가능합니다. 예를 들어 "백두산" 이라는 pmdl을 만들면, "동해물과 **백두산**이 마르고 닳도록... " 이라고 말하면 캐치가 가능합니다. 다만 이건 음성패턴자체를 기계적으로 인식하는 거라 문맥을 따진다든가 하는 건 어렵죠. 무조건 그 단어에 반응하도록 하는 겁니다.

좀더 문맥을 고려한 용법이 필요하다면 AssistantMk2의 transcriptionHook 또는 customAction을 활용하세요.

**Comment by eouia** [comment]
피드백이 없어 이슈를 닫겠습니다.
