### ISSUE TITLE
Hotword Setup

### ISSUE THREAD

**Issue by Sean-Amor** [eouia/MMM-Hotword#60]
Can you make a tutorial on how to install/setup? Also how to use this? With Raspberry Pi Zero W. I would love to learn how to power an led with the hotword "Lumos" and turn off the led with the hotword "Nox" thank you so much!

**Comment by eouia** [comment]
Raspberry Pi Zero couldn't be working because this module is using advanced technics which be not  supported by RPI0 default. (Of course, you can install stuffs by manual, but not recommended)

For usual installation and configuration, well, read the README doc. that is all.

**Comment by Sean-Amor** [comment]
Thank you, would you by chance be able to instruct me or write a code, I believe you call them recipes, to power an led, that is followed by a .wav file sound effect? I'm trying to learn how, but there are so many different ways, I can't quite understand how. Thank you so much for your response, you're the first person to respond in months. If I cannot use rpi0 I may use the desktop version or raspian stretch, with my rpi0 connected so it only uses the gpio pins.

**Comment by eouia** [comment]
To make a command to turn on LED, first Your LED be controllable with some methods.
I assume you have already a script - "ledon.sh" which can turn on LED when it is executed.

And also assume you have already a voice model - "ledon.pmdl" (You can make it with trainer - https://github.com/eouia/MMM-Hotword/blob/master/documents/trainer.md).


In that case You can make a command like this; add this into your configuration of MMM-Hotword

```js
models: [
  {
    hotwords    : "ledon",
    file        : "ledon.pmdl",
    sensitivity : "0.5",
  },
],
commands: {
  "ledon" : {
    shellExec: {
      exec: "./somewhere/ledon.sh"
    }
  }
},
```

Some enviromental values might be adjusted, but basic concept is like that.


And about RPI0,
By default, RPI0 is using different version of OS with popular RPI2/3. Current Raspbian Stretch has more advanced features in it. So you need to upgrade your system manually if you want to use RPI0 for this module. Sorry, I have no interests in using RPI0 so cannot help you about it - which parts to be upgraded and how to.

**Comment by Sean-Amor** [comment]
Thank you very much I really appreciate it this cleared up quite a lot. I will be happy to share what I come up with if I'm successful.
