### ISSUE TITLE
트레이닝 방법과 실행오류 질문있습니다

### ISSUE THREAD

**Issue by ddoong** [eouia/MMM-Hotword#61]
저번에 음성 녹음이 안되서 질문드렸는데 해결은 된것 같은데 문제가 있습니다.
맞는지는 모르겠는데 라즈베리파이에 사운드카드가 default로 0번으로 설정되어 있는데 hotword는 1번카드를 기준으로? 녹음을 하는것 같습니다.
그래서 asoundrc에서 1로 셋팅한 뒤 녹음을 하고 0으로 바꿔서 1~3 wav파일을 재생했을 때 잘 나옵니다.  혹시 이 default를 바꿀 수 있는지 알고싶습니다.

그리고 module:["clock"]로 hide 했을땐 작동이 정상적으로됩니다.
근데 module:[],  명령어로 모든 모듈 선택해서 hide 했는데적용이안됩니다.
확인부탁드려도될까요

**Comment by eouia** [comment]
설정에서 `device:"default"` 혹은 `device:null` 로 두시면 0번 디폴트카드 값을 받을텐데요.

혹시 recipe 파일에 작성하셨다면, 버그가 하나 있는데요.. (고쳐야 하는데 안고치고 있습니다... ^^;;;)
`module:[]` 대신
`module: ()=>{return []}` 로 바꾸시면 아마 동작할겁니다.

**Comment by ddoong** [comment]
1. 음성녹음할때 에러가납니다.
일단 제 .asoundrc 설정은 이렇습니다.
pcm.!default {
	type hw
	card 0
}
ctl.!default {
	type hw
	card 0
}

rec -r 16000 -c 1 -b 16 -e signed-integer 1.wav  ~ 3.wav에서 녹음을 할 때 아래 사진처럼 문제가생깁니다.
![image](https://user-images.githubusercontent.com/36120857/59755470-eaac9380-92c2-11e9-8d3d-28ecd3e268f6.png)

default 값이 달라서 그러는데 asoundrc에서 card 1로 바꾼뒤 할 경우 실행이 정상적으로되고
재생할때 default에러가 생겨서 asoundrc를 0으로 다시 바꾼 뒤 재생해서 했을때 이상없었습니다.
config에서는 device: "plughw:1"로 해두어도 이상없이 실행됩니다.
단지 녹음 부분을 card 0일때 될수있도록 하고싶어서 질문드린거였습니다.
 
2. 커맨드는 이겁니다.
    commands: {
        "hide_all": {
            moduleExec:{
                module: ["clock"], // module:[], 할시 에러
                exec: (module, hotword, file) => {
                    module.hide()               
                }               
            },
            restart:true,
            afterRecordLimit:0
        }
    },
module:[], 일때 작동하지않고 파라미터를 적어둘때는 정상작동합니다.

**Comment by eouia** [comment]
1. ALSA configuration(asoundrc)은 제가 도와드릴 수 없네요. 저도 Linux 잘 몰라서.. 저는 보통 PulseAudio가지고 오디오 셋업을 해서 ALSA를 직접 만지는 건 잘 안해서 저도 잘 몰라요. ^^;

2. 에러가 나나요? 아니면 그냥 작동을 안하는 건가요?
일단
`module:[],` 를
`module: ()=>{return []},` 이걸로 바꿔서 한번 테스트해보시겠어요?

**Comment by ddoong** [comment]
그럼 녹음부분은 가능했던 방법대로 계속 해서 사용하겠습니다.
module: ()=>{return []},로 바꿔도 마찬가지네요ㅠㅠ

**Comment by eouia** [comment]
패치 업데이트 했으니 git pull로 업데이트하고 다시 해보시겠어요?

**Comment by ddoong** [comment]
감사합니다! []로 해도 이제되네요 ㅎㅎ
그리고 녹음부분은 아래명령어로 했더니 적용되네요 
arecord -D plughw:1,0 -f S16_LE --rate 16000 -c 1 1.wav
