### ISSUE TITLE
Electron-Prebuilt's Version Number Error

### ISSUE THREAD

**Issue by Sean-Amor** [eouia/MMM-Hotword#62]
https://hastebin.com/zajikohoza.sql

The last portion, where it says "An unhandled error occurred inside electron-rebuild
Unable to find electron-prebuilt's version number, either install it or specify an explicit version
"

Any Help is appreciated!

**Comment by eouia** [comment]
Sorry, Snowboy will not be installed on Windows machine (IA32). As Developer of Snowboy team says;

> <img width="681" alt="a" src="https://user-images.githubusercontent.com/1720610/59883739-60455c00-93b6-11e9-996b-3f0d26e0913d.png">

**Comment by eouia** [comment]
But, Only electron-rebuilt might be issue, you might run it on Server only mode (Not with `npm start`, But `node serveronly` and with Chrome(Chriomium)

**Comment by Sean-Amor** [comment]
I fixed it by editing your install.sh 
./node_modules/.bin/electron-rebuild -v 1.8.5 -e /usr/local/lib/node_modules/electron-prebuilt

**Comment by Sean-Amor** [comment]
I'm actually running on raspberry Pi Stretch desktop build, not Windows. The rebuild was successful once I revised the install.sh although I am curious what you mean by running it on server mode only.

**Comment by Sean-Amor** [comment]
How do you change the mic so it recognizes your microphone?

**Comment by eouia** [comment]
If so, it could be something weird. Because your log said `node-v57-linux-ia32` and it means you are probably doing things on IA32 machine. 
Anyway, you seems to solve that problem. nice to hear it.

> How do you change the mic so it recognizes your microphone?
First, you can check your mic device info (probably it might be USB mic, right?) with `arecord -l`.  With that info, you can specify your mic like `plughw:1,0`. Or you can use more complex ALSA setup for your own purpose.
Then, put the device name into configuration of modules. That's all.

**Comment by Sean-Amor** [comment]
`pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: Intel [HDA Intel], device 0: ALC272X Analog [ALC272X Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`
This is what is listed when I type "arecord -l"
`pcm.!default {
  type analog
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type analog
  slave {
    pcm "hw:0,0"
  }
}
pcm.speaker {
  type analog
  slave {
    pcm "hw:0,0"
  }
}`

I have saved my .asoundrc with this code, inside /home/pi

In the terminal I verbally say snowboy, or computer, etc, and nothing pops up?

**Comment by eouia** [comment]
I'm not that kind of expert so might be wrong.
but as far as i know, "mic" or "hw:0,0" would work.
Anyway, is your system really raspberry? usually bcm2xxx will be the default device of rpi, not alc272... interesting.

**Comment by Sean-Amor** [comment]
Debian Stretch with Raspberry Pi Desktop. Is there some file inside snowboy that I need to tell what mic to use perhaps?  Sorry if you cannot help further. Thank you foe your help.

**Comment by Sean-Amor** [comment]
I can record now, but does your program work out the box, once I install, I say stuff like snowboy, or computer, etc, and I see nothing happening in the terminal. Just not sure if I have to do anything else?

So I try training, when I record my first word, it just continues to record, and doesn't stop.

**Comment by eouia** [comment]
ctrl+c for finishing recording of trainer. not so convenient.

**Comment by Sean-Amor** [comment]
where does it say the wav files?

**Comment by Sean-Amor** [comment]
Okay, now its trained, I placed the pmdl in its respective models folder, added the recipe, but I still see nothing happen when I say the hotword, or any universal model.

**Comment by eouia** [comment]
show me your configuration. and check whether there be some error (back or front). You can get more mic specific logs with `mic.verbose:true`

**Comment by Sean-Amor** [comment]
How might I go about showing you my configuration? Also when I type "mic.verbose:true" in terminal pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword/trainer $  mic.verbose:true
bash: mic.verbose:true: command not found, this appears.

**Comment by eouia** [comment]
Sorry for late answer.
in MMM-Hotword section of `config.js`;
```js
// Other configuration fields...
...
mic : {
  verbose:true, // <- add this `mic` section
  ... // your other configs of mic... 
},
...
// Also others.

**Comment by eouia** [comment]
Have you still got a problem? I'll close this issue cuz no more feedback. Have a nice day.
