### ISSUE TITLE
sequential hotwords

### ISSUE THREAD

**Issue by pooyasa** [eouia/MMM-Hotword#67]
Hi
I'm not sure but I've got a problem with this part of the documentation.
**This module can detect sequential hotwords at a time. When you say "snowboy blah blah jarvis blah blah ... ", the detector could catch "snowboy-jarvis" as hotword. you can use this snowboy-jarvis as your command name.**

I want to call my mirror "Snow Boy" and then say my real command which is "Turn off the light".
Something like "Snow Boy, Turn off the Light"
As I read that part of the documentation, I wrote this in the recipe:

```
var recipe = {
  models: [
    {
      hotwords    : "snowboy",
      file        : "snowboy.umdl",
      sensitivity : "0.5",
    },
    {
      hotwords    : "task",
      file        : "turnoff.umdl",
      sensitivity : "0.5",
    },    
  ],
  commands: {
    "snowboy": { 
      notificationExec: {
        notification: "SHOW_ALERT",
        payload: (hotword, file) => {
          return {"message": `Detected:${hotword}`, timer:2000}
        }
      }
    },
    "snowboy-task": { 
      notificationExec: {
        notification: "python",
        payload: "off"
        }
    },    
  }
}

exports.recipe = recipe // Don't remove this line.

```
but this is not working. when I say snow boy turn off the lights it only interprets the second phrase and tries to find the "task" command which doesn't exist.
What should I do?

**Comment by pooyasa** [comment]
Sooo I managed to fix it.
It was my mistake, didn't set the afterRecordLimit.
but the problem now is, it can undrestand I said "snowboy-task" but doesn't execute the notification I gave to it, as a matter of fact, it only did it once.

Here's the console:

```
[HOTWORD] Detected: snowboy
[HOTWORD] After Recording: 4000
[HOTWORD] After Recording: 4000
[HOTWORD] After Recording: 4000
[HOTWORD] After Recording: 4000
[HOTWORD] Detected: snowboy-task

```

and it just doesn't do anything after that.
It just stays there, untill I call it again!
the next time I call it "snowboy" it executes the notification and here's the result:
```

[HOTWORD] stops.
[HOTWORD] After Recording finised. size: 16050
[HOTWORD:B2W] WAV_FILE_CREATED: /home/pi/MagicMirror/modules/MMM-Hotword/temp/afterRecording.wav 16050
[HOTWORD] Final Result: { detected: true,
  hotword: 'snowboy-task',
  file: 'temp/afterRecording.wav' }

```

**Comment by eouia** [comment]
Sorry for late reply. I was on vacation.
I cannot test it at this moment, In a few days, after returning home I'll inspect.

**Comment by pooyasa** [comment]
Hi, it's alright.
In the meantime I'll send you my recipe and hotwords.
Thanks.

[Files.zip](https://github.com/eouia/MMM-Hotword/files/3396307/Files.zip)

It's supposed to turn an GPIO on after I say "snowboy - mirror"
But it just gets stuck over there until I say snowboy again.
Something like "SnowBoy - Mirror - SnowBoy"

**Comment by eouia** [comment]
I've patched. Plz update and try to test again.

**Comment by pooyasa** [comment]
Hi, thank you. It works perfectly now.
Just another question, can I make it play something when it hears "snow-boy" and then start listening too?
something like:
+SnowBoy!
-[plays beep sound and waits for the next command]
+mirror!
-[does the magic]

**Comment by pooyasa** [comment]
The thing is, I don't want to use speech recognition modules, because of the privacy issues and their delay time.
I used google, pocketsphinx, houndify, kaleope, mk2  and all of them take about 15 seconds to recognize my command and that's a real long delay.
So I wanted to use this module as an offline, fast, and standalone module to recognize my simple orders such as "Mirror, turn on room lights", "Mirror, turn on hall lights" etc and I wanted it to have "mirror" as a wakeword.
It seems to be doing that and I just wanted it to play a tone after I say the wake word so that I realize it's listening to the next word.
It's alright though, it works already, ،Thank you anyway.

**Comment by eouia** [comment]
How about just using "Mirror-TurnOn-RoomLights" and "Mirror-TurnOn-HallLights" instead waiting prompt? I think there is no need of waking and prompt awaiting. Just saying seamlessly "Mirror, turn on room lights" could be done. Or you can make somewhat long personal model - "TurnOnRoomLights.pmdl"

**Comment by eouia** [comment]
Anyway, it could be interesting challenge. I will consider, but not guarantee. If you have interests, you could also modify module and PR for others. Always welcome.

**Comment by pooyasa** [comment]
Thank you, I will try to do that and I will send you the results.
