### ISSUE TITLE
warning! could not load config file. starting with default configuration. error found: error: cannot find module './snowboy/lib/node/index.js'

### ISSUE THREAD

**Issue by hohomiee** [eouia/MMM-Hotword#69]
![KakaoTalk_20190724_190715546_01](https://user-images.githubusercontent.com/53257425/61785390-960eb200-ae46-11e9-9647-30a87fe22551.jpg)
![KakaoTalk_20190724_190715546_02](https://user-images.githubusercontent.com/53257425/61785399-99a23900-ae46-11e9-9695-9b30c3f0afe7.jpg)

![KakaoTalk_20190724_190715546_03](https://user-images.githubusercontent.com/53257425/61785447-aa52af00-ae46-11e9-86ac-b1d597908d14.jpg)
 
안녕하세요. 스마트미러 실행을 하면 검은 화면만 나와서 질문드려요. 처음에 화면은 나오고 음성인식이 안되서 댓글에 snowboy 설치방법 올려주셨길래 snowboy만 지우고 다시 설치를 해봤는데 소리도 안나오고 화면도 검은 화면만 나오길래 문제점을 찾지 못해서 질문드려요. 
lib/node 밑에 index.js, index.ts 파일 다 있고  lib/node/binding/Release 밑에도 있어야한다는 파일 다 있는데 왜 오류 메세지에 index.js가 문제라고 나올까요??ㅜㅜ

**Comment by eouia** [comment]
음.. MMM-Hotword를 어떻게 설치하셨나요? 
https://github.com/eouia/MMM-Hotword/blob/master/documents/install.md
이 문서에 적힌 대로 하신건가요? (Auto-install)

**Comment by hohomiee** [comment]
@eouia 네 저거대로 설치했고
![KakaoTalk_20190724_203314801](https://user-images.githubusercontent.com/53257425/61790536-6c5b8800-ae52-11e9-8ddc-81de6cd96168.jpg)
고
![KakaoTalk_20190724_203314801](https://user-images.githubusercontent.com/53257425/61790536-6c5b8800-ae52-11e9-8ddc-81de6cd96168.jpg)
@eouia 네 저거대로 설치했고
![KakaoTalk_20190724_203314801](https://user-images.githubusercontent.com/53257425/61790536-6c5b8800-ae52-11e9-8ddc-81de6cd96168.jpg)
고
![KakaoTalk_20190724_203314801](https://user-images.githubusercontent.com/53257425/61790536-6c5b8800-ae52-11e9-8ddc-81de6cd96168.jpg)


./installer/install.sh 이 명령어에서 npm ERR가 나오긴했습니다

**Comment by hohomiee** [comment]
네! 그대로 설치했고 ./installer/install.sh 이 명령어 했을때 npm 에러가 나오긴했습니다
[image: KakaoTalk_20190724_203314801.jpg]

2019년 7월 24일 (수) 오후 8:10, Seongnoh Sean Yi <notifications@github.com>님이 작성:

**Comment by eouia** [comment]
음.. 제대로 설치하신 것 같지 않습니다. 왜냐하면, snowboy가 node_modules 아래가 아닌 MMM-Hotword 아래에 설치되어야 하거든요. index.js가 있다고 보여주신 화면을 보면 snowboy가 node_modules 아래에 있는 걸로 보이거든요.
아마 이전 버전을 수동으로 설치하셨다가 다시 installer로 새로 설치하려고 하신 것 아니신지요?
일단 MMM-Hotword를 전체 다 지우고 다시 해보시겠어요?
(그리고 tsc 에러가 발생하더라도 Build Completed 까지 일단 갔다면 정상설치되었을 수 있습니다. 일부러 에러가 나든 안나든 상관없도록 스크립트를 짰거든요.)

**Comment by eouia** [comment]
index.js가 있는지 확인해보셔야 할 디렉토리는
`~/MagicMirror/modules/MMM-Hotword/snowboy/lib/node` 여기입니다.

**Comment by hohomiee** [comment]
다시 지우고 설치해서 화면은 나왔어요!! 감사합니다ㅜㅜ
근데  ./installer/install.sh 여기 부분에서 또 에러가 나오긴했는데 괜찮은건가요??
[image: KakaoTalk_20190724_211022941.jpg]


2019년 7월 24일 (수) 오후 8:52, Seongnoh Sean Yi <notifications@github.com>님이 작성:

**Comment by eouia** [comment]
Build Complete 메세지까지 나왔고, 그 아래에 electron-v3. 어쩌구 하는 메시지랑 /lib/index.js 어쩌구 하는 메시지까지 나왔으면 일단 설치는 되었을 겁니다.

**Comment by hohomiee** [comment]
정말 감사합니다!!!!!!🙏 하다가 또 궁금한게 생기면 여쭤봐도 될까요?ㅜㅜ

2019년 7월 24일 (수) 오후 9:13, Seongnoh Sean Yi <notifications@github.com>님이 작성:

**Comment by eouia** [comment]
네. 물론이죠.

**Comment by hohomiee** [comment]
또 여쭤볼게 있어서 메일 드립니다. 스마트미러를 실행시켰을때 음성 인식을 하지 못하는데 config 폴더안에 있는 config.js
파일을 수정해야하는건가요?
[image: KakaoTalk_20190725_131135397_01.jpg]
[image: KakaoTalk_20190725_131135397_02.jpg]
우선 현재 config파일은 이렇습니다! ㅠㅠ

2019년 7월 24일 (수) 오후 9:21, Seongnoh Sean Yi <notifications@github.com>님이 작성:

**Comment by eouia** [comment]
이미지 파일이 안보여서 뭐라 답변드리기 어렵네요.

**Comment by hohomiee** [comment]
![KakaoTalk_20190725_131135397_02](https://user-images.githubusercontent.com/53257425/61857504-42ac6a80-aeff-11e9-9278-07418270c360.jpg)
![KakaoTalk_20190725_131135397_01](https://user-images.githubusercontent.com/53257425/61857510-44762e00-aeff-11e9-8e44-2e49a1e3fdeb.jpg)

**Comment by eouia** [comment]
로그는 뭐라고 나오나요?

**Comment by hohomiee** [comment]
죄송해요ㅜ 사진이 올라간줄 알았는데 .. 다시 올렸습니다!!


2019년 7월 25일 (목) 오후 4:57, Seongnoh Sean Yi <notifications@github.com>님이 작성:

**Comment by hohomiee** [comment]
[image: KakaoTalk_20190725_172242235.jpg]

로그 화면은 이렇게 나와요!

2019년 7월 25일 (목) 오후 5:13, Seongnoh Sean Yi <notifications@github.com>님이 작성:

**Comment by hohomiee** [comment]
![KakaoTalk_20190725_172242235](https://user-images.githubusercontent.com/53257425/61858454-0ed24480-af01-11e9-9ca8-e60eb39177b1.jpg)
로그 화면은 이렇게 나옵니다!

**Comment by eouia** [comment]
No model to load 라는 메시지가 있네요. 음.. config을 보니 models는 제대로 적으신 것 같은데, 이게 제대로 안넘어왔다는 것은, 아마도 front에 에러가 있을 것 같습니다. 프론트 에러가 있을시 모듈들이 정상 작동 안할 수 있어요.

1) 일단 Hotword를 제외한 다른 모듈들은 모두 disabled 시키세요.
2) `npm start dev` 를 하면 일렉트론 프론트 단에 dev-console이 뜹니다. 거기 console 탭을 보시면 어떤 에러가 있는지 보일거에요.
3) 만약 특별한 에러가 없고, 동작이 잘된다면 => 사용하고 있는 다른 모듈 중에 뭔가 프론트 에러가 있어서 다른 모듈의 동작을 방해하는 게 있을 겁니다.
4) 에러가 있고, 동작이 잘 안된다면 => 보여주세요.
5) 에러가 없는데, 동작 역시 잘 안된다면... => 연구대상이네요.

**Comment by hohomiee** [comment]
![KakaoTalk_20190725_181609182_01](https://user-images.githubusercontent.com/53257425/61862177-67f1a680-af08-11e9-9949-f7d228cfb9bd.jpg)
![KakaoTalk_20190725_181609182_02](https://user-images.githubusercontent.com/53257425/61862180-69bb6a00-af08-11e9-95a9-aa252e27354a.jpg)

에러가 있고, 동작이 잘 안되는 상황이네요

**Comment by hohomiee** [comment]
![KakaoTalk_20190725_182226149](https://user-images.githubusercontent.com/53257425/61862640-2f060180-af09-11e9-8fd8-c376c0e68c02.jpg)
config파일에 MMM-Hotword만 썼고
![KakaoTalk_20190725_182141097_01](https://user-images.githubusercontent.com/53257425/61862694-4218d180-af09-11e9-9d31-94ee4913579d.jpg)
![KakaoTalk_20190725_182141097_02](https://user-images.githubusercontent.com/53257425/61862696-43e29500-af09-11e9-83a2-6a4f041cc537.jpg)
이 사진은 콘솔창이에요!

**Comment by eouia** [comment]
음... config 에러 있으신 거 아닌가요? 지금 보여준 화면은 에러랑은 상관없구요. (에러는 빨간 색으로 표시됩니다.)
거기 써있는 로그대로라면, 모듈이 하나도 로딩안되서 기본 helloworld 모듈 (config에러로 모듈이 로딩안될 시 대신 로딩되는 디폴트 모듈)만 올라가 있는 상태거든요. MMM-Hotword자체도 로딩이 안되었네요.

config 파일 자체를 eouia0819@gmail.com으로 보내주세요.

**Comment by eouia** [comment]
> 지금은 config파일에 원래 처럼 모든 모듈 쓰고 npm start dev 해보고있는데 오류도 늘어나고 렉 걸려서 마우스도 안움직이고 멈췄네요ㅜㅜ

이걸 보면, 다른 모듈들에 문제가 있는 것 같아요. 
 모듈들을 모두 disabled하고 하나씩 추가하면서 `npm start dev`로 프론트(dev-console에 빨간 색으로 표시)와 백(터미널 창에 표시)에 어떤 에러가 발생하는지 하나씩 잡으셔야 할 것 같습니다. Hotword와 Asssistant에는 특별히 config문제는 없는 것 같습니다.

**Comment by hohomiee** [comment]
config 파일에 Hotword만 추가해서 해봤는데 아래 처럼 오류가 나오네요.
![KakaoTalk_20190725_191159028_01](https://user-images.githubusercontent.com/53257425/61866506-35e44280-af10-11e9-9eff-25ec0d7fd9ad.jpg)
![KakaoTalk_20190725_191159028_02](https://user-images.githubusercontent.com/53257425/61866510-37ae0600-af10-11e9-8148-94cc63310642.jpg)


우선 하나씩 추가하면서 npm start dev 해보겠습니다!!!

**Comment by eouia** [comment]
저 에러 자체는 특별한 문제는 안되요.
저 상태에서 Hotword가 정상작동하는지 확인해보세요. 프론트 콘솔 말고 터미널 콘솔도 같이 보시면 서버단에서 어떤 일이 현재 일어나는지 보실 수 있어요. 프론트에는 특별한 문제가 없어보이니 서버단에도 문제가 없다면 Hotword가 정상작동되어야 합니다.

**Comment by hohomiee** [comment]
config에 Hotword랑 AssistantMk2 모듈 넣고 실행시켰을때 터미널 콘솔 창이에요.
마이크 동작도 모려고  mic : verbose:true 이 명령어도 해봤는데 듣고는 있다고 나오네요ㅠ

![KakaoTalk_20190725_192832524_03](https://user-images.githubusercontent.com/53257425/61867707-c6bc1d80-af12-11e9-9c9f-1361d47d6c46.jpg)
![KakaoTalk_20190725_192832524_02](https://user-images.githubusercontent.com/53257425/61867715-c91e7780-af12-11e9-8577-284329d678a9.jpg)
![KakaoTalk_20190725_192832524_01](https://user-images.githubusercontent.com/53257425/61867719-cae83b00-af12-11e9-9354-b17dd592fc5b.jpg)

**Comment by hohomiee** [comment]
혹시 snowboy 홈페이지에 가서 로그인하고 음성녹음을 직접해서 해야하는건가요?

**Comment by eouia** [comment]
아까 주신 config대로라면 smart_mirror라는 핫워드는 umdl 이니까 대충 모든 사람들의 발음을 알아 듣습니다.
1) 마이크의 볼륨게인이 너무 작을 수 있습니다. 좀 더 크게 "smart mirror"라고 말해보세요.
2) 발음 문제일 수 있습니다. -_-a

**Comment by hohomiee** [comment]
마이크에 음성이 인식되면 화면창에서 마이크 모양으로 바뀌어야 하는거 아닌가요??ㅜㅜ 처음 실행했을때 구글어시스턴트의 소개말은 들리는데
터미널 창에도 Listening이라고 나오는데 스마트미러 화면은 아무런 변화가 없어서요..
혹시 smart_mirror.umdl을 텍스트편집기로 열어봤을때 아무 내용도 안보이는게 맞나요?

2019년 7월 25일 (목) 오후 8:10, Seongnoh Sean Yi <notifications@github.com>님이 작성:

**Comment by eouia** [comment]
화면.. 은 상관없구요, 
`[HOTWORD:LPCM16] Listening XXXX bytes` 라고 하면 마이크는 제대로 작동되고 있는 거에요. 그런데 detector에서 hohomiee님의 발음을 못 알아듣는 것 뿐이죠. 이유는, 뭐.. 발음이 명확하게 안들린다.. 일 것 같습니다. 더 큰 소리로 말하거나, 발음을 교정하거나... ^^;;;
"smart_mirror"말고 다른 umdl을 써보세요.

**Comment by eouia** [comment]
그리고 AssistantMk2는 disabled해두세요. 로그 쌓이는 내용만 많아져서 한눈에 안보이고 어차피 Hotword 해결 못하시면 의미가 없으니까요. (Hotword가 정 안되시면, MMM-Clap 같은 모듈을 사용하실 수도 있습니다.)

**Comment by hohomiee** [comment]
smart mirror 발음이 문제였던게 맞네요ㅠㅠ 번역기 발음 틀고 해보니까 조금 늦게반응하긴 하지만 됩니다! 친절하게 알려주셔서 감사합니다!!!

**Comment by hohomiee** [comment]
[image: KakaoTalk_20190725_211117785.jpg]
명령어 바꿔보다가 다시 smart_mirror로 바꾸고 실행해봤는데 이러한 오류가 나오네요..
찾아봐도 잘 모르겠어서 혹시 아시나요?ㅜ


2019년 7월 25일 (목) 오후 8:32, Seongnoh Sean Yi <notifications@github.com>님이 작성:

**Comment by hohomiee** [comment]
![KakaoTalk_20190725_211117785](https://user-images.githubusercontent.com/53257425/61873532-20c3df80-af21-11e9-8c27-92a3a5ef1999.jpg)

명령어 바꿔보다가 다시 smart_mirror로 바꾸고 실행해봤는데 이러한 오류가 나오네요..
찾아봐도 잘 모르겠어서 혹시 아시나요?ㅜ

**Comment by eouia** [comment]
100ms도 안되게 열렸다 닫겼다 하는 건 마이크 문제가 있을 수 도 있습니다. 녹음프로그램을 sox로 바꿔보거나 마이크를 다른 걸로 바꿔보세요
