### ISSUE TITLE
electron-v3.0-linux-arm64/snowboy.node: undefined symbol: cblas_sdot

### ISSUE THREAD

**Issue by yms1217** [eouia/MMM-Hotword#70]
Dear,
I got a issue during running MMM-Hotword module thru magic mirror.
I'm using embedded linux (based on Yocto), actually I copied necessary libraries, libcblas/libatlas manually into /usr/lib. However, I didn't see any error message when installing MMM-Hotword and snowboy regarding referencing libraries.

< error message: >
...
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD:LPCM16] Start listening 1 channels with sample rate 16000
[HOTWORD:LPCM16] Listening 44 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
/home/root/new_magicmirror/node_modules/electron/dist/electron: symbol lookup error: /home/root/new_magicmirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/electron-v3.0-linux-arm64/snowboy.node: undefined symbol: cblas_sdot

"uname -a" result:
Linux imx8mqevk 4.14.78+g7029e49 #1 SMP PREEMPT Mon Jul 22 06:42:13 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

< configuration >
                {
                        module: "MMM-Hotword",
                        position: "bottom_left",
                        config: {
                                mic: {
                                        recordProgram: "arecord",
                                        device : "plughw:4,0",
                                        verbose: true,
                                },
                                models: [
                                        {
                                                hotwords: "smart_mirror",
                                                file: "smart_mirror.umdl",
                                                sensitivity: "0.5",
                                        },
                                ],
                                commands: {
                                        "smart_mirror": {
                                                notificationExec: {
                                                        notification: "ASSIS$
                                                        payload: (detected, $
                                                                return {prof$
                                                        }
                                                },
                                                restart: false
                                        },
                                }
                        },
                },

< arecord -l >
root@imx8mqevk:~/new_magicmirror# arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: imxspdif [imx-spdif], device 0: S/PDIF PCM snd-soc-dummy-dai-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: imxhdmiarc [imx-hdmi-arc], device 0: S/PDIF PCM snd-soc-dummy-dai-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 4: U0x46d0x825 [USB Device 0x46d:0x825], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

Do you have any clue for this issue?

**Comment by eouia** [comment]
Which device are you using? seems not rpi. I'm not sure whether it will work on other device(especially intel x86 architecture)

**Comment by eouia** [comment]
These are compatible list by snowboy developers.
```
all versions of Raspberry Pi (with Raspbian based on Debian Jessie 8.0)
64bit Mac OS X
64bit Ubuntu 14.04
iOS
Android
ARM64 (aarch64, Ubuntu 16.04)
```

**Comment by eouia** [comment]
After some researching, you are probably using i.MX8 based device. I have no experience about it so don't know whether it could be compatible or not.
