### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by TheSquareOne** [eouia/MMM-Hotword#72]
https://github.com/eouia/MMM-Hotword/blob/a023bb2256c6370950fee3fd72019c4e2bc93943/MMM-Hotword.js#L209

Hello!
I was wondering if that "htoword" is suppose to be "hotword".
1st time submitting issue, so i'm not sure if this is right way to do this.

**Comment by eouia** [comment]
ohmygod! There was a typo! I'll patch it tomorrow (I'm not in my working machine now)

**Comment by eouia** [comment]
Thanks. I'm fixing it.
