### ISSUE TITLE
안녕하십니까 mmm-hotword trainer 관련 질문이 있어서 질문을 하게 되었습니다.

### ISSUE THREAD

**Issue by wjdalsrbekt** [eouia/MMM-Hotword#73]
![image](https://user-images.githubusercontent.com/47201943/62451928-284d7900-b7aa-11e9-8d72-caa0440e0b2d.png)
 안녕하십니까 스마트미러를 따라하던도중 pmdl로 스마트미러를 호출하고싶어서 trainer.md를 보고 따라하고있는데 이부분에서 이렇게 뜨네요... 혹시 해결방법이나 조언을 좀 얻고싶은데 알려주실수 있으신가요..??

**Comment by wjdalsrbekt** [comment]
원래는 한글을 하고싶은데 한글을 도전하기전에 영어로 먼저 도전해보려고하는데 작동하질 안네용..

**Comment by eouia** [comment]
맨 첫줄 `/usr/bin/env bash` 뒤에 `\r` 이라는 쓸 데 없는 문자(눈으로는 안보입니다)가 들어간 채로 저장된 것 같네요. Windows 환경에서 이 파일을 열어보셨나보죠?
원래 리눅스에서 줄바꿈은 `\n`인데, 윈도우즈는 `\r\n`을 넣습니다. 그래서 bash에서 못 읽은 것 같네요.
해결책은; 
https://superuser.com/questions/156516/is-there-a-bash-command-to-convert-r-n-to-n
읽어보시고 이 중에서 선택하시면 될 것 같습니다.

**Comment by wjdalsrbekt** [comment]
감사합니다 덕분에 영어랑 한글에 원하는 음성을 넣어서 사용할수 있게 되었습니다.

좀더 완벽한 스마트 미러를 만들고싶은 욕심이 점점 생깁니다...

몇가지 질문이 더 생겼는데..

![image](https://user-images.githubusercontent.com/47201943/62465085-0e6f5e80-b7c9-11e9-9726-1831eb260bb7.png)
 
일때 
1. 정원이라는 글자가 인식되면서 세로로 출력이 되는데 혹시 이거는 한글이라 그런건가요..??

 2. 가끔 아무말이나해도 인식을 하게 되는데, 혹시 원하는 핫워드에 반응을 좀더 정확하게 할려면 녹음당시에 소음같은것이 아예 없어야하나요..?? 헛기침하는데 반응을 할때도 있어서요 ㅠㅠ

3. mmm-hotword 브랜치에 1커밋이 되었다고 뜨는데 어떠한 기능이 커밋이 되었나요..?
업데이트를 하였다가 혹시 작동이 안될까봐 ㅠㅠ 여쭈어봅니다..혹시 괜찮다면 업데이트 하는방법은 핫워드를 삭제하고 다시 git glone으로 해야하나요..?

한가지 이슈에 여러가지 질문을 드려서 죄송합니다..! 답변해주셔서 정말 감사합니다

**Comment by eouia** [comment]
1. 아마 CSS word-break 때문에 그럴거에요. width를 충분히 주시거나... 음.. CSS는 골치아파서. 여하튼, 이것저것 css 조정해보시면 될 겁니다. (MMM-Hotword.css 에 정의되어 있는 내용을 `MagicMirror/css/custom.css`에서 재정의 혹은 오버라이딩하시면 됩니다.)

2. 뭐.. 이 부분은 녹음 환경 같은 것도 중요하구요, sensitivity를 조절하시거나, 마이크 볼륨 등을 조절해보시거나. 정답이 없는 문제라서.

3. github 코드 목록 보시면 어떤 이유로 커밋되었는지 커밋로그가 남겨져 있습니다..만 제가 별로 자세히 적지는 않아서.
일단 snowboy 바이너리를 새로 컴파일 할 필요는 없기 때문에 그냥 MMM-Hotword 디렉토리에서 `git pull` 명령어 만으로 충분합니다. (소스 코드 안건드리셨죠?)

개인적으로 시맨틱 버저닝..을 개인적으로 사용하는데요. 현재 2.0.1 버전인데 2.1 또는 3.0이 되지 않는 한 리인스톨없이 `git pull`만으로 업데이트 가능하십니다.

**Comment by wjdalsrbekt** [comment]
정말 감사합니다 ^^  소스코드는 제가 config 로 pmdl로만 바꾼거 밖에 없습니다 ! git pull로 업데이트를 해봐야겠네요 !!

**Comment by mmssww** [comment]
> 원래는 한글을 하고싶은데 한글을 도전하기전에 영어로 먼저 도전해보려고하는데 작동하질 안네용..
스마트 미러에 대해서 도움 좀 받고 싶은데 괜찮을 까요?  
메일을 보내주면 문제점을 알려드리겠습니다

**Comment by wjdalsrbekt** [comment]
이 이슈는 닫혀있어서 그러는데 새로운 이슈를 열고 질문 하시면 될 것 같습니다 !!
