### ISSUE TITLE
MMM-Hotword can not install (ubuntu 18.04 desktop 64bit)

### ISSUE THREAD

**Issue by vipk31** [eouia/MMM-Hotword#74]
1. i install by guide:
Manual Install

> sudo apt update
> sudo apt upgrade
> sudo apt install libmagic-dev libatlas-base-dev sox libsox-fmt-all
> cd ~/MagicMirror/modules
> git clone https://github.com/eouia/MMM-Hotword.git
> cd MMM-Hotword
> chmod +x trainer/trainer.sh
> git clone https://github.com/Kitt-AI/snowboy.git
> cd snowboy
> rm -rf .git
> cp -r resources/models ..
> npm install -y nan node-pre-gyp
> ./node_modules/node-pre-gyp/bin/node-pre-gyp clean configure build
> npm install -y
> npm install -y electron-rebuild
> ./node_modules/.bin/electron-rebuild

ERROR STEP 
npm install -y nan node-pre-gyp
./node_modules/node-pre-gyp/bin/node-pre-gyp clean configure build

LOG INFOR

> thuan@kaka-pc:~/MagicMirror/modules/MMM-Hotword/snowboy$ ./node_modules/node-pre-gyp/bin/node-pre-gyp clean configure build
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@0.6.39
> node-pre-gyp info using node@10.16.2 | linux | x64
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.8.0
> gyp info using node@10.16.2 | linux | x64
> gyp info spawn /usr/bin/python2
> gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/thuan/MagicMirror/modules/MMM-Hotword/snowboy/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/thuan/.node-gyp/10.16.2/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/thuan/.node-gyp/10.16.2',
> gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
> gyp info spawn args   '-Dnode_lib_file=/home/thuan/.node-gyp/10.16.2/<(target_arch)/node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/home/thuan/MagicMirror/modules/MMM-Hotword/snowboy',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.' ]
> gyp info ok 
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.8.0
> gyp info using node@10.16.2 | linux | x64
> gyp ERR! build error 
> gyp ERR! stack Error: not found: make
> gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
> gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
> gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
> gyp ERR! System Linux 5.0.0-23-generic
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--module=/home/thuan/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-x64/snowboy.node" "--module_name=snowboy" "--module_path=/home/thuan/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-x64"
> gyp ERR! cwd /home/thuan/MagicMirror/modules/MMM-Hotword/snowboy
> gyp ERR! node -v v10.16.2
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/home/thuan/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-x64/snowboy.node --module_name=snowboy --module_path=/home/thuan/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-x64' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/thuan/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> node-pre-gyp ERR! System Linux 5.0.0-23-generic
> node-pre-gyp ERR! command "/usr/bin/node" "/home/thuan/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/node-pre-gyp/bin/node-pre-gyp" "clean" "configure" "build"
> node-pre-gyp ERR! cwd /home/thuan/MagicMirror/modules/MMM-Hotword/snowboy
> node-pre-gyp ERR! node -v v10.16.2
> node-pre-gyp ERR! node-pre-gyp -v v0.6.39
> node-pre-gyp ERR! not ok 
> Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/home/thuan/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-x64/snowboy.node --module_name=snowboy --module_path=/home/thuan/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-x64' (1)
> thuan@kaka-pc:~/MagicMirror/modules/MMM-Hotword/snowboy$ 
> 

I use Ubuntu dektop 18.04 64 bit
please help me

**Comment by vipk31** [comment]
evidence :
![Screenshot_2019-08-10_11-20-53](https://user-images.githubusercontent.com/12049629/62817449-29432980-bb61-11e9-9546-6a4ed101206b.png)

**Comment by eouia** [comment]
`not found: make` means you have not proper build-essential dependencies.
Try this then do again.
```
sudo apt-get install build-essential
```

**Comment by vipk31** [comment]
thanks very much
it worked !!
but I do not see install on guide

> sudo apt-get install build-essential
please add

**Comment by eouia** [comment]
@vipk31 Because common Raspbian (Stretch or Buster for RPI) has already those dependencies by default. But some unique machines(and some distributions of Ubuntu/Debian) have not on out-of-box state.
