### ISSUE TITLE
npm install -y fail

### ISSUE THREAD

**Issue by Zpider23** [eouia/MMM-Hotword#77]
When I get to this step it throws this error. 

`> snowboy@1.3.1 install /home/pi/MagicMirror/modules/MMM-Hotword/snowboy
> node-pre-gyp install --fallback-to-build

[snowboy] Success: "/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> snowboy@1.3.1 prepublish /home/pi/MagicMirror/modules/MMM-Hotword/snowboy
> tsc --listFiles

../../../node_modules/@types/unist/index.d.ts:31:20 - error TS2304: Cannot find name 'unknown'.

31     [key: string]: unknown;
                      ~~~~~~~


../../../node_modules/@types/unist/index.d.ts:40:20 - error TS2304: Cannot find name 'unknown'.

40     [key: string]: unknown;
                      ~~~~~~~

../../../node_modules/@types/unist/index.d.ts:97:12 - error TS2304: Cannot find name 'unknown'.

97     value: unknown;
              ~~~~~~~


../../../node_modules/@types/vfile-message/index.d.ts:69:24 - error TS2304: Cannot find name 'unknown'.

69         [key: string]: unknown;
                          ~~~~~~~

../../../node_modules/@types/vfile/index.d.ts:48:15 - error TS2304: Cannot find name 'unknown'.

48         data: unknown;
                 ~~~~~~~


/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/typescript/lib/lib.es6.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/index.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/node-pre-gyp.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/SnowboyDetectNative.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/@types/node/base.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/@types/node/index.d.ts
/home/pi/MagicMirror/node_modules/@types/events/index.d.ts
/home/pi/MagicMirror/node_modules/@types/minimatch/index.d.ts
/home/pi/MagicMirror/node_modules/@types/glob/index.d.ts
/home/pi/MagicMirror/node_modules/@types/unist/index.d.ts
/home/pi/MagicMirror/node_modules/@types/vfile-message/index.d.ts
/home/pi/MagicMirror/node_modules/@types/vfile/index.d.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! snowboy@1.3.1 prepublish: `tsc --listFiles`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the snowboy@1.3.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-09-07T01_08_27_849Z-debug.log
`

**Comment by Banhammer1919** [comment]
i have exactly the same problem on raspbian buster.

**Comment by Zpider23** [comment]
I found a solution by reflashing my sd card down to Raspbian Stretch

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
