### ISSUE TITLE
config파일이 잘 못 된건지..어디서 문제가 일어난지 모르겠습니다

### ISSUE THREAD

**Issue by Gyunnni** [eouia/MMM-Hotword#80]
pi@raspberrypi:~/MagicMirror $ npm start

 

> magicmirror@2.8.0 start /home/pi/MagicMirror

> sh run-start.sh

 

Starting MagicMirror: v2.8.0

Loading config ...

WARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: /home/pi/MagicMirror/config/config.js:3

  position: "top_right",

          ^

 

SyntaxError: Unexpected token :

    at new Script (vm.js:74:7)

    at createScript (vm.js:246:10)

    at Object.runInThisContext (vm.js:298:10)

    at Module._compile (internal/modules/cjs/loader.js:678:28)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)

    at Module.load (internal/modules/cjs/loader.js:620:32)

    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)

    at Function.Module._load (internal/modules/cjs/loader.js:551:3)

    at Module.require (internal/modules/cjs/loader.js:658:17)

    at require (internal/modules/cjs/helpers.js:20:18)

Loading module helpers ...

Initializing new module helper ...

Module helper loaded: updatenotification

No helper found for module: helloworld.

All module helpers loaded.

Starting server on port 8080 ... 

Server started ...

Connecting socket for: updatenotification

Sockets connected & modules started ...

Launching application.

Shutting down server...

Stopping module helper: updatenotification

 

--------------------------------------------------------------

config.js 

 

 

{

  module: "MMM-Hotword",

  position: "top_right",

  config: {

    chimeOnFinish: null,

    mic: {

      recordProgram: "arecord",

      device: "plughw:1"

    },

    models: [

      {

        hotwords    : "computer",

        file        : "computer.umdl",

        sensitivity : "0.5",

      },

    ],

    commands: {

      "computer": {

        notificationExec: {

          notification: "ASSISTANT_ACTIVATE",

          payload: (detected, afterRecord) => {

            return {profile:"default"}

          }

        },

        restart:false,

        afterRecordLimit:0

      }

    }

  }

},

detectorAudioGain: 2.0,

detectorApplyFrontend: false, // When you are using `.pmdl`, set this to `false`.

// For `.umdl`, When you use only`snowboy` and `smart_mirror`, `false` is better. But with other models, `true` is better.

 

mic: {

  recordProgram : "rec", //record prgram, `rec`, `arecord`, `sox`, `parec` is available

  device        : null,

  sampleRate    : 16000,  // audio sample rate

  channels      : 1,      // number of channels

  threshold     : 0.5,

  thresholdStart: null,

  thresholdEnd  : null,

  silence       : 1.0, // detect end of your hotword or afterRecord.

  verbose       : false,  // log info to the console

},

 

recipes: [],

models: [],

commands: {},

defaultCommand: {

  notificationExec: {

    notification: "HOTWORD_DETECTED",

    payload: (detected, afterRecord) => {

      return {hotword:detected, file:afterRecord}

    }

  }

},

 

chimeOnFinish: "resources/ding.wav", // If you don't want to use chime, set this to null.

useDisplay: true,

iconify: "https://code.iconify.design/1/1.0.2/iconify.min.js",

//iconify: null,

//When you use this module with `MMM-CalendarExt2`, `MMM-Spotify` or any other `iconify` used modules together, Set this to null.

 

icons: { //https://iconify.design/icon-sets/

  waiting: "uil-comment-message",

  detected: "uil-comment-exclamation",

  finished: "uil-comment-dots",

},

 

// customizable notification trigger

notifications: {

  PAUSE: "HOTWORD_PAUSE",

  RESUME: "HOTWORD_RESUME",

  LISTENING : "HOTWORD_LISTENING",

  SLEEPING : "HOTWORD_SLEEPING",

  ERROR : "HOTWORD_ERROR",

  DETECTED: "HOTWORD_DETECTED"

},

mic: {

  recordProgram : "rec", //record prgram, `rec`, `arecord`, `sox`, `parec` is available

  device        : null,

  sampleRate    : 16000,  // audio sample rate

  channels      : 1,      // number of channels

  threshold     : 0.5,

  thresholdStart: null,

  thresholdEnd  : null,

  silence       : 1.0, // detect end of your hotword or afterRecord.

  verbose       : false,  // log info to the console

},

{

  hotwords    : "hello_mirror",

  file        : "hello_mirror.pmdl", // Personal model of your voice "Hello mirror"

  sensitivity : "0.5",

}

**Comment by eouia** [comment]
config.js 가 완전히 틀렸네요. 
https://github.com/MichMich/MagicMirror/blob/master/config/config.js.sample
여기의 각 모듈이 추가된 것 처럼 MMM-Hotword관련 config도 추가하시면 됩니다. 그냥 전체를 바꿔버리신 것 같네요.
그리고, 필요없는 필드들은 굳이 적으실 필요도 없고(어차피 디폴트값으로 전부 들어있음), 보면 같은 필드를 두번 적으신 것도 있고(문법상으로는 틀리지는 않았어도, 저렇게 쓰면 의도한 것과는 다르죠.).
여하튼... MMM-Hotword 모듈 이전에 MagicMirror 자체에 대해 더 공부하셔야 할 것 같습니다.

**Comment by eouia** [comment]
이번엔, MMM-Hotword에 관한 config을 config.js에 포함시키지 않으셨는데요.

**Comment by Gyunnni** [comment]
이번엔 스마트 미러가 제대로 작동 되었습니다. 하지만 음성인식은 제대로 되지 않아 문의드립니다. https://github.com/eouia/MMM-Hotword/blob/master/documents/config.md#simple-configuration-example에 올리신 것을 보고 mic test를 해야 한다는 것은 알고 있습니다.다만 MMM-Hotword만 enable하고 다른것은  disable을 어떻게 하는지 잘 모르겠습니다.

**Comment by Gyunnni** [comment]
해결 되었습니다. 감사합니다!!
