### ISSUE TITLE
Hotword not listening

### ISSUE THREAD

**Issue by zikotrance** [eouia/MMM-Hotword#82]
Hi eouia, 

First I wanna thank you for all the effort your doing on those modules :) 
I have issues interacting with the mirror.It does listen to one single time at the beggining but nothing after that.

**Here what I see in the command line:** 
pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Launching application.
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] No model to load
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Started with text query: hello
{ requestId: '5d9eceb3-0000-27dd-96f1-089e082471a8' } { profileFile: 'default.json', lang: 'en-US' }
[AMK2] Device Action: { requestId: '5d9eceb3-0000-27dd-96f1-089e082471a8' }
[AMK2] Assistant Text Response: 
[AMK2] Conversation Completed
[HOTWORD] No model to load
Shutting down server...
Stopping module helper: MMM-Hotword
Stopping module helper: MMM-AssistantMk2
pi@raspberrypi:~/MagicMirror $ 

> **Here what I see in the console:**

main.js:454 Initializing MagicMirror.
translator.js:202 Loading core translation file: translations/en.json
translator.js:225 Loading core translation fallback file: translations/en.json
loader.js:179 Load script: modules/MMM-Hotword//MMM-Hotword.js
module.js:476 Module registered: MMM-Hotword
loader.js:150 Bootstrapping module: MMM-Hotword
loader.js:179 Load script: https://code.iconify.design/1/1.0.2/iconify.min.js
loader.js:155 Scripts loaded for: MMM-Hotword
loader.js:194 Load stylesheet: modules/MMM-Hotword/MMM-Hotword.css
loader.js:157 Styles loaded for: MMM-Hotword
loader.js:159 Translations loaded for: MMM-Hotword
loader.js:179 Load script: modules/MMM-AssistantMk2//MMM-AssistantMk2.js
module.js:476 Module registered: MMM-AssistantMk2
loader.js:150 Bootstrapping module: MMM-AssistantMk2
loader.js:179 Load script: modules/MMM-AssistantMk2/vendor/serialize.js
loader.js:155 Scripts loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: modules/MMM-AssistantMk2/MMM-AssistantMk2.css
loader.js:157 Styles loaded for: MMM-AssistantMk2
loader.js:159 Translations loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: css/custom.css
main.js:472 All modules started!
:8080/modules/MMM-AssistantMk2//MMM-AssistantMk2.js:333 [AMK2]  YouTube iframe API is ready.
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:127 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
    protocols.This exposes users of this app to unnecessary security risks.
    Consider loading the following resources over HTTPS or FTPS. 
 - http://localhost:8080/css/main.css
- http://localhost:8080/fonts/roboto.css
- http://localhost:8080/socket.io/socket.io.js
- http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://localhost:8080/js/defaults.js
- http://localhost:8080/config/config.js
- http://localhost:8080/vendor/vendor.js
- http://localhost:8080/modules/default/defaultmodules.js
- http://localhost:8080/js/logger.js
- http://localhost:8080/translations/translations.js
- http://localhost:8080/js/translator.js
- http://localhost:8080/js/class.js
- http://localhost:8080/js/module.js
- http://localhost:8080/js/loader.js
- http://localhost:8080/js/socketclient.js
- http://localhost:8080/js/main.js
- http://localhost:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://localhost:8080/translations/en.json
- http://localhost:8080/translations/en.json
- http://localhost:8080/modules/MMM-Hotword//MMM-Hotword.js
- http://localhost:8080/modules/MMM-Hotword/MMM-Hotword.css
- http://localhost:8080/modules/MMM-AssistantMk2//MMM-AssistantMk2.js
- http://localhost:8080/modules/MMM-AssistantMk2/vendor/serialize.js
- http://localhost:8080/modules/MMM-AssistantMk2/MMM-AssistantMk2.css
- http://localhost:8080/css/custom.css
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MseQlp7
- http://localhost:8080/modules/MMM-AssistantMk2/resources/assistant.png
- http://localhost:8080/modules/MMM-Hotword/resources/ding.wav
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MseQlqj&sid=x3FQmcWwMKSHK_bJAAAA
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MseQlqt&sid=x3FQmcWwMKSHK_bJAAAA
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MseQlrL&sid=x3FQmcWwMKSHK_bJAAAA
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MseQlrR&sid=x3FQmcWwMKSHK_bJAAAA
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MseQls2&sid=x3FQmcWwMKSHK_bJAAAA
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MseQls5&sid=x3FQmcWwMKSHK_bJAAAA
    
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureResources @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:127
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:184 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
      Policy set or a policy with "unsafe-eval" enabled. This exposes users of
      this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureCSP @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:184

> **I'm using AIY Google voice HAT and here's the details:**

pi@raspberrypi:~/MagicMirror $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpigooglevoi [snd_rpi_googlevoicehat_soundcar], device 0: Google voiceHAT SoundCard HiFi voicehat-codec-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

pi@raspberrypi:~/MagicMirror $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: sndrpigooglevoi [snd_rpi_googlevoicehat_soundcar], device 0: Google voiceHAT SoundCard HiFi voicehat-codec-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

> **And this is my config file:**

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "celsius",

	modules: [
//		{
//			module: "alert",
//		},
//		{
//			module: "updatenotification",
//			position: "top_bar"
//		},
//		{
//			module: "clock",
//			position: "top_left"
//		},
//		{
//			module: "calendar",
//			header: "US Holidays",
//			position: "top_left",
//			config: {
//				calendars: [
//					{
//						symbol: "calendar-check-o ",
//						url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
//					}
//				]
//			}
//		},

{
	module: "MMM-Hotword",
	position: "top_right",
	detectorAudioGain: 2.0,
	detectorApplyFrontend: false, // When you are using `.pmdl`, set this to `false`.
	// For `.umdl`, When you use only`snowboy` and `smart_mirror`, `false` is better. But with other models, `true` is better.
	config: {
		chimeOnFinish: null,

		mic: {
		  recordProgram : "rec", //record prgram, `rec`, `arecord`, `sox`, `parec` is available
		  device        : null,
		  sampleRate    : 16000,  // audio sample rate
		  channels      : 1,      // number of channels
		  threshold     : 0.5,
		  thresholdStart: null,
		  thresholdEnd  : null,
		  silence       : 1.0, // detect end of your hotword or afterRecord.
		  verbose       : false,  // log info to the console
		},

		recipes: [],
		models: [],
		commands: {},
		defaultCommand: {
		  notificationExec: {
		    notification: "HOTWORD_DETECTED",
		    payload: (detected, afterRecord) => {
		      return {hotword:detected, file:afterRecord}
		    }
		  }
		},

		chimeOnFinish: "resources/ding.wav", // If you don't want to use chime, set this to null.
		useDisplay: true,
		iconify: "https://code.iconify.design/1/1.0.2/iconify.min.js",
		//iconify: null,
		//When you use this module with `MMM-CalendarExt2`, `MMM-Spotify` or any other `iconify` used modules together, Set this to null.

		icons: { //https://iconify.design/icon-sets/
		  waiting: "uil-comment-message",
		  detected: "uil-comment-exclamation",
		  finished: "uil-comment-dots",
		},

		// customizable notification trigger
		notifications: {
		  PAUSE: "HOTWORD_PAUSE",
		  RESUME: "HOTWORD_RESUME",
		  LISTENING : "HOTWORD_LISTENING",
		  SLEEPING : "HOTWORD_SLEEPING",
		  ERROR : "HOTWORD_ERROR",
		  DETECTED: "HOTWORD_DETECTED"
		},

     }
    
  
},

{
	module: "MMM-AssistantMk2",
	position: "top_right",
	config: {
		deviceLocation: {
			coordinates: {
				latitude: 37.5650168, // -90.0 - +90.0
				longitude: 126.8491231, // -180.0 - +180.0
			},
		},
		record: {
			recordProgram : "arecord",  
			device        : "plughw:0,0",
		},
		notifications: {
			ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
			ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
		},
		useWelcomeMessage: "hello",
		profiles: {
			"default" : {
				lang: "en-US"
			}
		},
	}
},		

	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

I'm able to see HOTWORD and Google Assistant Logo and I hear a sound saying: How can I help you after that its silence. 

Please help

**Comment by eouia** [comment]
First, the reason might be `[HOTWORD] No model to load`. You didn't assign `model` in configuration.
Second, You don't need to describe ALL fields of the configuration of MMM-Hotword, They are already defined as default values. When you need to modify some specific values, you can reassign those.

Conclusion; your configuration was wrong.
Start from here ; https://github.com/eouia/MMM-Hotword/blob/master/documents/config.md#simple-configuration-example
