### ISSUE TITLE
Speaker error: 1 오류 때문에 문의 드립니다.

### ISSUE THREAD

**Issue by YounhJunJin** [eouia/MMM-Hotword#84]
[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }
Speaker error: 1
Whoops! There was an uncaught exception...
1
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

음성인식이 잘 되다가 갑자기 저런 에러가 뜨고나서 음성인식이 되질 않습니다.
해결방법 문의 하고싶습니다.

**Comment by eouia** [comment]
스피커가 잘 안닫긴 것 같습니다. 혹시 전체 config과 로그를 볼 수 있을까요?
(eouia0819@gmail.com)

**Comment by YounhJunJin** [comment]
스피커 설정이 문제였던거 같습니다.

 pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.!default {
        type plug
        slave.pcm "dmixer"
}

pcm.dmixer  {
        type dmix
        ipc_key 1024
        slave {
                pcm "hw:1,0"
                period_time 0
                period_size 1024
                buffer_size 4096
                rate 44100
        }
        bindings {
                0 0
                1 1
        }
}

ctl.dmixer {
        type hw
        card 0
}

로 하고나니 잘됩니다. 감사합니다
