### ISSUE TITLE
unsure if a hotword issue or a assistant issue

### ISSUE THREAD

**Issue by sy8282** [eouia/MMM-Hotword#86]
[AMK2] assistant ready
/home/pi/MagicMirror/node_modules/electron/dist/electron js/electron.js: symbol lookup error: /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node: undefined symbol: __atomic_store_8
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! magicmirror@2.9.0 start: `sh run-start.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the magicmirror@2.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-10-25T11_45_50_286Z-debug.log

**Comment by sy8282** [comment]
the mirror starts listens registers the activation word then crashes to desktop 
not sure where i messed up

**Comment by eouia** [comment]
That would be MMM-AssistantMk2 issue. (duplicated). I'll inspect.
