### ISSUE TITLE
no microphone/speech icon 

### ISSUE THREAD

**Issue by sy8282** [eouia/MMM-Hotword#87]
hi after a complete reinstall i have assistant mk2 starting playing the brief today 
had a few errors installing snowboy
/home/pi/node_modules/@types/bytebuffer/index.d.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! snowboy@1.3.1 prepublish: `tsc --listFiles`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the snowboy@1.3.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

would this explain the no detection or even speech detection icon from showing and working 
if so anyone know how to fix this error

**Comment by eouia** [comment]
Your MMM-Hotword is not installed properly.
To make things simple, 
- backup your current `config.js`. and make new one with only `MMM-Hotword` to test. (other modules should be eliminated from config)

We can go further after confirmation of working MMM-Hotword.

Then, execute MM and show me the whole error logs and your new configuration.

**Comment by sy8282** [comment]
changed config to just run hotword 
still no microphone or listening symbol

[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Detected: smart_mirror
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'smart_mirror', file: null }

terminal reports this

**Comment by eouia** [comment]
Well, the log says your MMM-Hotword works well. It heard your voice and detected `smart_mirror` which you've said. 
So, the next step is, add `MMM-AssistantMk2` in your config.
Remove `useWelcomeMessage`. (you need some setup to use that feature with MMM-Hotword, in this test, just remove it.)
Then test again.

**Comment by sy8282** [comment]
weird i used the basic config without the usewelcome message and it detected the question once responded but then it wont respond a second time
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Detected: smart_mirror
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'smart_mirror', file: null }
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response: 
[AMK2] Transcription: what  --- Done: false
[AMK2] Transcription: what's  --- Done: false
[AMK2] Transcription: what time  --- Done: false
[AMK2] Transcription: what time is  --- Done: false
[AMK2] Transcription: what time is it  --- Done: false
[AMK2] Transcription: what time is it today  --- Done: false
[AMK2] Transcription: what time is it today  --- Done: false
[AMK2] Transcription: what time is it today  --- Done: false
[AMK2] Transcription: what time is it today  --- Done: false
[AMK2] end-of-utterance
[AMK2] Transcription: what time is it today  --- Done: true
{ requestId: '****' } { profileFile: 'default.json', lang: 'en-US' }
[AMK2] Device Action: { requestId: '****' }
[AMK2] Assistant Text Response: 
[AMK2] Conversation Completed

**Comment by sy8282** [comment]
{
  module: "MMM-Hotword",
  position: "top_right",
  config: {
    chimeOnFinish: null,
    mic: {
      recordProgram: "arecord",
      device: "plughw:1"
    },
    models: [
      {
        hotwords    : "computer",
        file        : "computer.umdl",
        sensitivity : "0.5",
      },
    ],
    commands: {
      "computer": {
        notificationExec: {
          notification: "ASSISTANT_ACTIVATE",
          payload: (detected, afterRecord) => {
            return {profile:"default"}
          }
        },
        restart:false,
        afterRecordLimit:0
      }
    }
  }
},
just used this config from your git documents and it detects and has the speech bubble icon but still only listens and responds once

**Comment by eouia** [comment]
Because Your MMM-AssistantMk2 config should be proper to use together with MMM-Hotword.
Your config of MMM-Hotword looks perfect now.
See this configuration sample for MMM-AssistantMk2 and MMM-Hotword (`with MMM-Hotword(v2)` section)
https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration#with-mmm-hotwordv2

**Comment by sy8282** [comment]
ok im an idiot

notifications: {
      ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
      ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
    },
added this to my assistant config and it continues to listen so seems all good

is there anything special i need to add to allow the mirror to control devices connected to my google home mini?

**Comment by sy8282** [comment]
thanks for your help buddy 
sorry for being a noob

**Comment by eouia** [comment]
If your IoT devices are registered on your existing real Google Home network, 
You need to register MM as one of your Google Home network device. (Read the docs of MMM-AssistantMk2), 
Or you can make simple commands through IFTTT to control your IoTs.
Give me more details.

**Comment by sy8282** [comment]
I will have to test that later today or tomorrow my kid just woke from a
nap, i will report back asap. Again thanks for your patience looking at it
now the answer was staring me in the face the whole time
