### ISSUE TITLE
설치만 6시간 짼데 도저히 안돼서 문의드립니다

### ISSUE THREAD

**Issue by nhpunch** [eouia/MMM-Hotword#88]
`
pi@raspberrypi:~ $ cd ~/MagicMirror/modules

pi@raspberrypi:~/MagicMirror/modules $ git clone https://github.com/eouia/MMM-Hotword.git

Cloning into 'MMM-Hotword'...

remote: Enumerating objects: 98, done.

remote: Counting objects: 100% (98/98), done.

remote: Compressing objects: 100% (83/83), done.

remote: Total 314 (delta 57), reused 31 (delta 15), pack-reused 216

Receiving objects: 100% (314/314), 8.02 MiB | 2.47 MiB/s, done.

Resolving deltas: 100% (173/173), done.

pi@raspberrypi:~/MagicMirror/modules $ cd MMM-Hotword

pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ chmod +x ./installer/install.sh

pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ ./installer/install.sh

Cloning into 'snowboy'...

remote: Enumerating objects: 18, done.

remote: Counting objects: 100% (18/18), done.

remote: Compressing objects: 100% (16/16), done.

remote: Total 2145 (delta 5), reused 5 (delta 2), pack-reused 2127

Receiving objects: 100% (2145/2145), 55.22 MiB | 3.44 MiB/s, done.

Resolving deltas: 100% (1064/1064), done.

npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.

npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.

npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

npm notice created a lockfile as package-lock.json. You should commit this file.

+ nan@2.14.0

+ node-pre-gyp@0.6.39

added 115 packages from 85 contributors and audited 269 packages in 17.639s

found 8 moderate severity vulnerabilities

  run `npm audit fix` to fix them, or `npm audit` for details

node-pre-gyp info it worked if it ends with ok

node-pre-gyp info using node-pre-gyp@0.6.39

node-pre-gyp info using node@10.17.0 | linux | arm

gyp info it worked if it ends with ok

gyp info using node-gyp@4.0.0

gyp info using node@10.17.0 | linux | arm

gyp info spawn /usr/bin/python2

gyp info spawn args [ '/home/pi/MagicMirror/node_modules/node-gyp/gyp/gyp_main.py',

gyp info spawn args   'binding.gyp',

gyp info spawn args   '-f',

gyp info spawn args   'make',

gyp info spawn args   '-I',

gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build/config.gypi',

gyp info spawn args   '-I',

gyp info spawn args   '/home/pi/MagicMirror/node_modules/node-gyp/addon.gypi',

gyp info spawn args   '-I',

gyp info spawn args   '/home/pi/.node-gyp/10.17.0/include/node/common.gypi',

gyp info spawn args   '-Dlibrary=shared_library',

gyp info spawn args   '-Dvisibility=default',

gyp info spawn args   '-Dnode_root_dir=/home/pi/.node-gyp/10.17.0',

gyp info spawn args   '-Dnode_gyp_dir=/home/pi/MagicMirror/node_modules/node-gyp',

gyp info spawn args   '-Dnode_lib_file=/home/pi/.node-gyp/10.17.0/<(target_arch)/node.lib',

gyp info spawn args   '-Dmodule_root_dir=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy',

gyp info spawn args   '-Dnode_engine=v8',

gyp info spawn args   '--depth=.',

gyp info spawn args   '--no-parallel',

gyp info spawn args   '--generator-output',

gyp info spawn args   'build',

gyp info spawn args   '-Goutput_dir=.' ]

gyp info ok 

gyp info it worked if it ends with ok

gyp info using node-gyp@4.0.0

gyp info using node@10.17.0 | linux | arm

gyp info spawn make

gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]

make: Entering directory '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build'

  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o

  SOLINK_MODULE(target) Release/obj.target/snowboy.node

/usr/bin/ld: cannot find -lcblas

collect2: error: ld returned 1 exit status

snowboy.target.mk:139: recipe for target 'Release/obj.target/snowboy.node' failed

make: *** [Release/obj.target/snowboy.node] Error 1

make: Leaving directory '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build'

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/node_modules/node-gyp/lib/build.js:262:23)

gyp ERR! stack     at ChildProcess.emit (events.js:198:13)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

gyp ERR! System Linux 4.14.79-v7+

gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/node_modules/node-gyp/bin/node-gyp.js" "build" "--module=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm"

gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/snowboy

gyp ERR! node -v v10.17.0

gyp ERR! node-gyp -v v4.0.0

gyp ERR! not ok 

node-pre-gyp ERR! build error 

node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /home/pi/MagicMirror/node_modules/node-gyp/bin/node-gyp.js build --module=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)

node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/node-pre-gyp/lib/util/compile.js:83:29)

node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)

node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)

node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

node-pre-gyp ERR! System Linux 4.14.79-v7+

node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/node-pre-gyp/bin/node-pre-gyp" "clean" "configure" "build"

node-pre-gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/snowboy

node-pre-gyp ERR! node -v v10.17.0

node-pre-gyp ERR! node-pre-gyp -v v0.6.39

node-pre-gyp ERR! not ok 

Failed to execute '/usr/bin/node /home/pi/MagicMirror/node_modules/node-gyp/bin/node-gyp.js build --module=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)

 

> snowboy@1.3.1 install /home/pi/MagicMirror/modules/MMM-Hotword/snowboy

> node-pre-gyp install --fallback-to-build

 

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 

node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.17.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 

node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 

node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.17.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 

make: Entering directory '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build'

  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o

make: Entering directory '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build'

  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o

sed: can't read ./Release/.deps/Release/obj.target/snowboy/swig/Node/snowboy.o.d.raw: No such file or directory

  SOLINK_MODULE(target) Release/obj.target/snowboy.node

rm: cannot remove './Release/.deps/Release/obj.target/snowboy/swig/Node/snowboy.o.d.raw': No such file or directory

snowboy.target.mk:109: recipe for target 'Release/obj.target/snowboy/swig/Node/snowboy.o' failed

make: *** [Release/obj.target/snowboy/swig/Node/snowboy.o] Error 1

make: Leaving directory '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build'

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:193:23)

gyp ERR! stack     at ChildProcess.emit (events.js:198:13)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

gyp ERR! System Linux 4.14.79-v7+

gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm"

gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/snowboy

gyp ERR! node -v v10.17.0

gyp ERR! node-gyp -v v5.0.3

gyp ERR! not ok 

node-pre-gyp ERR! build error 

node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)

node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/node-pre-gyp/lib/util/compile.js:83:29)

node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)

node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)

node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

node-pre-gyp ERR! System Linux 4.14.79-v7+

node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"

node-pre-gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/snowboy

node-pre-gyp ERR! node -v v10.17.0

node-pre-gyp ERR! node-pre-gyp -v v0.6.39

node-pre-gyp ERR! not ok 

Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! snowboy@1.3.1 install: `node-pre-gyp install --fallback-to-build`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the snowboy@1.3.1 install script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

 

npm ERR! A complete log of this run can be found in:

npm ERR!     /home/pi/.npm/_logs/2019-11-08T09_28_37_291Z-debug.log

/usr/bin/ld: cannot find -lcblas

collect2: error: ld returned 1 exit status

snowboy.target.mk:139: recipe for target 'Release/obj.target/snowboy.node' failed

make: *** [Release/obj.target/snowboy.node] Error 1

make: Leaving directory '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build'

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:193:23)

gyp ERR! stack     at ChildProcess.emit (events.js:198:13)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

gyp ERR! System Linux 4.14.79-v7+

gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm"

gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/snowboy

gyp ERR! node -v v10.17.0

gyp ERR! node-gyp -v v5.0.3

gyp ERR! not ok 

+ electron-rebuild@1.8.6

added 91 packages from 76 contributors, removed 30 packages and audited 508 packages in 23.95s

found 8 moderate severity vulnerabilities

  run `npm audit fix` to fix them, or `npm audit` for details

âœ– Rebuild Failed

 

An unhandled error occurred inside electron-rebuild

gyp info it worked if it ends with ok

gyp info using node-gyp@5.0.5

gyp info using node@10.17.0 | linux | arm

gyp info find Python using Python version 2.7.13 found at "/usr/bin/python"

gyp info spawn /usr/bin/python

gyp info spawn args [ '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/node-gyp/gyp/gyp_main.py',

gyp info spawn args   'binding.gyp',

gyp info spawn args   '-f',

gyp info spawn args   'make',

gyp info spawn args   '-I',

gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build/config.gypi',

gyp info spawn args   '-I',

gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/node-gyp/addon.gypi',

gyp info spawn args   '-I',

gyp info spawn args   '/home/pi/.electron-gyp/iojs-3.0.13/common.gypi',

gyp info spawn args   '-Dlibrary=shared_library',

gyp info spawn args   '-Dvisibility=default',

gyp info spawn args   '-Dnode_root_dir=/home/pi/.electron-gyp/iojs-3.0.13',

gyp info spawn args   '-Dnode_gyp_dir=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/node-gyp',

gyp info spawn args   '-Dnode_lib_file=/home/pi/.electron-gyp/iojs-3.0.13/<(target_arch)/iojs.lib',

gyp info spawn args   '-Dmodule_root_dir=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy',

gyp info spawn args   '-Dnode_engine=v8',

gyp info spawn args   '--depth=.',

gyp info spawn args   '--no-parallel',

gyp info spawn args   '--generator-output',

gyp info spawn args   'build',

gyp info spawn args   '-Goutput_dir=.' ]

gyp info spawn make

gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]

make: Entering directory '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build'

  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o

  SOLINK_MODULE(target) Release/obj.target/snowboy.node

/usr/bin/ld: cannot find -lcblas

collect2: error: ld returned 1 exit status

snowboy.target.mk:137: recipe for target 'Release/obj.target/snowboy.node' failed

make: Leaving directory '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build'

make: *** [Release/obj.target/snowboy.node] Error 1

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/node-gyp/lib/build.js:194:23)

gyp ERR! stack     at ChildProcess.emit (events.js:198:13)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

gyp ERR! System Linux 4.14.79-v7+

gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/.bin/node-gyp" "rebuild" "--target=3.0.13" "--arch=arm" "--dist-url=https://electronjs.org/headers" "--build-from-source" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/electron-v3.0-linux-arm" "--remote_path=./snowboy/v1.3.1/Release/" "--package_name=snowboy-v1.3.1-electron-v3.0-linux-arm.tar.gz" "--host=https://snowboy-release-node.s3-us-west-2.amazonaws.com"

gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/snowboy

gyp ERR! node -v v10.17.0

gyp ERR! node-gyp -v v5.0.5

gyp ERR! not ok 

 

Failed with exit code: 1

 

Error: gyp info it worked if it ends with ok

gyp info using node-gyp@5.0.5

gyp info using node@10.17.0 | linux | arm

gyp info find Python using Python version 2.7.13 found at "/usr/bin/python"

gyp info spawn /usr/bin/python

gyp info spawn args [ '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/node-gyp/gyp/gyp_main.py',

gyp info spawn args   'binding.gyp',

gyp info spawn args   '-f',

gyp info spawn args   'make',

gyp info spawn args   '-I',

gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build/config.gypi',

gyp info spawn args   '-I',

gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/node-gyp/addon.gypi',

gyp info spawn args   '-I',

gyp info spawn args   '/home/pi/.electron-gyp/iojs-3.0.13/common.gypi',

gyp info spawn args   '-Dlibrary=shared_library',

gyp info spawn args   '-Dvisibility=default',

gyp info spawn args   '-Dnode_root_dir=/home/pi/.electron-gyp/iojs-3.0.13',

gyp info spawn args   '-Dnode_gyp_dir=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/node-gyp',

gyp info spawn args   '-Dnode_lib_file=/home/pi/.electron-gyp/iojs-3.0.13/<(target_arch)/iojs.lib',

gyp info spawn args   '-Dmodule_root_dir=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy',

gyp info spawn args   '-Dnode_engine=v8',

gyp info spawn args   '--depth=.',

gyp info spawn args   '--no-parallel',

gyp info spawn args   '--generator-output',

gyp info spawn args   'build',

gyp info spawn args   '-Goutput_dir=.' ]

gyp info spawn make

gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]

make: Entering directory '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build'

  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o

  SOLINK_MODULE(target) Release/obj.target/snowboy.node

/usr/bin/ld: cannot find -lcblas

collect2: error: ld returned 1 exit status

snowboy.target.mk:137: recipe for target 'Release/obj.target/snowboy.node' failed

make: Leaving directory '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build'

make: *** [Release/obj.target/snowboy.node] Error 1

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/node-gyp/lib/build.js:194:23)

gyp ERR! stack     at ChildProcess.emit (events.js:198:13)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

gyp ERR! System Linux 4.14.79-v7+

gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/.bin/node-gyp" "rebuild" "--target=3.0.13" "--arch=arm" "--dist-url=https://electronjs.org/headers" "--build-from-source" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/electron-v3.0-linux-arm" "--remote_path=./snowboy/v1.3.1/Release/" "--package_name=snowboy-v1.3.1-electron-v3.0-linux-arm.tar.gz" "--host=https://snowboy-release-node.s3-us-west-2.amazonaws.com"

gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/snowboy

gyp ERR! node -v v10.17.0

gyp ERR! node-gyp -v v5.0.5

gyp ERR! not ok 

 

Failed with exit code: 1

    at SafeSubscriber._error (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/spawn-rx/lib/src/index.js:267:84)

    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/rxjs/internal/Subscriber.js:205:16)

    at SafeSubscriber.error (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/rxjs/internal/Subscriber.js:156:26)

    at Subscriber._error (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/rxjs/internal/Subscriber.js:92:26)

    at Subscriber.error (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/rxjs/internal/Subscriber.js:72:18)

    at MapSubscriber.Subscriber._error (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/rxjs/internal/Subscriber.js:92:26)

    at MapSubscriber.Subscriber.error (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/rxjs/internal/Subscriber.js:72:18)

    at SafeSubscriber._next (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/spawn-rx/lib/src/index.js:242:65)

    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/rxjs/internal/Subscriber.js:205:16)

    at SafeSubscriber.next (/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/rxjs/internal/Subscriber.js:143:22)

node-v64-linux-arm

ls: cannot access 'lib/node/index.js': No such file or directory

pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ `

자동설치로도 여러번하고, 수동설치로도 수십번했는데 안되네요..

도움주시면 감사하겠습니다

**Comment by eouia** [comment]
1. 사용하고 계신 Raspberry Pi OS 버전이 어떻게 되시나요?
2. 이 부분 하셨나요?
```
sudo apt update
sudo apt upgrade
sudo apt install libmagic-dev libatlas-base-dev sox libsox-fmt-all
```
에러 중에 보면 `/usr/bin/ld: cannot find -lcblas` 가 있던데, 보통 위 과정을 실패할 경우 나올 겁니다.

3. 이전에 설치시도하실 때 생긴 `package-lock.json`이 문제가 있는 것 같은데, 새로 설치하실 때 디렉토리를 전부 지우고 다시 하신건가요?
```
npm notice created a lockfile as package-lock.json. You should commit this file.
nan@2.14.0
node-pre-gyp@0.6.39
```

**Comment by nhpunch** [comment]
우선 답변 정말 감사합니다.

1. 라즈비안 스트레치이고, 다른 모듈들은 이런 오류가 한번도 뜬적이 없이 잘 사용중입니다.

2. sudo apt update
sudo apt upgrade
sudo apt install libmagic-dev libatlas-base-dev sox libsox-fmt-all 항목에 대해서 진행하였는데

에러같은건 뜨지 않았는데 마지막에 네트워크 연결 잘 되는 곳으로 가서 확인했을때 다른 식으로 진행이 된걸 확인이 되었고 그게 바르게 진행이 된거라고 생각해서 차근차근 시도하였지만 역시 안됐습니다.

3. 디렉토리라는 건 클론한 MMM-Hotword 폴더를 말씀하시는 거라면 대부분 지우고 다시 하기도 하였지만 그대로 덮어씌워서 진행한적이 한두번있을겁니다.

**Comment by eouia** [comment]
1. 다른 모듈들은 이 만큼의 dependencies들을 필요로 하지 않을 만큼 간단하니까요. 아마 제일 설치가 어려운 모듈이 MMM-Hotword와 MMM-AssistantMk2 일겁니다. :D

2. 일단 특별한 에러가 없었다면 다행입니다만,
저걸 다 실행했는데도, `/usr/bin/ld` 에러가 나왔다면, build-essentials 패키지가 없어서일 수 있습니다. 그런데 보통 stretch에는 기본적으로 깔려있을텐데요. 
ld는 C/C++ compile시 쓰는 linker인데요, 이게 없다는 건 개발환경이 맞춰지지 않았다는 뜻입니다. 흠... 아마 OS 설치시에는 있었는데, 무슨 이유로 삭제되었던가 끊어졌다든가 했겠죠. 그렇다는 이야기는 아마 gcc 같은 것도 제대로 안깔려있을 것 같네요.

```
sudo apt-get install build-essential
```
이거 실행하시고 다시 시도해보시기 바랍니다.



3. 덮어씌워서는 안되는게 `package-lock.json`이 있으면 문제가 될 수 있거든요. 물론 업데이트시에는 매우 필수적인 파일입니다만, 신규설치시에는 문제의 소지가 될 수 있습니다.

**Comment by nhpunch** [comment]
`sudo apt-get install build-essential`

이건 초기에 업데이트, 업그레이드 전에 실행하고 처음부터 진행하면 되는건가요? 해보고 코멘트 드리도록 하겠습니다!

**Comment by eouia** [comment]
```
sudo apt update
sudo apt upgrade
```
이건 최근에 하셨다면 포맷하지 않은 이상 바로 안하셔도 됩니다.
그래도 가끔 주기적, 혹은 다른 apt 관련 작업하시기 전에 한번씩 해주시면 좋아요. 최근 업데이트/업그레이드된 apt 패키지가 있으면 갱신하라는 거니까 시스템을 항상 최신으로 유지하기 위해서 필요하지요.

... Raspbian Stretch는 요즘 링크 구하기도 힘드실텐데 어디서 구하셨대요. ^^;;; 전부 Buster로 올라갔을텐데...

**Comment by nhpunch** [comment]
앗 알겠습니다 그 밑으로 해서 진행해보고 코멘트 드리겠습니다

Raspbian Stretch는 올해 4월에 다운받아서 다른 기능들 구현 후 마무리로 기능들 수행할 수 있는 음성명령을 해보려고 하는 중입니다

**Comment by nhpunch** [comment]
설치 잘 되었습니다 감사합니다 근데 마이크는 정상인데 Hotword가 detected false네요 ㅠㅠ

**Comment by eouia** [comment]
볼륨이나 감도 아니면 발음 문제일 겁니다. 좀 더 큰 소리로 명확히 해보세요.

**Comment by nhpunch** [comment]
그러네요 발음을 정확히 해야 인식을 하네요 감사합니다 감도는 0.1~1 이렇게 있는데 정확히 어떤식으로 이해하면 될까요?
