### ISSUE TITLE
안녕하세요 선생님 살려주세요

### ISSUE THREAD

**Issue by nohsangwoo** [eouia/MMM-Hotword#90]
하라는대로 한거같은데 분명 제가 뭔가 잘못했겠죠 ㅠ 
뭘잘못했는지를 모르는 미천한 저에게 답을 알려주시면 감사하겠습니다.
assistant-Mk2랑 Hotword 설치후 실행까지는 잘되고 마이크 인식도 되는거같은데
smart mirror라고 말하면 띵똥 거리면서 튕겨요
튕기면서 나오는 내용은 아래와 같고요.ㅜㅜ

/home/pi/MagicMirror/node_modules/electron/dist/electron js/electron.js: symbol lookup error: /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node: undefined symbol: __atomic_store_8
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! magicmirror@2.9.0 start: `sh run-start.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the magicmirror@2.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-11-14T09_22_49_514Z-debug.log

로그내용은 아래와 같습니다
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.13.0
3 info using node@v12.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle magicmirror@2.9.0~prestart: magicmirror@2.9.0
6 info lifecycle magicmirror@2.9.0~start: magicmirror@2.9.0
7 verbose lifecycle magicmirror@2.9.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle magicmirror@2.9.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/MagicMirror/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle magicmirror@2.9.0~start: CWD: /home/pi/MagicMirror
10 silly lifecycle magicmirror@2.9.0~start: Args: [ '-c', 'sh run-start.sh' ]
11 info lifecycle magicmirror@2.9.0~start: Failed to exec start script
12 verbose stack Error: magicmirror@2.9.0 start: `sh run-start.sh`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:210:5)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
13 verbose pkgid magicmirror@2.9.0
14 verbose cwd /home/pi/MagicMirror
15 verbose Linux 4.19.75-v7+
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v12.13.0
18 verbose npm  v6.13.0
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error magicmirror@2.9.0 start: `sh run-start.sh`
23 error spawn ENOENT
24 error Failed at the magicmirror@2.9.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

------------------------------------MMM-Hotword 설치시 에러 내용-------------------
MMM-Hotword 에서 문제가 생긴건진 확실하지 않고요 다만 재설치를해도 계속 생기는 에러가 문제인가 싶기도 하고 그래서 그부분도 복사해서 써놓을께요 ㅠ

pi@raspberrypi:~/MagicMirror/modules $ git clone https://github.com/eouia/MMM-Hotword.git
'MMM-Hotword'에 복제합니다...
remote: Enumerating objects: 98, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 314 (delta 57), reused 31 (delta 15), pack-reused 216
오브젝트를 받는 중: 100% (314/314), 8.02 MiB | 1.23 MiB/s, 완료.
델타를 알아내는 중: 100% (173/173), 완료.
pi@raspberrypi:~/MagicMirror/modules $ cd MMM-Hotword
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ chmod +x ./installer/install.sh
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ ./installer/install.sh
'snowboy'에 복제합니다...
remote: Enumerating objects: 2145, done.
remote: Total 2145 (delta 0), reused 0 (delta 0), pack-reused 2145
오브젝트를 받는 중: 100% (2145/2145), 55.22 MiB | 3.67 MiB/s, 완료.
델타를 알아내는 중: 100% (1072/1072), 완료.
파일을 가져옵니다: 100% (313/313), 완료.
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm notice created a lockfile as package-lock.json. You should commit this file.
+ nan@2.14.0
+ node-pre-gyp@0.6.39
added 115 packages from 85 contributors and audited 269 packages in 32.644s

1 package is looking for funding.
Run "npm fund" to find out more.
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@12.13.0 | linux | arm
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.13.0 | linux | arm
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.cache/node-gyp/12.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.cache/node-gyp/12.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.cache/node-gyp/12.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.13.0 | linux | arm
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: 디렉터리 '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build' 들어감
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
In file included from ../swig/Node/snowboy.cc:1:
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../node_modules/nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../swig/Node/snowboy.cc: In constructor ‘SnowboyDetect::SnowboyDetect(const string&, const string&)’:
../swig/Node/snowboy.cc:38:31: warning: catching polymorphic type ‘class std::runtime_error’ by value [-Wcatch-value=]
   } catch (std::runtime_error e) {
                               ^
In file included from ../node_modules/nan/nan.h:54,
                 from ../swig/Node/snowboy.cc:1:
../swig/Node/snowboy.cc: At global scope:
/home/pi/.cache/node-gyp/12.13.0/include/node/node.h:560:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.cache/node-gyp/12.13.0/include/node/node.h:594:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../swig/Node/snowboy.cc:183:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(SnowboyDetect, SnowboyDetect::Init)
 ^~~~~~~~~~~
In file included from /home/pi/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:54,
                 from ../swig/Node/snowboy.cc:1:
/home/pi/.cache/node-gyp/12.13.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/pi/.cache/node-gyp/12.13.0/include/node/node_object_wrap.h:84:78:   required from here
/home/pi/.cache/node-gyp/12.13.0/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/.cache/node-gyp/12.13.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../node_modules/nan/nan_object_wrap.h:65:61:   required from here
/home/pi/.cache/node-gyp/12.13.0/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
  COPY Release/snowboy.node
  COPY /home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v72-linux-arm/snowboy.node
  TOUCH Release/obj.target/action_after_build.stamp
make: 디렉터리 '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build' 나감
gyp info ok 
node-pre-gyp info ok 

> snowboy@1.3.1 install /home/pi/MagicMirror/modules/MMM-Hotword/snowboy
> node-pre-gyp install --fallback-to-build

[snowboy] Success: "/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v72-linux-arm/snowboy.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> snowboy@1.3.1 prepublish /home/pi/MagicMirror/modules/MMM-Hotword/snowboy
> tsc --listFiles

../../../node_modules/@types/unist/index.d.ts:31:20 - error TS2304: Cannot find name 'unknown'.

31     [key: string]: unknown;
                      ~~~~~~~


../../../node_modules/@types/unist/index.d.ts:40:20 - error TS2304: Cannot find name 'unknown'.

40     [key: string]: unknown;
                      ~~~~~~~

../../../node_modules/@types/unist/index.d.ts:97:12 - error TS2304: Cannot find name 'unknown'.

97     value: unknown;
              ~~~~~~~


../../../node_modules/@types/vfile/index.d.ts:48:15 - error TS2304: Cannot find name 'unknown'.

48         data: unknown;
                 ~~~~~~~

../../../node_modules/vfile-message/types/index.d.ts:67:20 - error TS2304: Cannot find name 'unknown'.

67     [key: string]: unknown
                      ~~~~~~~


/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/typescript/lib/lib.es6.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/index.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/node-pre-gyp.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/SnowboyDetectNative.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/@types/node/base.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/@types/node/index.d.ts
/home/pi/MagicMirror/node_modules/@types/events/index.d.ts
/home/pi/MagicMirror/node_modules/@types/minimatch/index.d.ts
/home/pi/MagicMirror/node_modules/@types/glob/index.d.ts
/home/pi/MagicMirror/node_modules/@types/unist/index.d.ts
/home/pi/MagicMirror/node_modules/vfile-message/types/index.d.ts
/home/pi/MagicMirror/node_modules/@types/vfile/index.d.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! snowboy@1.3.1 prepublish: `tsc --listFiles`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the snowboy@1.3.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-11-14T09_10_31_485Z-debug.log
+ electron-rebuild@1.8.6
added 91 packages from 76 contributors, removed 30 packages and audited 508 packages in 42.041s

1 package is looking for funding.
Run "npm fund" to find out more.
✔ Rebuild Complete
electron-v3.0-linux-arm  node-v72-linux-arm
lib/node/index.js


아래는 제 라즈비안 상태이구욤
apt upgrade했구요 ㅠ 이것저것 찾다가 gcc도 7.x로 설치하라셔서 설치했어요 
근데 왜 튕기는건지 모르겠습니다. ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ
답답해 죽겠어요 살려주세요 선생님

pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ sudo apt-get install build-essential
패키지 목록을 읽는 중입니다... 완료
의존성 트리를 만드는 중입니다       
상태 정보를 읽는 중입니다... 완료
build-essential is already the newest version (12.6).
0개 업그레이드, 0개 새로 설치, 0개 제거 및 0개 업그레이드 안 함.
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ npm -v
6.13.0
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ node -v
v12.13.0
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ gcc --version
gcc (Raspbian 7.3.0-19) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

선생님이 계신쪽으로 절 하면서 글쓰고 있습니다 부디 답변을 주신다면 감사하겠습니다.

**Comment by nohsangwoo** [comment]
아참 그리고
Raspbian Buster with desktop and recommended software는 충돌이 있을수도 있다고 하신글을 봐서


Raspbian Buster with desktop로 설치하고 진행했습니다 ㅠㅠ...흐어...

**Comment by eouia** [comment]
grpc@1.24 이슈로 electron-rebuild 한 결과가 현재 MagicMirror의 electron과 충돌하는 것 같습니다.
https://github.com/eouia/MMM-AssistantMk2#some-more-troubleshooting 의 첫번째 항목 보시고 grpc@1.24 대신 1.23으로 바꿔서 설치하세요.

**Comment by nohsangwoo** [comment]
해보겠습니당 ㅠㅠㅠㅠ 감사합니다

**Comment by nohsangwoo** [comment]
돼요! 감사합니다 사랑합니다.!
