### ISSUE TITLE
Error when installing snowboy

### ISSUE THREAD

**Issue by tanvir586** [eouia/MMM-Hotword#93]
../../../node_modules/@types/unist/index.d.ts:31:20 - error TS2304: Cannot find name 'unknown'.

31     [key: string]: unknown;
                      ~~~~~~~


../../../node_modules/@types/unist/index.d.ts:40:20 - error TS2304: Cannot find name 'unknown'.

40     [key: string]: unknown;
                      ~~~~~~~

../../../node_modules/@types/unist/index.d.ts:97:12 - error TS2304: Cannot find name 'unknown'.

97     value: unknown;
              ~~~~~~~


../../../node_modules/@types/vfile/index.d.ts:48:15 - error TS2304: Cannot find name 'unknown'.

48         data: unknown;
                 ~~~~~~~

../../../node_modules/vfile-message/types/index.d.ts:67:20 - error TS2304: Cannot find name 'unknown'.

67     [key: string]: unknown
                      ~~~~~~~


/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/typescript/lib/lib.es6.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/index.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/node-pre-gyp.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/SnowboyDetectNative.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/@types/node/base.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/@types/node/index.d.ts
/home/pi/MagicMirror/node_modules/@types/events/index.d.ts
/home/pi/MagicMirror/node_modules/@types/minimatch/index.d.ts
/home/pi/MagicMirror/node_modules/@types/glob/index.d.ts
/home/pi/MagicMirror/node_modules/@types/unist/index.d.ts
/home/pi/MagicMirror/node_modules/vfile-message/types/index.d.ts
/home/pi/MagicMirror/node_modules/@types/vfile/index.d.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! snowboy@1.3.1 prepublish: `tsc --listFiles`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the snowboy@1.3.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-11-27T04_59_07_079Z-debug.log

Plz help

**Comment by eouia** [comment]
Well, some errors could be not important.
What is the last 3 lines of the result of auto installation?

If,
```
✔ Rebuild Complete
electron-v3.0-linux-arm node-v72-linux-arm    #It could be different, something similar.
lib/node/index.js
```
these lines are displayed, your installation is completed.

**Comment by tanvir586** [comment]
Thanks for reply.  
Yes the last 3 line was that. 
Will check today and let you know.

**Comment by tanvir586** [comment]
hi . thanks it worked. but i have another problem. when i say magic mirror it detect but my mirror stop working with this error

[HOTWORD] Detected: smart_mirror
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'smart_mirror', file: null }
[AMK2] assistant ready
/home/pi/MagicMirror/node_modules/electron/dist/electron js/electron.js: symbol lookup error: /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node: undefined symbol: __atomic_store_8
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! magicmirror@2.9.0 start: `sh run-start.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the magicmirror@2.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-11-27T18_25_19_251Z-debug.log

**Comment by eouia** [comment]
That is another issue. You've failed to install `MMM-AssistantMk2`, especially on `electron-rebuild` step, due to `grpc@1.24` issue. There is also a guide about it on that module.
