### ISSUE TITLE
Can't npm install google spreadsheets

### ISSUE THREAD

**Issue by Pyra745** [eouia/MMM-Hotword#95]
Hi, I'm trying to install google spreadsheets with the command "npm install google-spreadsheets@2.0.3" but it gives me this error. I don't know how to fix this, any help will be greatly appreciated.

$ npm install google-spreadsheet@2.0.3
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN enoent ENOENT: no such file or directory, open '/storage/emulated/0/Secsec/package.json'
npm WARN discord.js@11.5.1 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN Secsec No description
npm WARN Secsec No repository field.
npm WARN Secsec No README data
npm WARN Secsec No license field.

npm ERR! code EPERM
npm ERR! syscall symlink
npm ERR! path ../mime/cli.js
npm ERR! dest /storage/emulated/0/Secsec/node_modules/google-spreadsheet/node_modules/.bin/mime
npm ERR! errno -1
npm ERR! Error: EPERM: operation not permitted, symlink '../mime/cli.js' -> '/storage/emulated/0/Secsec/node_modules/google-spreadsheet/node_modules/.bin/mime'
npm ERR!  [OperationalError: EPERM: operation not permitted, symlink '../mime/cli.js' -> '/storage/emulated/0/Secsec/node_modules/google-spreadsheet/node_modules/.bin/mime'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, symlink '../mime/cli.js' -> '/storage/emulated/0/Secsec/node_modules/google-spreadsheet/node_modules/.bin/mime'] {
npm ERR!     errno: -1,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'symlink',
npm ERR!     path: '../mime/cli.js',
npm ERR!     dest: '/storage/emulated/0/Secsec/node_modules/google-spreadsheet/node_modules/.bin/mime'
npm ERR!   },
npm ERR!   stack: "Error: EPERM: operation not permitted, symlink '../mime/cli.js' -> '/storage/emulated/0/Secsec/node_modules/google-spreadsheet/node_modules/.bin/mime'",
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../mime/cli.js',
npm ERR!   dest: '/storage/emulated/0/Secsec/node_modules/google-spreadsheet/node_modules/.bin/mime',
npm ERR!   parent: 'google-spreadsheet'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2019-12-01T23_57_30_142Z-debug.log

**Comment by eouia** [comment]
You probably posted this issue on wrong project.
