### ISSUE TITLE
현재 https://snowboy.kitt.ai/ 인증서가 만료되었습니다..

### ISSUE THREAD

**Issue by nhpunch** [eouia/MMM-Hotword#97]
그래스 스노우보이 공식 이메일로 갱신요청한 상황인데

급히 pmdl파일을 하나 만들어야 하는데 

인증서가 만료된 상황에서 trainer.sh를 사용해서 제작할 수 있나요?

아니면 다른 방법이 아예 없는지 궁금합니다..

**Comment by eouia** [comment]
글쎄요. 인증서라는 거, 웹브라우저 단에서 작동하는 거 아닌가요? 
curl 쓰는 거라서 웹 인증과는 관계없을 것 같은데.. 테스트는 안해봤는데 trainer.sh 안의 엔드포인트 주소를 http로 바꾸면 큰 상관없지 싶긴 한데요. 테스트는 안해봤지만.

**Comment by nhpunch** [comment]
`pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.7.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.7.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-Serial-Notifications
Initializing new module helper ...
Module helper loaded: MMM-KVV
No helper found for module: mm-hide-all.
Initializing new module helper ...
Module helper loaded: MMM-Water
Initializing new module helper ...
Module helper loaded: MMM-Door
Initializing new module helper ...
Module helper loaded: MMM-PushBulletNotifications
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: MMM-Serial-Notifications
Connecting socket for: MMM-KVV
Starting node helper for: MMM-KVV
Connecting socket for: MMM-Water
Connecting socket for: MMM-Door
Connecting socket for: MMM-PushBulletNotifications
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Launching application.
false
false
[MMM-PushBulletNotifications][Info] 11:23:05.961 - START received
Create new news fetcher for url: https://news.google.com/rss?cf=all&hl=ko&gl=KR&ceid=KR:ko - Interval: 300000
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/somyeong03%40gmail.com/private-84c61c6d2fdb3b61dcb7b43763e943eb/basic.ics - Interval: 3600000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
write
port Close
(node:3249) UnhandledPromiseRejectionWarning: Error: Error Resource temporarily unavailable Cannot lock port
(node:3249) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3249) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[AMK2] Temporal storage directory is clearing.
ERROR (ClassifyModels():pipeline-detect.cc:713) PipelineDetect: undefined model type detected. Most likely you provided the wrong model.
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR (ClassifyModels():pipeline-detect.cc:713) PipelineDetect: undefined model type detected. Most likely you provided the wrong model.

[stack trace: ]
Backtrace has not been implemented yet.
`

**Comment by nhpunch** [comment]
말씀하신대로 해서 htts 로 수정 후 했는데 pmdl 파일 확장자가 제대로 만들어지지 않고 html 파일로 만들어지네요.. 그래서 config에 추가해서 사용했는데 역시 안되고 터미널에 저렇게 뜨네요 ㅠ

**Comment by eouia** [comment]
kitt-ai 쪽에서는 오늘 복구된다고 하네요.
